spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://47.93.184.40:3306/x-energy-db?characterEncoding=utf-8&connectTimeout=3000
    username: root
    password: root
  mvc:
    view:
      prefix: /pages/
      suffix: .jsp
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration

mybatis:
  type-aliases-package: com.xhkj.server.energy.dao
  mapper-locations: classpath:mapping/*Mapper.xml

energy:
  create-fake-data-ip: 172.17.160.138
  run-data-handler: false

# 打印sql
logging:
  level:
    com.xhkj.server.energy.dao: debug
#    com.xhkj.server.energy.dao: info

debug: true