package com.xhkj.server.energy.dao.mybatis.mapper;

import com.xhkj.server.energy.dao.mybatis.vo.GroupData;
import com.xhkj.server.energy.dao.mybatis.vo.GroupDataExample;
import com.xhkj.server.energy.dao.mybatis.vo.GroupDataKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface GroupDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_group
     *
     * @mbg.generated
     */
    long countByExample(GroupDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_group
     *
     * @mbg.generated
     */
    int deleteByExample(GroupDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_group
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(GroupDataKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_group
     *
     * @mbg.generated
     */
    int insert(GroupData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_group
     *
     * @mbg.generated
     */
    int insertSelective(GroupData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_group
     *
     * @mbg.generated
     */
    List<GroupData> selectByExample(GroupDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_group
     *
     * @mbg.generated
     */
    GroupData selectByPrimaryKey(GroupDataKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_group
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GroupData record, @Param("example") GroupDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_group
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GroupData record, @Param("example") GroupDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GroupData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GroupData record);


    ////*******自定义开始********/
    //***********自定义结束****////
}
