package com.xhkj.server.energy.dao.mybatis.mapper;

import com.xhkj.server.energy.dao.mybatis.vo.MenuItem;
import com.xhkj.server.energy.dao.mybatis.vo.MenuItemExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Set;

public interface MenuItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu_item
     *
     * @mbg.generated
     */
    long countByExample(MenuItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu_item
     *
     * @mbg.generated
     */
    int deleteByExample(MenuItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu_item
     *
     * @mbg.generated
     */
    int insert(MenuItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu_item
     *
     * @mbg.generated
     */
    int insertSelective(MenuItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu_item
     *
     * @mbg.generated
     */
    List<MenuItem> selectByExample(MenuItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu_item
     *
     * @mbg.generated
     */
    MenuItem selectByPrimaryKey(Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu_item
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MenuItem record, @Param("example") MenuItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu_item
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MenuItem record, @Param("example") MenuItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MenuItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MenuItem record);


    ////*******自定义开始********/
    List<MenuItem> getItemByRoleId(String roleId);

    Set<String> getPermissionsByRoleIds(String[] ids);
    //***********自定义结束****////
}
