package com.xhkj.server.energy.dao.mybatis.mapper;

import com.xhkj.server.energy.dao.mybatis.vo.OprInfo;
import com.xhkj.server.energy.dao.mybatis.vo.OprInfoExample;
import com.xhkj.server.energy.page.BootstrapTableParams;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface OprInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_opr_info
     *
     * @mbg.generated
     */
    long countByExample(OprInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_opr_info
     *
     * @mbg.generated
     */
    int deleteByExample(OprInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_opr_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer oprId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_opr_info
     *
     * @mbg.generated
     */
    int insert(OprInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_opr_info
     *
     * @mbg.generated
     */
    int insertSelective(OprInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_opr_info
     *
     * @mbg.generated
     */
    List<OprInfo> selectByExample(OprInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_opr_info
     *
     * @mbg.generated
     */
    OprInfo selectByPrimaryKey(Integer oprId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_opr_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OprInfo record, @Param("example") OprInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_opr_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") OprInfo record, @Param("example") OprInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_opr_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OprInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_opr_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OprInfo record);


    ////*******自定义开始********/
    void deleteOprRoleRel(Map<String, Object> delRoleMap);

    void insertOprRoleRel(List<Map<String, Object>> roleList);

    int getCountByLoginId(String loginId);

    int modifyPassword(Map<String, Object> paramMap);

    OprInfo getByLoginId(String loginId);

    List<OprInfo> getAll(BootstrapTableParams params);

    OprInfo getById(Integer oprId);
    //***********自定义结束****////
}
