package com.xhkj.server.energy.dao.mybatis.mapper;

import com.xhkj.server.energy.dao.mybatis.vo.OprInfoLoginLog;
import com.xhkj.server.energy.dao.mybatis.vo.OprInfoLoginLogExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface OprInfoLoginLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_opr_info_login_log
     *
     * @mbg.generated
     */
    long countByExample(OprInfoLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_opr_info_login_log
     *
     * @mbg.generated
     */
    int deleteByExample(OprInfoLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_opr_info_login_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_opr_info_login_log
     *
     * @mbg.generated
     */
    int insert(OprInfoLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_opr_info_login_log
     *
     * @mbg.generated
     */
    int insertSelective(OprInfoLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_opr_info_login_log
     *
     * @mbg.generated
     */
    List<OprInfoLoginLog> selectByExample(OprInfoLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_opr_info_login_log
     *
     * @mbg.generated
     */
    OprInfoLoginLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_opr_info_login_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OprInfoLoginLog record, @Param("example") OprInfoLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_opr_info_login_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") OprInfoLoginLog record, @Param("example") OprInfoLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_opr_info_login_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OprInfoLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_opr_info_login_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OprInfoLoginLog record);

    ////*******自定义开始********/
    Map<String, Object> getLoginLastDt(String loginId);
    //***********自定义结束****////
}
