package com.xhkj.server.energy.dao.mybatis.mapper;

import com.xhkj.server.energy.dao.mybatis.vo.PredictStation;
import com.xhkj.server.energy.dao.mybatis.vo.PredictStationExample;
import com.xhkj.server.energy.dao.mybatis.vo.PredictStationKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PredictStationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_predict_station
     *
     * @mbg.generated
     */
    long countByExample(PredictStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_predict_station
     *
     * @mbg.generated
     */
    int deleteByExample(PredictStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_predict_station
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(PredictStationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_predict_station
     *
     * @mbg.generated
     */
    int insert(PredictStation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_predict_station
     *
     * @mbg.generated
     */
    int insertSelective(PredictStation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_predict_station
     *
     * @mbg.generated
     */
    List<PredictStation> selectByExample(PredictStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_predict_station
     *
     * @mbg.generated
     */
    PredictStation selectByPrimaryKey(PredictStationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_predict_station
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PredictStation record, @Param("example") PredictStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_predict_station
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PredictStation record, @Param("example") PredictStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_predict_station
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PredictStation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_predict_station
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PredictStation record);


    ////*******自定义开始********/
    //***********自定义结束****////
}
