package com.xhkj.server.energy.dao.mybatis.mapper;

import com.xhkj.server.energy.dao.mybatis.vo.PredictData;
import com.xhkj.server.energy.dao.mybatis.vo.PredictDataExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PredictDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_para
     *
     * @mbg.generated
     */
    long countByExample(PredictDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_para
     *
     * @mbg.generated
     */
    int deleteByExample(PredictDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_para
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String cityName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_para
     *
     * @mbg.generated
     */
    int insert(PredictData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_para
     *
     * @mbg.generated
     */
    int insertSelective(PredictData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_para
     *
     * @mbg.generated
     */
    List<PredictData> selectByExample(PredictDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_para
     *
     * @mbg.generated
     */
    PredictData selectByPrimaryKey(String cityName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_para
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PredictData record, @Param("example") PredictDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_para
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PredictData record, @Param("example") PredictDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_para
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PredictData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_para
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PredictData record);


    ////*******自定义开始********/

    //一般是一个数据，暂时没有用list
    PredictData getThePredict();

    //根据主键（城市名）修改记录，只有一个城市，写死了
    Integer updateHaErBinSelective(PredictData predictData);

    //***********自定义结束****////
}
