package com.xhkj.server.energy.dao.mybatis.mapper;

import com.xhkj.server.energy.dao.mybatis.vo.Price;
import com.xhkj.server.energy.dao.mybatis.vo.PriceExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_price
     *
     * @mbg.generated
     */
    long countByExample(PriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_price
     *
     * @mbg.generated
     */
    int deleteByExample(PriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_price
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer companyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_price
     *
     * @mbg.generated
     */
    int insert(Price record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_price
     *
     * @mbg.generated
     */
    int insertSelective(Price record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_price
     *
     * @mbg.generated
     */
    List<Price> selectByExample(PriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_price
     *
     * @mbg.generated
     */
    Price selectByPrimaryKey(Integer companyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_price
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Price record, @Param("example") PriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_price
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Price record, @Param("example") PriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_price
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Price record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_price
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Price record);


    ////*******自定义开始********/
    //***********自定义结束****////
}
