package com.xhkj.server.energy.dao.mybatis.mapper;

import com.xhkj.server.energy.dao.mybatis.vo.StandData;
import com.xhkj.server.energy.dao.mybatis.vo.StandDataExample;
import com.xhkj.server.energy.dao.mybatis.vo.StandDataKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface StandDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_stand
     *
     * @mbg.generated
     */
    long countByExample(StandDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_stand
     *
     * @mbg.generated
     */
    int deleteByExample(StandDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_stand
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(StandDataKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_stand
     *
     * @mbg.generated
     */
    int insert(StandData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_stand
     *
     * @mbg.generated
     */
    int insertSelective(StandData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_stand
     *
     * @mbg.generated
     */
    List<StandData> selectByExample(StandDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_stand
     *
     * @mbg.generated
     */
    StandData selectByPrimaryKey(StandDataKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_stand
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") StandData record, @Param("example") StandDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_stand
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") StandData record, @Param("example") StandDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_stand
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StandData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_stand
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StandData record);


    ////*******自定义开始********/
    //***********自定义结束****////
}
