package com.xhkj.server.energy.dao.mybatis.mapper;

import com.xhkj.server.energy.dao.mybatis.vo.StandBasicData;
import com.xhkj.server.energy.dao.mybatis.vo.StandBasicDataExample;
import com.xhkj.server.energy.dao.mybatis.vo.StandBasicDataKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface StandBasicDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_stand_basic
     *
     * @mbg.generated
     */
    long countByExample(StandBasicDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_stand_basic
     *
     * @mbg.generated
     */
    int deleteByExample(StandBasicDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_stand_basic
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(StandBasicDataKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_stand_basic
     *
     * @mbg.generated
     */
    int insert(StandBasicData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_stand_basic
     *
     * @mbg.generated
     */
    int insertSelective(StandBasicData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_stand_basic
     *
     * @mbg.generated
     */
    List<StandBasicData> selectByExample(StandBasicDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_stand_basic
     *
     * @mbg.generated
     */
    StandBasicData selectByPrimaryKey(StandBasicDataKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_stand_basic
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") StandBasicData record, @Param("example") StandBasicDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_stand_basic
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") StandBasicData record, @Param("example") StandBasicDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_stand_basic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StandBasicData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_stand_basic
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StandBasicData record);


    ////*******自定义开始********/
    //***********自定义结束****////
}
