package com.xhkj.server.energy.dao.mybatis.mapper;

import com.xhkj.server.energy.dao.mybatis.vo.TecolCurveData;
import com.xhkj.server.energy.dao.mybatis.vo.TecolCurveDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TecolCurveDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_tecol_curve
     *
     * @mbg.generated
     */
    long countByExample(TecolCurveDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_tecol_curve
     *
     * @mbg.generated
     */
    int deleteByExample(TecolCurveDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_tecol_curve
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short temperature);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_tecol_curve
     *
     * @mbg.generated
     */
    int insert(TecolCurveData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_tecol_curve
     *
     * @mbg.generated
     */
    int insertSelective(TecolCurveData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_tecol_curve
     *
     * @mbg.generated
     */
    List<TecolCurveData> selectByExample(TecolCurveDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_tecol_curve
     *
     * @mbg.generated
     */
    TecolCurveData selectByPrimaryKey(Short temperature);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_tecol_curve
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TecolCurveData record, @Param("example") TecolCurveDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_tecol_curve
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TecolCurveData record, @Param("example") TecolCurveDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_tecol_curve
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TecolCurveData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_tecol_curve
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TecolCurveData record);


    ////*******自定义开始********/
    //***********自定义结束****////
}
