package com.xhkj.server.energy.dao.mybatis.mapper;

import com.xhkj.server.energy.dao.mybatis.vo.TecolCurveCulData;
import com.xhkj.server.energy.dao.mybatis.vo.TecolCurveCulDataExample;
import java.util.List;

import com.xhkj.server.energy.dao.mybatis.vo.TecolCurveCulDataKey;
import org.apache.ibatis.annotations.Param;

public interface TecolCurveCulDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_tecol_curve_cul
     *
     * @mbg.generated
     */
    long countByExample(TecolCurveCulDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_tecol_curve_cul
     *
     * @mbg.generated
     */
    int deleteByExample(TecolCurveCulDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_tecol_curve_cul
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TecolCurveCulDataKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_tecol_curve_cul
     *
     * @mbg.generated
     */
    int insert(TecolCurveCulData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_tecol_curve_cul
     *
     * @mbg.generated
     */
    int insertSelective(TecolCurveCulData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_tecol_curve_cul
     *
     * @mbg.generated
     */
    List<TecolCurveCulData> selectByExample(TecolCurveCulDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_tecol_curve_cul
     *
     * @mbg.generated
     */
    TecolCurveCulData selectByPrimaryKey(TecolCurveCulDataKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_tecol_curve_cul
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TecolCurveCulData record, @Param("example") TecolCurveCulDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_tecol_curve_cul
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TecolCurveCulData record, @Param("example") TecolCurveCulDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_tecol_curve_cul
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TecolCurveCulData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_tecol_curve_cul
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TecolCurveCulData record);


    ////*******自定义开始********/
    //***********自定义结束****////
}
