package com.xhkj.server.energy.dao.mybatis.mapper;

import com.xhkj.server.energy.dao.mybatis.vo.Valve;
import com.xhkj.server.energy.dao.mybatis.vo.ValveExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface ValveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_valve
     *
     * @mbg.generated
     */
    long countByExample(ValveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_valve
     *
     * @mbg.generated
     */
    int deleteByExample(ValveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_valve
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_valve
     *
     * @mbg.generated
     */
    int insert(Valve record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_valve
     *
     * @mbg.generated
     */
    int insertSelective(Valve record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_valve
     *
     * @mbg.generated
     */
    List<Valve> selectByExample(ValveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_valve
     *
     * @mbg.generated
     */
    Valve selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_valve
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Valve record, @Param("example") ValveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_valve
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Valve record, @Param("example") ValveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_valve
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Valve record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_valve
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Valve record);


    ////*******自定义开始********/
    List<Valve> getAll(Map<String, String> params);
    //***********自定义结束****////
}
