package com.xhkj.server.energy.dao.mybatis.mapper;

import com.xhkj.server.energy.dao.mybatis.vo.WaterTemperatureData;
import com.xhkj.server.energy.dao.mybatis.vo.WaterTemperatureDataExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface WaterTemperatureDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_water_temperature
     *
     * @mbg.generated
     */
    long countByExample(WaterTemperatureDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_water_temperature
     *
     * @mbg.generated
     */
    int deleteByExample(WaterTemperatureDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_water_temperature
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short temperature);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_water_temperature
     *
     * @mbg.generated
     */
    int insert(WaterTemperatureData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_water_temperature
     *
     * @mbg.generated
     */
    int insertSelective(WaterTemperatureData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_water_temperature
     *
     * @mbg.generated
     */
    List<WaterTemperatureData> selectByExample(WaterTemperatureDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_water_temperature
     *
     * @mbg.generated
     */
    WaterTemperatureData selectByPrimaryKey(Short temperature);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_water_temperature
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WaterTemperatureData record, @Param("example") WaterTemperatureDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_water_temperature
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WaterTemperatureData record, @Param("example") WaterTemperatureDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_water_temperature
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WaterTemperatureData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_water_temperature
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WaterTemperatureData record);


    ////*******自定义开始********/
    //***********自定义结束****////
}
