package com.xhkj.server.energy.dao.mybatis.mapper;

import com.xhkj.server.energy.dao.mybatis.vo.WeatherData;
import com.xhkj.server.energy.dao.mybatis.vo.WeatherDataExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface WeatherDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_weather
     *
     * @mbg.generated
     */
    long countByExample(WeatherDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_weather
     *
     * @mbg.generated
     */
    int deleteByExample(WeatherDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_weather
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_weather
     *
     * @mbg.generated
     */
    int insert(WeatherData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_weather
     *
     * @mbg.generated
     */
    int insertSelective(WeatherData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_weather
     *
     * @mbg.generated
     */
    List<WeatherData> selectByExample(WeatherDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_weather
     *
     * @mbg.generated
     */
    WeatherData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_weather
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WeatherData record, @Param("example") WeatherDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_weather
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WeatherData record, @Param("example") WeatherDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_weather
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WeatherData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_weather
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WeatherData record);

    ////*******自定义开始********/

    List<WeatherData> getAvgTemList(Map<String, String> map);

    List<WeatherData> getInDays(String[] array);

    //***********自定义结束****////
}
