package com.xhkj.server.energy.dao.mybatis.mapper;

import com.xhkj.server.energy.dao.mybatis.vo.WeatherDataStal;
import com.xhkj.server.energy.dao.mybatis.vo.WeatherDataStalExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface WeatherDataStalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_weather_stal
     *
     * @mbg.generated
     */
    long countByExample(WeatherDataStalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_weather_stal
     *
     * @mbg.generated
     */
    int deleteByExample(WeatherDataStalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_weather_stal
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_weather_stal
     *
     * @mbg.generated
     */
    int insert(WeatherDataStal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_weather_stal
     *
     * @mbg.generated
     */
    int insertSelective(WeatherDataStal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_weather_stal
     *
     * @mbg.generated
     */
    List<WeatherDataStal> selectByExample(WeatherDataStalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_weather_stal
     *
     * @mbg.generated
     */
    WeatherDataStal selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_weather_stal
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WeatherDataStal record, @Param("example") WeatherDataStalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_weather_stal
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WeatherDataStal record, @Param("example") WeatherDataStalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_weather_stal
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WeatherDataStal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_weather_stal
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WeatherDataStal record);


    ////*******自定义开始********/

    /**
     * 根据日期获取一条记录
     */
    List<WeatherDataStal> getListByDay(@Param("day")String day);

    /**
     * 获取一条今日的最新记录
     */
    WeatherDataStal getWeatherStalCurrent(@Param("crtDt")String day);

    //***********自定义结束****////
}
