package com.xhkj.server.energy.dao.mybatis.vo;

import java.util.Date;

public class CollectData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_collect.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_collect.COMPANY_ID
     *
     * @mbg.generated
     */
    private Integer companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_collect.STAND_ID
     *
     * @mbg.generated
     */
    private String standId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_collect.STATION_ID
     *
     * @mbg.generated
     */
    private String stationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_collect.GROUP_ID
     *
     * @mbg.generated
     */
    private String groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_collect.OP_TIME
     *
     * @mbg.generated
     */
    private Date opTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_collect.PT1
     *
     * @mbg.generated
     */
    private Float pt1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_collect.PT2
     *
     * @mbg.generated
     */
    private Float pt2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_collect.TE1
     *
     * @mbg.generated
     */
    private Float te1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_collect.TE2
     *
     * @mbg.generated
     */
    private Float te2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_collect.CVI1
     *
     * @mbg.generated
     */
    private Float cvi1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_collect.QI
     *
     * @mbg.generated
     */
    private Float qi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_collect.FT1
     *
     * @mbg.generated
     */
    private Float ft1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_collect.FT1Q
     *
     * @mbg.generated
     */
    private Float ft1q;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_collect.PT3
     *
     * @mbg.generated
     */
    private Float pt3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_collect.PT4
     *
     * @mbg.generated
     */
    private Float pt4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_collect.TE3
     *
     * @mbg.generated
     */
    private Float te3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_collect.TE4
     *
     * @mbg.generated
     */
    private Float te4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_collect.FT2
     *
     * @mbg.generated
     */
    private Float ft2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_collect.FT3
     *
     * @mbg.generated
     */
    private Float ft3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_collect.FC1V1
     *
     * @mbg.generated
     */
    private Float fc1v1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_collect.LT1
     *
     * @mbg.generated
     */
    private Float lt1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_collect.QQI
     *
     * @mbg.generated
     */
    private Float qqi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_collect.JQI
     *
     * @mbg.generated
     */
    private Float jqi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_collect.FT3Q
     *
     * @mbg.generated
     */
    private Float ft3q;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_collect.FT2Q
     *
     * @mbg.generated
     */
    private Float ft2q;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_collect.FT3Q_PRICE
     *
     * @mbg.generated
     */
    private Float ft3qPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_collect.JQI_PRICE
     *
     * @mbg.generated
     */
    private Float jqiPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_collect.QQI_PRICE
     *
     * @mbg.generated
     */
    private Float qqiPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_collect.BATCH_NUMBER
     *
     * @mbg.generated
     */
    private Integer batchNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_collect.ID
     *
     * @return the value of data_collect.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_collect.ID
     *
     * @param id the value for data_collect.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_collect.COMPANY_ID
     *
     * @return the value of data_collect.COMPANY_ID
     *
     * @mbg.generated
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_collect.COMPANY_ID
     *
     * @param companyId the value for data_collect.COMPANY_ID
     *
     * @mbg.generated
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_collect.STAND_ID
     *
     * @return the value of data_collect.STAND_ID
     *
     * @mbg.generated
     */
    public String getStandId() {
        return standId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_collect.STAND_ID
     *
     * @param standId the value for data_collect.STAND_ID
     *
     * @mbg.generated
     */
    public void setStandId(String standId) {
        this.standId = standId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_collect.STATION_ID
     *
     * @return the value of data_collect.STATION_ID
     *
     * @mbg.generated
     */
    public String getStationId() {
        return stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_collect.STATION_ID
     *
     * @param stationId the value for data_collect.STATION_ID
     *
     * @mbg.generated
     */
    public void setStationId(String stationId) {
        this.stationId = stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_collect.GROUP_ID
     *
     * @return the value of data_collect.GROUP_ID
     *
     * @mbg.generated
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_collect.GROUP_ID
     *
     * @param groupId the value for data_collect.GROUP_ID
     *
     * @mbg.generated
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_collect.OP_TIME
     *
     * @return the value of data_collect.OP_TIME
     *
     * @mbg.generated
     */
    public Date getOpTime() {
        return opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_collect.OP_TIME
     *
     * @param opTime the value for data_collect.OP_TIME
     *
     * @mbg.generated
     */
    public void setOpTime(Date opTime) {
        this.opTime = opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_collect.PT1
     *
     * @return the value of data_collect.PT1
     *
     * @mbg.generated
     */
    public Float getPt1() {
        return pt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_collect.PT1
     *
     * @param pt1 the value for data_collect.PT1
     *
     * @mbg.generated
     */
    public void setPt1(Float pt1) {
        this.pt1 = pt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_collect.PT2
     *
     * @return the value of data_collect.PT2
     *
     * @mbg.generated
     */
    public Float getPt2() {
        return pt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_collect.PT2
     *
     * @param pt2 the value for data_collect.PT2
     *
     * @mbg.generated
     */
    public void setPt2(Float pt2) {
        this.pt2 = pt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_collect.TE1
     *
     * @return the value of data_collect.TE1
     *
     * @mbg.generated
     */
    public Float getTe1() {
        return te1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_collect.TE1
     *
     * @param te1 the value for data_collect.TE1
     *
     * @mbg.generated
     */
    public void setTe1(Float te1) {
        this.te1 = te1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_collect.TE2
     *
     * @return the value of data_collect.TE2
     *
     * @mbg.generated
     */
    public Float getTe2() {
        return te2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_collect.TE2
     *
     * @param te2 the value for data_collect.TE2
     *
     * @mbg.generated
     */
    public void setTe2(Float te2) {
        this.te2 = te2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_collect.CVI1
     *
     * @return the value of data_collect.CVI1
     *
     * @mbg.generated
     */
    public Float getCvi1() {
        return cvi1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_collect.CVI1
     *
     * @param cvi1 the value for data_collect.CVI1
     *
     * @mbg.generated
     */
    public void setCvi1(Float cvi1) {
        this.cvi1 = cvi1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_collect.QI
     *
     * @return the value of data_collect.QI
     *
     * @mbg.generated
     */
    public Float getQi() {
        return qi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_collect.QI
     *
     * @param qi the value for data_collect.QI
     *
     * @mbg.generated
     */
    public void setQi(Float qi) {
        this.qi = qi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_collect.FT1
     *
     * @return the value of data_collect.FT1
     *
     * @mbg.generated
     */
    public Float getFt1() {
        return ft1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_collect.FT1
     *
     * @param ft1 the value for data_collect.FT1
     *
     * @mbg.generated
     */
    public void setFt1(Float ft1) {
        this.ft1 = ft1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_collect.FT1Q
     *
     * @return the value of data_collect.FT1Q
     *
     * @mbg.generated
     */
    public Float getFt1q() {
        return ft1q;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_collect.FT1Q
     *
     * @param ft1q the value for data_collect.FT1Q
     *
     * @mbg.generated
     */
    public void setFt1q(Float ft1q) {
        this.ft1q = ft1q;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_collect.PT3
     *
     * @return the value of data_collect.PT3
     *
     * @mbg.generated
     */
    public Float getPt3() {
        return pt3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_collect.PT3
     *
     * @param pt3 the value for data_collect.PT3
     *
     * @mbg.generated
     */
    public void setPt3(Float pt3) {
        this.pt3 = pt3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_collect.PT4
     *
     * @return the value of data_collect.PT4
     *
     * @mbg.generated
     */
    public Float getPt4() {
        return pt4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_collect.PT4
     *
     * @param pt4 the value for data_collect.PT4
     *
     * @mbg.generated
     */
    public void setPt4(Float pt4) {
        this.pt4 = pt4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_collect.TE3
     *
     * @return the value of data_collect.TE3
     *
     * @mbg.generated
     */
    public Float getTe3() {
        return te3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_collect.TE3
     *
     * @param te3 the value for data_collect.TE3
     *
     * @mbg.generated
     */
    public void setTe3(Float te3) {
        this.te3 = te3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_collect.TE4
     *
     * @return the value of data_collect.TE4
     *
     * @mbg.generated
     */
    public Float getTe4() {
        return te4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_collect.TE4
     *
     * @param te4 the value for data_collect.TE4
     *
     * @mbg.generated
     */
    public void setTe4(Float te4) {
        this.te4 = te4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_collect.FT2
     *
     * @return the value of data_collect.FT2
     *
     * @mbg.generated
     */
    public Float getFt2() {
        return ft2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_collect.FT2
     *
     * @param ft2 the value for data_collect.FT2
     *
     * @mbg.generated
     */
    public void setFt2(Float ft2) {
        this.ft2 = ft2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_collect.FT3
     *
     * @return the value of data_collect.FT3
     *
     * @mbg.generated
     */
    public Float getFt3() {
        return ft3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_collect.FT3
     *
     * @param ft3 the value for data_collect.FT3
     *
     * @mbg.generated
     */
    public void setFt3(Float ft3) {
        this.ft3 = ft3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_collect.FC1V1
     *
     * @return the value of data_collect.FC1V1
     *
     * @mbg.generated
     */
    public Float getFc1v1() {
        return fc1v1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_collect.FC1V1
     *
     * @param fc1v1 the value for data_collect.FC1V1
     *
     * @mbg.generated
     */
    public void setFc1v1(Float fc1v1) {
        this.fc1v1 = fc1v1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_collect.LT1
     *
     * @return the value of data_collect.LT1
     *
     * @mbg.generated
     */
    public Float getLt1() {
        return lt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_collect.LT1
     *
     * @param lt1 the value for data_collect.LT1
     *
     * @mbg.generated
     */
    public void setLt1(Float lt1) {
        this.lt1 = lt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_collect.QQI
     *
     * @return the value of data_collect.QQI
     *
     * @mbg.generated
     */
    public Float getQqi() {
        return qqi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_collect.QQI
     *
     * @param qqi the value for data_collect.QQI
     *
     * @mbg.generated
     */
    public void setQqi(Float qqi) {
        this.qqi = qqi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_collect.JQI
     *
     * @return the value of data_collect.JQI
     *
     * @mbg.generated
     */
    public Float getJqi() {
        return jqi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_collect.JQI
     *
     * @param jqi the value for data_collect.JQI
     *
     * @mbg.generated
     */
    public void setJqi(Float jqi) {
        this.jqi = jqi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_collect.FT3Q
     *
     * @return the value of data_collect.FT3Q
     *
     * @mbg.generated
     */
    public Float getFt3q() {
        return ft3q;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_collect.FT3Q
     *
     * @param ft3q the value for data_collect.FT3Q
     *
     * @mbg.generated
     */
    public void setFt3q(Float ft3q) {
        this.ft3q = ft3q;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_collect.FT2Q
     *
     * @return the value of data_collect.FT2Q
     *
     * @mbg.generated
     */
    public Float getFt2q() {
        return ft2q;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_collect.FT2Q
     *
     * @param ft2q the value for data_collect.FT2Q
     *
     * @mbg.generated
     */
    public void setFt2q(Float ft2q) {
        this.ft2q = ft2q;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_collect.FT3Q_PRICE
     *
     * @return the value of data_collect.FT3Q_PRICE
     *
     * @mbg.generated
     */
    public Float getFt3qPrice() {
        return ft3qPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_collect.FT3Q_PRICE
     *
     * @param ft3qPrice the value for data_collect.FT3Q_PRICE
     *
     * @mbg.generated
     */
    public void setFt3qPrice(Float ft3qPrice) {
        this.ft3qPrice = ft3qPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_collect.JQI_PRICE
     *
     * @return the value of data_collect.JQI_PRICE
     *
     * @mbg.generated
     */
    public Float getJqiPrice() {
        return jqiPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_collect.JQI_PRICE
     *
     * @param jqiPrice the value for data_collect.JQI_PRICE
     *
     * @mbg.generated
     */
    public void setJqiPrice(Float jqiPrice) {
        this.jqiPrice = jqiPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_collect.QQI_PRICE
     *
     * @return the value of data_collect.QQI_PRICE
     *
     * @mbg.generated
     */
    public Float getQqiPrice() {
        return qqiPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_collect.QQI_PRICE
     *
     * @param qqiPrice the value for data_collect.QQI_PRICE
     *
     * @mbg.generated
     */
    public void setQqiPrice(Float qqiPrice) {
        this.qqiPrice = qqiPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_collect.BATCH_NUMBER
     *
     * @return the value of data_collect.BATCH_NUMBER
     *
     * @mbg.generated
     */
    public Integer getBatchNumber() {
        return batchNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_collect.BATCH_NUMBER
     *
     * @param batchNumber the value for data_collect.BATCH_NUMBER
     *
     * @mbg.generated
     */
    public void setBatchNumber(Integer batchNumber) {
        this.batchNumber = batchNumber;
    }


    ////*******自定义开始********/
    //***********自定义结束****////
}
