package com.xhkj.server.energy.dao.mybatis.vo;

public class GroupData extends GroupDataKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_group.GROUP_NAME
     *
     * @mbg.generated
     */
    private String groupName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_group.GROUP_NAME
     *
     * @return the value of data_group.GROUP_NAME
     *
     * @mbg.generated
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_group.GROUP_NAME
     *
     * @param groupName the value for data_group.GROUP_NAME
     *
     * @mbg.generated
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }


    ////*******自定义开始********/
    //***********自定义结束****////
}
