package com.xhkj.server.energy.dao.mybatis.vo;

import lombok.ToString;
import org.apache.commons.lang3.builder.CompareToBuilder;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

@ToString
public class Menu implements Comparable<Menu>{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_menu.MENU_ID
     *
     * @mbg.generated
     */
    private Integer menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_menu.MENU_CODE
     *
     * @mbg.generated
     */
    private String menuCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_menu.MENU_NAME
     *
     * @mbg.generated
     */
    private String menuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_menu.MENU_PID
     *
     * @mbg.generated
     */
    private String menuPid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_menu.MENU_URL
     *
     * @mbg.generated
     */
    private String menuUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_menu.ICON
     *
     * @mbg.generated
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_menu.MENU_ORDER
     *
     * @mbg.generated
     */
    private Integer menuOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_menu.RMK
     *
     * @mbg.generated
     */
    private String rmk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_menu.CRT_ID
     *
     * @mbg.generated
     */
    private String crtId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_menu.CRT_DT
     *
     * @mbg.generated
     */
    private String crtDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_menu.CRT_TM
     *
     * @mbg.generated
     */
    private String crtTm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_menu.UPT_ID
     *
     * @mbg.generated
     */
    private String uptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_menu.UPT_DT
     *
     * @mbg.generated
     */
    private String uptDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_menu.UPT_TM
     *
     * @mbg.generated
     */
    private String uptTm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_menu.TM_SMP
     *
     * @mbg.generated
     */
    private String tmSmp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_menu.MENU_ID
     *
     * @return the value of t_sys_menu.MENU_ID
     *
     * @mbg.generated
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_menu.MENU_ID
     *
     * @param menuId the value for t_sys_menu.MENU_ID
     *
     * @mbg.generated
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_menu.MENU_CODE
     *
     * @return the value of t_sys_menu.MENU_CODE
     *
     * @mbg.generated
     */
    public String getMenuCode() {
        return menuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_menu.MENU_CODE
     *
     * @param menuCode the value for t_sys_menu.MENU_CODE
     *
     * @mbg.generated
     */
    public void setMenuCode(String menuCode) {
        this.menuCode = menuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_menu.MENU_NAME
     *
     * @return the value of t_sys_menu.MENU_NAME
     *
     * @mbg.generated
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_menu.MENU_NAME
     *
     * @param menuName the value for t_sys_menu.MENU_NAME
     *
     * @mbg.generated
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_menu.MENU_PID
     *
     * @return the value of t_sys_menu.MENU_PID
     *
     * @mbg.generated
     */
    public String getMenuPid() {
        return menuPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_menu.MENU_PID
     *
     * @param menuPid the value for t_sys_menu.MENU_PID
     *
     * @mbg.generated
     */
    public void setMenuPid(String menuPid) {
        this.menuPid = menuPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_menu.MENU_URL
     *
     * @return the value of t_sys_menu.MENU_URL
     *
     * @mbg.generated
     */
    public String getMenuUrl() {
        return menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_menu.MENU_URL
     *
     * @param menuUrl the value for t_sys_menu.MENU_URL
     *
     * @mbg.generated
     */
    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_menu.ICON
     *
     * @return the value of t_sys_menu.ICON
     *
     * @mbg.generated
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_menu.ICON
     *
     * @param icon the value for t_sys_menu.ICON
     *
     * @mbg.generated
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_menu.MENU_ORDER
     *
     * @return the value of t_sys_menu.MENU_ORDER
     *
     * @mbg.generated
     */
    public Integer getMenuOrder() {
        return menuOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_menu.MENU_ORDER
     *
     * @param menuOrder the value for t_sys_menu.MENU_ORDER
     *
     * @mbg.generated
     */
    public void setMenuOrder(Integer menuOrder) {
        this.menuOrder = menuOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_menu.RMK
     *
     * @return the value of t_sys_menu.RMK
     *
     * @mbg.generated
     */
    public String getRmk() {
        return rmk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_menu.RMK
     *
     * @param rmk the value for t_sys_menu.RMK
     *
     * @mbg.generated
     */
    public void setRmk(String rmk) {
        this.rmk = rmk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_menu.CRT_ID
     *
     * @return the value of t_sys_menu.CRT_ID
     *
     * @mbg.generated
     */
    public String getCrtId() {
        return crtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_menu.CRT_ID
     *
     * @param crtId the value for t_sys_menu.CRT_ID
     *
     * @mbg.generated
     */
    public void setCrtId(String crtId) {
        this.crtId = crtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_menu.CRT_DT
     *
     * @return the value of t_sys_menu.CRT_DT
     *
     * @mbg.generated
     */
    public String getCrtDt() {
        return crtDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_menu.CRT_DT
     *
     * @param crtDt the value for t_sys_menu.CRT_DT
     *
     * @mbg.generated
     */
    public void setCrtDt(String crtDt) {
        this.crtDt = crtDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_menu.CRT_TM
     *
     * @return the value of t_sys_menu.CRT_TM
     *
     * @mbg.generated
     */
    public String getCrtTm() {
        return crtTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_menu.CRT_TM
     *
     * @param crtTm the value for t_sys_menu.CRT_TM
     *
     * @mbg.generated
     */
    public void setCrtTm(String crtTm) {
        this.crtTm = crtTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_menu.UPT_ID
     *
     * @return the value of t_sys_menu.UPT_ID
     *
     * @mbg.generated
     */
    public String getUptId() {
        return uptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_menu.UPT_ID
     *
     * @param uptId the value for t_sys_menu.UPT_ID
     *
     * @mbg.generated
     */
    public void setUptId(String uptId) {
        this.uptId = uptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_menu.UPT_DT
     *
     * @return the value of t_sys_menu.UPT_DT
     *
     * @mbg.generated
     */
    public String getUptDt() {
        return uptDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_menu.UPT_DT
     *
     * @param uptDt the value for t_sys_menu.UPT_DT
     *
     * @mbg.generated
     */
    public void setUptDt(String uptDt) {
        this.uptDt = uptDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_menu.UPT_TM
     *
     * @return the value of t_sys_menu.UPT_TM
     *
     * @mbg.generated
     */
    public String getUptTm() {
        return uptTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_menu.UPT_TM
     *
     * @param uptTm the value for t_sys_menu.UPT_TM
     *
     * @mbg.generated
     */
    public void setUptTm(String uptTm) {
        this.uptTm = uptTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_menu.TM_SMP
     *
     * @return the value of t_sys_menu.TM_SMP
     *
     * @mbg.generated
     */
    public String getTmSmp() {
        return tmSmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_menu.TM_SMP
     *
     * @param tmSmp the value for t_sys_menu.TM_SMP
     *
     * @mbg.generated
     */
    public void setTmSmp(String tmSmp) {
        this.tmSmp = tmSmp;
    }


    ////*******自定义开始********/

    /** 对应菜单set */
    private Set<String> menuItems = new HashSet<String>(0);
    /** 对应菜单 */
    private List<MenuItem> menuItemList = new ArrayList<MenuItem>(0);

    public Set<String> getMenuItems() {
        return menuItems;
    }

    public void setMenuItems(Set<String> menuItems) {
        this.menuItems = menuItems;
    }

    public List<MenuItem> getMenuItemList() {
        return menuItemList;
    }

    public void setMenuItemList(List<MenuItem> menuItemList) {
        this.menuItemList = menuItemList;
    }

    /* (非 Javadoc)
     * <p>Title: equals</p>
     * <p>Description: </p>
     * @param obj
     * @return
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        Menu other = (Menu) obj;
        if (menuId == null) {
            return other.menuId == null;
        } else return menuId.equals(other.menuId);
    }

    /* (非 Javadoc)
     * <p>Title: hashCode</p>
     * <p>Description: </p>
     * @return
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((menuId == null) ? 0 : menuId.hashCode());
        return result;
    }

    @Override
    public int compareTo(Menu o) {
        return new CompareToBuilder().append(menuId, o.menuId).toComparison();
    }

    //***********自定义结束****////
}
