package com.xhkj.server.energy.dao.mybatis.vo;

import java.util.ArrayList;
import java.util.List;

public class MenuExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_menu
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_menu
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_menu
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu
     *
     * @mbg.generated
     */
    public MenuExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sys_menu
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMenuIdIsNull() {
            addCriterion("MENU_ID is null");
            return (Criteria) this;
        }

        public Criteria andMenuIdIsNotNull() {
            addCriterion("MENU_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMenuIdEqualTo(Integer value) {
            addCriterion("MENU_ID =", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdNotEqualTo(Integer value) {
            addCriterion("MENU_ID <>", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdGreaterThan(Integer value) {
            addCriterion("MENU_ID >", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("MENU_ID >=", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdLessThan(Integer value) {
            addCriterion("MENU_ID <", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdLessThanOrEqualTo(Integer value) {
            addCriterion("MENU_ID <=", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdIn(List<Integer> values) {
            addCriterion("MENU_ID in", values, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdNotIn(List<Integer> values) {
            addCriterion("MENU_ID not in", values, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdBetween(Integer value1, Integer value2) {
            addCriterion("MENU_ID between", value1, value2, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdNotBetween(Integer value1, Integer value2) {
            addCriterion("MENU_ID not between", value1, value2, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuCodeIsNull() {
            addCriterion("MENU_CODE is null");
            return (Criteria) this;
        }

        public Criteria andMenuCodeIsNotNull() {
            addCriterion("MENU_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andMenuCodeEqualTo(String value) {
            addCriterion("MENU_CODE =", value, "menuCode");
            return (Criteria) this;
        }

        public Criteria andMenuCodeNotEqualTo(String value) {
            addCriterion("MENU_CODE <>", value, "menuCode");
            return (Criteria) this;
        }

        public Criteria andMenuCodeGreaterThan(String value) {
            addCriterion("MENU_CODE >", value, "menuCode");
            return (Criteria) this;
        }

        public Criteria andMenuCodeGreaterThanOrEqualTo(String value) {
            addCriterion("MENU_CODE >=", value, "menuCode");
            return (Criteria) this;
        }

        public Criteria andMenuCodeLessThan(String value) {
            addCriterion("MENU_CODE <", value, "menuCode");
            return (Criteria) this;
        }

        public Criteria andMenuCodeLessThanOrEqualTo(String value) {
            addCriterion("MENU_CODE <=", value, "menuCode");
            return (Criteria) this;
        }

        public Criteria andMenuCodeLike(String value) {
            addCriterion("MENU_CODE like", value, "menuCode");
            return (Criteria) this;
        }

        public Criteria andMenuCodeNotLike(String value) {
            addCriterion("MENU_CODE not like", value, "menuCode");
            return (Criteria) this;
        }

        public Criteria andMenuCodeIn(List<String> values) {
            addCriterion("MENU_CODE in", values, "menuCode");
            return (Criteria) this;
        }

        public Criteria andMenuCodeNotIn(List<String> values) {
            addCriterion("MENU_CODE not in", values, "menuCode");
            return (Criteria) this;
        }

        public Criteria andMenuCodeBetween(String value1, String value2) {
            addCriterion("MENU_CODE between", value1, value2, "menuCode");
            return (Criteria) this;
        }

        public Criteria andMenuCodeNotBetween(String value1, String value2) {
            addCriterion("MENU_CODE not between", value1, value2, "menuCode");
            return (Criteria) this;
        }

        public Criteria andMenuNameIsNull() {
            addCriterion("MENU_NAME is null");
            return (Criteria) this;
        }

        public Criteria andMenuNameIsNotNull() {
            addCriterion("MENU_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andMenuNameEqualTo(String value) {
            addCriterion("MENU_NAME =", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameNotEqualTo(String value) {
            addCriterion("MENU_NAME <>", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameGreaterThan(String value) {
            addCriterion("MENU_NAME >", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameGreaterThanOrEqualTo(String value) {
            addCriterion("MENU_NAME >=", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameLessThan(String value) {
            addCriterion("MENU_NAME <", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameLessThanOrEqualTo(String value) {
            addCriterion("MENU_NAME <=", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameLike(String value) {
            addCriterion("MENU_NAME like", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameNotLike(String value) {
            addCriterion("MENU_NAME not like", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameIn(List<String> values) {
            addCriterion("MENU_NAME in", values, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameNotIn(List<String> values) {
            addCriterion("MENU_NAME not in", values, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameBetween(String value1, String value2) {
            addCriterion("MENU_NAME between", value1, value2, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameNotBetween(String value1, String value2) {
            addCriterion("MENU_NAME not between", value1, value2, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuPidIsNull() {
            addCriterion("MENU_PID is null");
            return (Criteria) this;
        }

        public Criteria andMenuPidIsNotNull() {
            addCriterion("MENU_PID is not null");
            return (Criteria) this;
        }

        public Criteria andMenuPidEqualTo(String value) {
            addCriterion("MENU_PID =", value, "menuPid");
            return (Criteria) this;
        }

        public Criteria andMenuPidNotEqualTo(String value) {
            addCriterion("MENU_PID <>", value, "menuPid");
            return (Criteria) this;
        }

        public Criteria andMenuPidGreaterThan(String value) {
            addCriterion("MENU_PID >", value, "menuPid");
            return (Criteria) this;
        }

        public Criteria andMenuPidGreaterThanOrEqualTo(String value) {
            addCriterion("MENU_PID >=", value, "menuPid");
            return (Criteria) this;
        }

        public Criteria andMenuPidLessThan(String value) {
            addCriterion("MENU_PID <", value, "menuPid");
            return (Criteria) this;
        }

        public Criteria andMenuPidLessThanOrEqualTo(String value) {
            addCriterion("MENU_PID <=", value, "menuPid");
            return (Criteria) this;
        }

        public Criteria andMenuPidLike(String value) {
            addCriterion("MENU_PID like", value, "menuPid");
            return (Criteria) this;
        }

        public Criteria andMenuPidNotLike(String value) {
            addCriterion("MENU_PID not like", value, "menuPid");
            return (Criteria) this;
        }

        public Criteria andMenuPidIn(List<String> values) {
            addCriterion("MENU_PID in", values, "menuPid");
            return (Criteria) this;
        }

        public Criteria andMenuPidNotIn(List<String> values) {
            addCriterion("MENU_PID not in", values, "menuPid");
            return (Criteria) this;
        }

        public Criteria andMenuPidBetween(String value1, String value2) {
            addCriterion("MENU_PID between", value1, value2, "menuPid");
            return (Criteria) this;
        }

        public Criteria andMenuPidNotBetween(String value1, String value2) {
            addCriterion("MENU_PID not between", value1, value2, "menuPid");
            return (Criteria) this;
        }

        public Criteria andMenuUrlIsNull() {
            addCriterion("MENU_URL is null");
            return (Criteria) this;
        }

        public Criteria andMenuUrlIsNotNull() {
            addCriterion("MENU_URL is not null");
            return (Criteria) this;
        }

        public Criteria andMenuUrlEqualTo(String value) {
            addCriterion("MENU_URL =", value, "menuUrl");
            return (Criteria) this;
        }

        public Criteria andMenuUrlNotEqualTo(String value) {
            addCriterion("MENU_URL <>", value, "menuUrl");
            return (Criteria) this;
        }

        public Criteria andMenuUrlGreaterThan(String value) {
            addCriterion("MENU_URL >", value, "menuUrl");
            return (Criteria) this;
        }

        public Criteria andMenuUrlGreaterThanOrEqualTo(String value) {
            addCriterion("MENU_URL >=", value, "menuUrl");
            return (Criteria) this;
        }

        public Criteria andMenuUrlLessThan(String value) {
            addCriterion("MENU_URL <", value, "menuUrl");
            return (Criteria) this;
        }

        public Criteria andMenuUrlLessThanOrEqualTo(String value) {
            addCriterion("MENU_URL <=", value, "menuUrl");
            return (Criteria) this;
        }

        public Criteria andMenuUrlLike(String value) {
            addCriterion("MENU_URL like", value, "menuUrl");
            return (Criteria) this;
        }

        public Criteria andMenuUrlNotLike(String value) {
            addCriterion("MENU_URL not like", value, "menuUrl");
            return (Criteria) this;
        }

        public Criteria andMenuUrlIn(List<String> values) {
            addCriterion("MENU_URL in", values, "menuUrl");
            return (Criteria) this;
        }

        public Criteria andMenuUrlNotIn(List<String> values) {
            addCriterion("MENU_URL not in", values, "menuUrl");
            return (Criteria) this;
        }

        public Criteria andMenuUrlBetween(String value1, String value2) {
            addCriterion("MENU_URL between", value1, value2, "menuUrl");
            return (Criteria) this;
        }

        public Criteria andMenuUrlNotBetween(String value1, String value2) {
            addCriterion("MENU_URL not between", value1, value2, "menuUrl");
            return (Criteria) this;
        }

        public Criteria andIconIsNull() {
            addCriterion("ICON is null");
            return (Criteria) this;
        }

        public Criteria andIconIsNotNull() {
            addCriterion("ICON is not null");
            return (Criteria) this;
        }

        public Criteria andIconEqualTo(String value) {
            addCriterion("ICON =", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconNotEqualTo(String value) {
            addCriterion("ICON <>", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconGreaterThan(String value) {
            addCriterion("ICON >", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconGreaterThanOrEqualTo(String value) {
            addCriterion("ICON >=", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconLessThan(String value) {
            addCriterion("ICON <", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconLessThanOrEqualTo(String value) {
            addCriterion("ICON <=", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconLike(String value) {
            addCriterion("ICON like", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconNotLike(String value) {
            addCriterion("ICON not like", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconIn(List<String> values) {
            addCriterion("ICON in", values, "icon");
            return (Criteria) this;
        }

        public Criteria andIconNotIn(List<String> values) {
            addCriterion("ICON not in", values, "icon");
            return (Criteria) this;
        }

        public Criteria andIconBetween(String value1, String value2) {
            addCriterion("ICON between", value1, value2, "icon");
            return (Criteria) this;
        }

        public Criteria andIconNotBetween(String value1, String value2) {
            addCriterion("ICON not between", value1, value2, "icon");
            return (Criteria) this;
        }

        public Criteria andMenuOrderIsNull() {
            addCriterion("MENU_ORDER is null");
            return (Criteria) this;
        }

        public Criteria andMenuOrderIsNotNull() {
            addCriterion("MENU_ORDER is not null");
            return (Criteria) this;
        }

        public Criteria andMenuOrderEqualTo(Integer value) {
            addCriterion("MENU_ORDER =", value, "menuOrder");
            return (Criteria) this;
        }

        public Criteria andMenuOrderNotEqualTo(Integer value) {
            addCriterion("MENU_ORDER <>", value, "menuOrder");
            return (Criteria) this;
        }

        public Criteria andMenuOrderGreaterThan(Integer value) {
            addCriterion("MENU_ORDER >", value, "menuOrder");
            return (Criteria) this;
        }

        public Criteria andMenuOrderGreaterThanOrEqualTo(Integer value) {
            addCriterion("MENU_ORDER >=", value, "menuOrder");
            return (Criteria) this;
        }

        public Criteria andMenuOrderLessThan(Integer value) {
            addCriterion("MENU_ORDER <", value, "menuOrder");
            return (Criteria) this;
        }

        public Criteria andMenuOrderLessThanOrEqualTo(Integer value) {
            addCriterion("MENU_ORDER <=", value, "menuOrder");
            return (Criteria) this;
        }

        public Criteria andMenuOrderIn(List<Integer> values) {
            addCriterion("MENU_ORDER in", values, "menuOrder");
            return (Criteria) this;
        }

        public Criteria andMenuOrderNotIn(List<Integer> values) {
            addCriterion("MENU_ORDER not in", values, "menuOrder");
            return (Criteria) this;
        }

        public Criteria andMenuOrderBetween(Integer value1, Integer value2) {
            addCriterion("MENU_ORDER between", value1, value2, "menuOrder");
            return (Criteria) this;
        }

        public Criteria andMenuOrderNotBetween(Integer value1, Integer value2) {
            addCriterion("MENU_ORDER not between", value1, value2, "menuOrder");
            return (Criteria) this;
        }

        public Criteria andRmkIsNull() {
            addCriterion("RMK is null");
            return (Criteria) this;
        }

        public Criteria andRmkIsNotNull() {
            addCriterion("RMK is not null");
            return (Criteria) this;
        }

        public Criteria andRmkEqualTo(String value) {
            addCriterion("RMK =", value, "rmk");
            return (Criteria) this;
        }

        public Criteria andRmkNotEqualTo(String value) {
            addCriterion("RMK <>", value, "rmk");
            return (Criteria) this;
        }

        public Criteria andRmkGreaterThan(String value) {
            addCriterion("RMK >", value, "rmk");
            return (Criteria) this;
        }

        public Criteria andRmkGreaterThanOrEqualTo(String value) {
            addCriterion("RMK >=", value, "rmk");
            return (Criteria) this;
        }

        public Criteria andRmkLessThan(String value) {
            addCriterion("RMK <", value, "rmk");
            return (Criteria) this;
        }

        public Criteria andRmkLessThanOrEqualTo(String value) {
            addCriterion("RMK <=", value, "rmk");
            return (Criteria) this;
        }

        public Criteria andRmkLike(String value) {
            addCriterion("RMK like", value, "rmk");
            return (Criteria) this;
        }

        public Criteria andRmkNotLike(String value) {
            addCriterion("RMK not like", value, "rmk");
            return (Criteria) this;
        }

        public Criteria andRmkIn(List<String> values) {
            addCriterion("RMK in", values, "rmk");
            return (Criteria) this;
        }

        public Criteria andRmkNotIn(List<String> values) {
            addCriterion("RMK not in", values, "rmk");
            return (Criteria) this;
        }

        public Criteria andRmkBetween(String value1, String value2) {
            addCriterion("RMK between", value1, value2, "rmk");
            return (Criteria) this;
        }

        public Criteria andRmkNotBetween(String value1, String value2) {
            addCriterion("RMK not between", value1, value2, "rmk");
            return (Criteria) this;
        }

        public Criteria andCrtIdIsNull() {
            addCriterion("CRT_ID is null");
            return (Criteria) this;
        }

        public Criteria andCrtIdIsNotNull() {
            addCriterion("CRT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCrtIdEqualTo(String value) {
            addCriterion("CRT_ID =", value, "crtId");
            return (Criteria) this;
        }

        public Criteria andCrtIdNotEqualTo(String value) {
            addCriterion("CRT_ID <>", value, "crtId");
            return (Criteria) this;
        }

        public Criteria andCrtIdGreaterThan(String value) {
            addCriterion("CRT_ID >", value, "crtId");
            return (Criteria) this;
        }

        public Criteria andCrtIdGreaterThanOrEqualTo(String value) {
            addCriterion("CRT_ID >=", value, "crtId");
            return (Criteria) this;
        }

        public Criteria andCrtIdLessThan(String value) {
            addCriterion("CRT_ID <", value, "crtId");
            return (Criteria) this;
        }

        public Criteria andCrtIdLessThanOrEqualTo(String value) {
            addCriterion("CRT_ID <=", value, "crtId");
            return (Criteria) this;
        }

        public Criteria andCrtIdLike(String value) {
            addCriterion("CRT_ID like", value, "crtId");
            return (Criteria) this;
        }

        public Criteria andCrtIdNotLike(String value) {
            addCriterion("CRT_ID not like", value, "crtId");
            return (Criteria) this;
        }

        public Criteria andCrtIdIn(List<String> values) {
            addCriterion("CRT_ID in", values, "crtId");
            return (Criteria) this;
        }

        public Criteria andCrtIdNotIn(List<String> values) {
            addCriterion("CRT_ID not in", values, "crtId");
            return (Criteria) this;
        }

        public Criteria andCrtIdBetween(String value1, String value2) {
            addCriterion("CRT_ID between", value1, value2, "crtId");
            return (Criteria) this;
        }

        public Criteria andCrtIdNotBetween(String value1, String value2) {
            addCriterion("CRT_ID not between", value1, value2, "crtId");
            return (Criteria) this;
        }

        public Criteria andCrtDtIsNull() {
            addCriterion("CRT_DT is null");
            return (Criteria) this;
        }

        public Criteria andCrtDtIsNotNull() {
            addCriterion("CRT_DT is not null");
            return (Criteria) this;
        }

        public Criteria andCrtDtEqualTo(String value) {
            addCriterion("CRT_DT =", value, "crtDt");
            return (Criteria) this;
        }

        public Criteria andCrtDtNotEqualTo(String value) {
            addCriterion("CRT_DT <>", value, "crtDt");
            return (Criteria) this;
        }

        public Criteria andCrtDtGreaterThan(String value) {
            addCriterion("CRT_DT >", value, "crtDt");
            return (Criteria) this;
        }

        public Criteria andCrtDtGreaterThanOrEqualTo(String value) {
            addCriterion("CRT_DT >=", value, "crtDt");
            return (Criteria) this;
        }

        public Criteria andCrtDtLessThan(String value) {
            addCriterion("CRT_DT <", value, "crtDt");
            return (Criteria) this;
        }

        public Criteria andCrtDtLessThanOrEqualTo(String value) {
            addCriterion("CRT_DT <=", value, "crtDt");
            return (Criteria) this;
        }

        public Criteria andCrtDtLike(String value) {
            addCriterion("CRT_DT like", value, "crtDt");
            return (Criteria) this;
        }

        public Criteria andCrtDtNotLike(String value) {
            addCriterion("CRT_DT not like", value, "crtDt");
            return (Criteria) this;
        }

        public Criteria andCrtDtIn(List<String> values) {
            addCriterion("CRT_DT in", values, "crtDt");
            return (Criteria) this;
        }

        public Criteria andCrtDtNotIn(List<String> values) {
            addCriterion("CRT_DT not in", values, "crtDt");
            return (Criteria) this;
        }

        public Criteria andCrtDtBetween(String value1, String value2) {
            addCriterion("CRT_DT between", value1, value2, "crtDt");
            return (Criteria) this;
        }

        public Criteria andCrtDtNotBetween(String value1, String value2) {
            addCriterion("CRT_DT not between", value1, value2, "crtDt");
            return (Criteria) this;
        }

        public Criteria andCrtTmIsNull() {
            addCriterion("CRT_TM is null");
            return (Criteria) this;
        }

        public Criteria andCrtTmIsNotNull() {
            addCriterion("CRT_TM is not null");
            return (Criteria) this;
        }

        public Criteria andCrtTmEqualTo(String value) {
            addCriterion("CRT_TM =", value, "crtTm");
            return (Criteria) this;
        }

        public Criteria andCrtTmNotEqualTo(String value) {
            addCriterion("CRT_TM <>", value, "crtTm");
            return (Criteria) this;
        }

        public Criteria andCrtTmGreaterThan(String value) {
            addCriterion("CRT_TM >", value, "crtTm");
            return (Criteria) this;
        }

        public Criteria andCrtTmGreaterThanOrEqualTo(String value) {
            addCriterion("CRT_TM >=", value, "crtTm");
            return (Criteria) this;
        }

        public Criteria andCrtTmLessThan(String value) {
            addCriterion("CRT_TM <", value, "crtTm");
            return (Criteria) this;
        }

        public Criteria andCrtTmLessThanOrEqualTo(String value) {
            addCriterion("CRT_TM <=", value, "crtTm");
            return (Criteria) this;
        }

        public Criteria andCrtTmLike(String value) {
            addCriterion("CRT_TM like", value, "crtTm");
            return (Criteria) this;
        }

        public Criteria andCrtTmNotLike(String value) {
            addCriterion("CRT_TM not like", value, "crtTm");
            return (Criteria) this;
        }

        public Criteria andCrtTmIn(List<String> values) {
            addCriterion("CRT_TM in", values, "crtTm");
            return (Criteria) this;
        }

        public Criteria andCrtTmNotIn(List<String> values) {
            addCriterion("CRT_TM not in", values, "crtTm");
            return (Criteria) this;
        }

        public Criteria andCrtTmBetween(String value1, String value2) {
            addCriterion("CRT_TM between", value1, value2, "crtTm");
            return (Criteria) this;
        }

        public Criteria andCrtTmNotBetween(String value1, String value2) {
            addCriterion("CRT_TM not between", value1, value2, "crtTm");
            return (Criteria) this;
        }

        public Criteria andUptIdIsNull() {
            addCriterion("UPT_ID is null");
            return (Criteria) this;
        }

        public Criteria andUptIdIsNotNull() {
            addCriterion("UPT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUptIdEqualTo(String value) {
            addCriterion("UPT_ID =", value, "uptId");
            return (Criteria) this;
        }

        public Criteria andUptIdNotEqualTo(String value) {
            addCriterion("UPT_ID <>", value, "uptId");
            return (Criteria) this;
        }

        public Criteria andUptIdGreaterThan(String value) {
            addCriterion("UPT_ID >", value, "uptId");
            return (Criteria) this;
        }

        public Criteria andUptIdGreaterThanOrEqualTo(String value) {
            addCriterion("UPT_ID >=", value, "uptId");
            return (Criteria) this;
        }

        public Criteria andUptIdLessThan(String value) {
            addCriterion("UPT_ID <", value, "uptId");
            return (Criteria) this;
        }

        public Criteria andUptIdLessThanOrEqualTo(String value) {
            addCriterion("UPT_ID <=", value, "uptId");
            return (Criteria) this;
        }

        public Criteria andUptIdLike(String value) {
            addCriterion("UPT_ID like", value, "uptId");
            return (Criteria) this;
        }

        public Criteria andUptIdNotLike(String value) {
            addCriterion("UPT_ID not like", value, "uptId");
            return (Criteria) this;
        }

        public Criteria andUptIdIn(List<String> values) {
            addCriterion("UPT_ID in", values, "uptId");
            return (Criteria) this;
        }

        public Criteria andUptIdNotIn(List<String> values) {
            addCriterion("UPT_ID not in", values, "uptId");
            return (Criteria) this;
        }

        public Criteria andUptIdBetween(String value1, String value2) {
            addCriterion("UPT_ID between", value1, value2, "uptId");
            return (Criteria) this;
        }

        public Criteria andUptIdNotBetween(String value1, String value2) {
            addCriterion("UPT_ID not between", value1, value2, "uptId");
            return (Criteria) this;
        }

        public Criteria andUptDtIsNull() {
            addCriterion("UPT_DT is null");
            return (Criteria) this;
        }

        public Criteria andUptDtIsNotNull() {
            addCriterion("UPT_DT is not null");
            return (Criteria) this;
        }

        public Criteria andUptDtEqualTo(String value) {
            addCriterion("UPT_DT =", value, "uptDt");
            return (Criteria) this;
        }

        public Criteria andUptDtNotEqualTo(String value) {
            addCriterion("UPT_DT <>", value, "uptDt");
            return (Criteria) this;
        }

        public Criteria andUptDtGreaterThan(String value) {
            addCriterion("UPT_DT >", value, "uptDt");
            return (Criteria) this;
        }

        public Criteria andUptDtGreaterThanOrEqualTo(String value) {
            addCriterion("UPT_DT >=", value, "uptDt");
            return (Criteria) this;
        }

        public Criteria andUptDtLessThan(String value) {
            addCriterion("UPT_DT <", value, "uptDt");
            return (Criteria) this;
        }

        public Criteria andUptDtLessThanOrEqualTo(String value) {
            addCriterion("UPT_DT <=", value, "uptDt");
            return (Criteria) this;
        }

        public Criteria andUptDtLike(String value) {
            addCriterion("UPT_DT like", value, "uptDt");
            return (Criteria) this;
        }

        public Criteria andUptDtNotLike(String value) {
            addCriterion("UPT_DT not like", value, "uptDt");
            return (Criteria) this;
        }

        public Criteria andUptDtIn(List<String> values) {
            addCriterion("UPT_DT in", values, "uptDt");
            return (Criteria) this;
        }

        public Criteria andUptDtNotIn(List<String> values) {
            addCriterion("UPT_DT not in", values, "uptDt");
            return (Criteria) this;
        }

        public Criteria andUptDtBetween(String value1, String value2) {
            addCriterion("UPT_DT between", value1, value2, "uptDt");
            return (Criteria) this;
        }

        public Criteria andUptDtNotBetween(String value1, String value2) {
            addCriterion("UPT_DT not between", value1, value2, "uptDt");
            return (Criteria) this;
        }

        public Criteria andUptTmIsNull() {
            addCriterion("UPT_TM is null");
            return (Criteria) this;
        }

        public Criteria andUptTmIsNotNull() {
            addCriterion("UPT_TM is not null");
            return (Criteria) this;
        }

        public Criteria andUptTmEqualTo(String value) {
            addCriterion("UPT_TM =", value, "uptTm");
            return (Criteria) this;
        }

        public Criteria andUptTmNotEqualTo(String value) {
            addCriterion("UPT_TM <>", value, "uptTm");
            return (Criteria) this;
        }

        public Criteria andUptTmGreaterThan(String value) {
            addCriterion("UPT_TM >", value, "uptTm");
            return (Criteria) this;
        }

        public Criteria andUptTmGreaterThanOrEqualTo(String value) {
            addCriterion("UPT_TM >=", value, "uptTm");
            return (Criteria) this;
        }

        public Criteria andUptTmLessThan(String value) {
            addCriterion("UPT_TM <", value, "uptTm");
            return (Criteria) this;
        }

        public Criteria andUptTmLessThanOrEqualTo(String value) {
            addCriterion("UPT_TM <=", value, "uptTm");
            return (Criteria) this;
        }

        public Criteria andUptTmLike(String value) {
            addCriterion("UPT_TM like", value, "uptTm");
            return (Criteria) this;
        }

        public Criteria andUptTmNotLike(String value) {
            addCriterion("UPT_TM not like", value, "uptTm");
            return (Criteria) this;
        }

        public Criteria andUptTmIn(List<String> values) {
            addCriterion("UPT_TM in", values, "uptTm");
            return (Criteria) this;
        }

        public Criteria andUptTmNotIn(List<String> values) {
            addCriterion("UPT_TM not in", values, "uptTm");
            return (Criteria) this;
        }

        public Criteria andUptTmBetween(String value1, String value2) {
            addCriterion("UPT_TM between", value1, value2, "uptTm");
            return (Criteria) this;
        }

        public Criteria andUptTmNotBetween(String value1, String value2) {
            addCriterion("UPT_TM not between", value1, value2, "uptTm");
            return (Criteria) this;
        }

        public Criteria andTmSmpIsNull() {
            addCriterion("TM_SMP is null");
            return (Criteria) this;
        }

        public Criteria andTmSmpIsNotNull() {
            addCriterion("TM_SMP is not null");
            return (Criteria) this;
        }

        public Criteria andTmSmpEqualTo(String value) {
            addCriterion("TM_SMP =", value, "tmSmp");
            return (Criteria) this;
        }

        public Criteria andTmSmpNotEqualTo(String value) {
            addCriterion("TM_SMP <>", value, "tmSmp");
            return (Criteria) this;
        }

        public Criteria andTmSmpGreaterThan(String value) {
            addCriterion("TM_SMP >", value, "tmSmp");
            return (Criteria) this;
        }

        public Criteria andTmSmpGreaterThanOrEqualTo(String value) {
            addCriterion("TM_SMP >=", value, "tmSmp");
            return (Criteria) this;
        }

        public Criteria andTmSmpLessThan(String value) {
            addCriterion("TM_SMP <", value, "tmSmp");
            return (Criteria) this;
        }

        public Criteria andTmSmpLessThanOrEqualTo(String value) {
            addCriterion("TM_SMP <=", value, "tmSmp");
            return (Criteria) this;
        }

        public Criteria andTmSmpLike(String value) {
            addCriterion("TM_SMP like", value, "tmSmp");
            return (Criteria) this;
        }

        public Criteria andTmSmpNotLike(String value) {
            addCriterion("TM_SMP not like", value, "tmSmp");
            return (Criteria) this;
        }

        public Criteria andTmSmpIn(List<String> values) {
            addCriterion("TM_SMP in", values, "tmSmp");
            return (Criteria) this;
        }

        public Criteria andTmSmpNotIn(List<String> values) {
            addCriterion("TM_SMP not in", values, "tmSmp");
            return (Criteria) this;
        }

        public Criteria andTmSmpBetween(String value1, String value2) {
            addCriterion("TM_SMP between", value1, value2, "tmSmp");
            return (Criteria) this;
        }

        public Criteria andTmSmpNotBetween(String value1, String value2) {
            addCriterion("TM_SMP not between", value1, value2, "tmSmp");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sys_menu
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sys_menu
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }


    ////*******自定义开始********/
    //***********自定义结束****////
}
