package com.xhkj.server.energy.dao.mybatis.vo;

public class MenuItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_menu_item.ITEM_ID
     *
     * @mbg.generated
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_menu_item.MENU_ID
     *
     * @mbg.generated
     */
    private Integer menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_menu_item.ITEM_NAME
     *
     * @mbg.generated
     */
    private String itemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_menu_item.permission
     *
     * @mbg.generated
     */
    private String permission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_menu_item.item_sts
     *
     * @mbg.generated
     */
    private String itemSts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_menu_item.rmk
     *
     * @mbg.generated
     */
    private String rmk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_menu_item.CRT_ID
     *
     * @mbg.generated
     */
    private String crtId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_menu_item.CRT_DT
     *
     * @mbg.generated
     */
    private String crtDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_menu_item.CRT_TM
     *
     * @mbg.generated
     */
    private String crtTm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_menu_item.UPT_ID
     *
     * @mbg.generated
     */
    private String uptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_menu_item.UPT_DT
     *
     * @mbg.generated
     */
    private String uptDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_menu_item.UPT_TM
     *
     * @mbg.generated
     */
    private String uptTm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_menu_item.TM_SMP
     *
     * @mbg.generated
     */
    private String tmSmp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_menu_item.ITEM_ID
     *
     * @return the value of t_sys_menu_item.ITEM_ID
     *
     * @mbg.generated
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_menu_item.ITEM_ID
     *
     * @param itemId the value for t_sys_menu_item.ITEM_ID
     *
     * @mbg.generated
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_menu_item.MENU_ID
     *
     * @return the value of t_sys_menu_item.MENU_ID
     *
     * @mbg.generated
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_menu_item.MENU_ID
     *
     * @param menuId the value for t_sys_menu_item.MENU_ID
     *
     * @mbg.generated
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_menu_item.ITEM_NAME
     *
     * @return the value of t_sys_menu_item.ITEM_NAME
     *
     * @mbg.generated
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_menu_item.ITEM_NAME
     *
     * @param itemName the value for t_sys_menu_item.ITEM_NAME
     *
     * @mbg.generated
     */
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_menu_item.permission
     *
     * @return the value of t_sys_menu_item.permission
     *
     * @mbg.generated
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_menu_item.permission
     *
     * @param permission the value for t_sys_menu_item.permission
     *
     * @mbg.generated
     */
    public void setPermission(String permission) {
        this.permission = permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_menu_item.item_sts
     *
     * @return the value of t_sys_menu_item.item_sts
     *
     * @mbg.generated
     */
    public String getItemSts() {
        return itemSts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_menu_item.item_sts
     *
     * @param itemSts the value for t_sys_menu_item.item_sts
     *
     * @mbg.generated
     */
    public void setItemSts(String itemSts) {
        this.itemSts = itemSts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_menu_item.rmk
     *
     * @return the value of t_sys_menu_item.rmk
     *
     * @mbg.generated
     */
    public String getRmk() {
        return rmk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_menu_item.rmk
     *
     * @param rmk the value for t_sys_menu_item.rmk
     *
     * @mbg.generated
     */
    public void setRmk(String rmk) {
        this.rmk = rmk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_menu_item.CRT_ID
     *
     * @return the value of t_sys_menu_item.CRT_ID
     *
     * @mbg.generated
     */
    public String getCrtId() {
        return crtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_menu_item.CRT_ID
     *
     * @param crtId the value for t_sys_menu_item.CRT_ID
     *
     * @mbg.generated
     */
    public void setCrtId(String crtId) {
        this.crtId = crtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_menu_item.CRT_DT
     *
     * @return the value of t_sys_menu_item.CRT_DT
     *
     * @mbg.generated
     */
    public String getCrtDt() {
        return crtDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_menu_item.CRT_DT
     *
     * @param crtDt the value for t_sys_menu_item.CRT_DT
     *
     * @mbg.generated
     */
    public void setCrtDt(String crtDt) {
        this.crtDt = crtDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_menu_item.CRT_TM
     *
     * @return the value of t_sys_menu_item.CRT_TM
     *
     * @mbg.generated
     */
    public String getCrtTm() {
        return crtTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_menu_item.CRT_TM
     *
     * @param crtTm the value for t_sys_menu_item.CRT_TM
     *
     * @mbg.generated
     */
    public void setCrtTm(String crtTm) {
        this.crtTm = crtTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_menu_item.UPT_ID
     *
     * @return the value of t_sys_menu_item.UPT_ID
     *
     * @mbg.generated
     */
    public String getUptId() {
        return uptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_menu_item.UPT_ID
     *
     * @param uptId the value for t_sys_menu_item.UPT_ID
     *
     * @mbg.generated
     */
    public void setUptId(String uptId) {
        this.uptId = uptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_menu_item.UPT_DT
     *
     * @return the value of t_sys_menu_item.UPT_DT
     *
     * @mbg.generated
     */
    public String getUptDt() {
        return uptDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_menu_item.UPT_DT
     *
     * @param uptDt the value for t_sys_menu_item.UPT_DT
     *
     * @mbg.generated
     */
    public void setUptDt(String uptDt) {
        this.uptDt = uptDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_menu_item.UPT_TM
     *
     * @return the value of t_sys_menu_item.UPT_TM
     *
     * @mbg.generated
     */
    public String getUptTm() {
        return uptTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_menu_item.UPT_TM
     *
     * @param uptTm the value for t_sys_menu_item.UPT_TM
     *
     * @mbg.generated
     */
    public void setUptTm(String uptTm) {
        this.uptTm = uptTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_menu_item.TM_SMP
     *
     * @return the value of t_sys_menu_item.TM_SMP
     *
     * @mbg.generated
     */
    public String getTmSmp() {
        return tmSmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_menu_item.TM_SMP
     *
     * @param tmSmp the value for t_sys_menu_item.TM_SMP
     *
     * @mbg.generated
     */
    public void setTmSmp(String tmSmp) {
        this.tmSmp = tmSmp;
    }


    ////*******自定义开始********/
    //***********自定义结束****////
}
