package com.xhkj.server.energy.dao.mybatis.vo;

import com.xhkj.server.energy.entity.BaseEntity;
import com.xhkj.server.energy.shiro.RetryLimitHashedCredentialsMatcher;
import org.apache.shiro.codec.Hex;
import org.apache.shiro.crypto.SecureRandomNumberGenerator;
import org.apache.shiro.crypto.hash.Sha1Hash;
import org.apache.shiro.util.ByteSource;
import org.apache.shiro.util.SimpleByteSource;

import java.util.HashSet;
import java.util.Set;

public class OprInfo extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_opr_info.OPR_ID
     *
     * @mbg.generated
     */
    private Integer oprId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_opr_info.OPR_NAME
     *
     * @mbg.generated
     */
    private String oprName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_opr_info.ORG_ID
     *
     * @mbg.generated
     */
    private Integer orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_opr_info.COMPANY_ID
     *
     * @mbg.generated
     */
    private Integer companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_opr_info.LOGIN_ID
     *
     * @mbg.generated
     */
    private String loginId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_opr_info.LOGIN_PWD
     *
     * @mbg.generated
     */
    private String loginPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_opr_info.EMAIL
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_opr_info.PHONE
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_opr_info.DEP_ID
     *
     * @mbg.generated
     */
    private Integer depId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_opr_info.HEAD
     *
     * @mbg.generated
     */
    private String head;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_opr_info.CRT_ID
     *
     * @mbg.generated
     */
    private String crtId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_opr_info.CRT_DT
     *
     * @mbg.generated
     */
    private String crtDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_opr_info.CRT_TM
     *
     * @mbg.generated
     */
    private String crtTm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_opr_info.UPT_ID
     *
     * @mbg.generated
     */
    private String uptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_opr_info.UPT_DT
     *
     * @mbg.generated
     */
    private String uptDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_opr_info.UPT_TM
     *
     * @mbg.generated
     */
    private String uptTm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_opr_info.OPR_STS
     *
     * @mbg.generated
     */
    private String oprSts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_opr_info.TM_SMP
     *
     * @mbg.generated
     */
    private String tmSmp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_opr_info.PWD_ERR_NUM
     *
     * @mbg.generated
     */
    private String pwdErrNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_opr_info.OPR_ID
     *
     * @return the value of t_sys_opr_info.OPR_ID
     *
     * @mbg.generated
     */
    public Integer getOprId() {
        return oprId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_opr_info.OPR_ID
     *
     * @param oprId the value for t_sys_opr_info.OPR_ID
     *
     * @mbg.generated
     */
    public void setOprId(Integer oprId) {
        this.oprId = oprId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_opr_info.OPR_NAME
     *
     * @return the value of t_sys_opr_info.OPR_NAME
     *
     * @mbg.generated
     */
    public String getOprName() {
        return oprName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_opr_info.OPR_NAME
     *
     * @param oprName the value for t_sys_opr_info.OPR_NAME
     *
     * @mbg.generated
     */
    public void setOprName(String oprName) {
        this.oprName = oprName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_opr_info.ORG_ID
     *
     * @return the value of t_sys_opr_info.ORG_ID
     *
     * @mbg.generated
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_opr_info.ORG_ID
     *
     * @param orgId the value for t_sys_opr_info.ORG_ID
     *
     * @mbg.generated
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_opr_info.COMPANY_ID
     *
     * @return the value of t_sys_opr_info.COMPANY_ID
     *
     * @mbg.generated
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_opr_info.COMPANY_ID
     *
     * @param companyId the value for t_sys_opr_info.COMPANY_ID
     *
     * @mbg.generated
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_opr_info.LOGIN_ID
     *
     * @return the value of t_sys_opr_info.LOGIN_ID
     *
     * @mbg.generated
     */
    public String getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_opr_info.LOGIN_ID
     *
     * @param loginId the value for t_sys_opr_info.LOGIN_ID
     *
     * @mbg.generated
     */
    public void setLoginId(String loginId) {
        this.loginId = loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_opr_info.LOGIN_PWD
     *
     * @return the value of t_sys_opr_info.LOGIN_PWD
     *
     * @mbg.generated
     */
    public String getLoginPwd() {
        return loginPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_opr_info.LOGIN_PWD
     *
     * @param loginPwd the value for t_sys_opr_info.LOGIN_PWD
     *
     * @mbg.generated
     */
    public void setLoginPwd(String loginPwd) {
        this.loginPwd = loginPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_opr_info.EMAIL
     *
     * @return the value of t_sys_opr_info.EMAIL
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_opr_info.EMAIL
     *
     * @param email the value for t_sys_opr_info.EMAIL
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_opr_info.PHONE
     *
     * @return the value of t_sys_opr_info.PHONE
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_opr_info.PHONE
     *
     * @param phone the value for t_sys_opr_info.PHONE
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_opr_info.DEP_ID
     *
     * @return the value of t_sys_opr_info.DEP_ID
     *
     * @mbg.generated
     */
    public Integer getDepId() {
        return depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_opr_info.DEP_ID
     *
     * @param depId the value for t_sys_opr_info.DEP_ID
     *
     * @mbg.generated
     */
    public void setDepId(Integer depId) {
        this.depId = depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_opr_info.HEAD
     *
     * @return the value of t_sys_opr_info.HEAD
     *
     * @mbg.generated
     */
    public String getHead() {
        return head;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_opr_info.HEAD
     *
     * @param head the value for t_sys_opr_info.HEAD
     *
     * @mbg.generated
     */
    public void setHead(String head) {
        this.head = head;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_opr_info.CRT_ID
     *
     * @return the value of t_sys_opr_info.CRT_ID
     *
     * @mbg.generated
     */
    public String getCrtId() {
        return crtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_opr_info.CRT_ID
     *
     * @param crtId the value for t_sys_opr_info.CRT_ID
     *
     * @mbg.generated
     */
    public void setCrtId(String crtId) {
        this.crtId = crtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_opr_info.CRT_DT
     *
     * @return the value of t_sys_opr_info.CRT_DT
     *
     * @mbg.generated
     */
    public String getCrtDt() {
        return crtDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_opr_info.CRT_DT
     *
     * @param crtDt the value for t_sys_opr_info.CRT_DT
     *
     * @mbg.generated
     */
    public void setCrtDt(String crtDt) {
        this.crtDt = crtDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_opr_info.CRT_TM
     *
     * @return the value of t_sys_opr_info.CRT_TM
     *
     * @mbg.generated
     */
    public String getCrtTm() {
        return crtTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_opr_info.CRT_TM
     *
     * @param crtTm the value for t_sys_opr_info.CRT_TM
     *
     * @mbg.generated
     */
    public void setCrtTm(String crtTm) {
        this.crtTm = crtTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_opr_info.UPT_ID
     *
     * @return the value of t_sys_opr_info.UPT_ID
     *
     * @mbg.generated
     */
    public String getUptId() {
        return uptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_opr_info.UPT_ID
     *
     * @param uptId the value for t_sys_opr_info.UPT_ID
     *
     * @mbg.generated
     */
    public void setUptId(String uptId) {
        this.uptId = uptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_opr_info.UPT_DT
     *
     * @return the value of t_sys_opr_info.UPT_DT
     *
     * @mbg.generated
     */
    public String getUptDt() {
        return uptDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_opr_info.UPT_DT
     *
     * @param uptDt the value for t_sys_opr_info.UPT_DT
     *
     * @mbg.generated
     */
    public void setUptDt(String uptDt) {
        this.uptDt = uptDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_opr_info.UPT_TM
     *
     * @return the value of t_sys_opr_info.UPT_TM
     *
     * @mbg.generated
     */
    public String getUptTm() {
        return uptTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_opr_info.UPT_TM
     *
     * @param uptTm the value for t_sys_opr_info.UPT_TM
     *
     * @mbg.generated
     */
    public void setUptTm(String uptTm) {
        this.uptTm = uptTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_opr_info.OPR_STS
     *
     * @return the value of t_sys_opr_info.OPR_STS
     *
     * @mbg.generated
     */
    public String getOprSts() {
        return oprSts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_opr_info.OPR_STS
     *
     * @param oprSts the value for t_sys_opr_info.OPR_STS
     *
     * @mbg.generated
     */
    public void setOprSts(String oprSts) {
        this.oprSts = oprSts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_opr_info.TM_SMP
     *
     * @return the value of t_sys_opr_info.TM_SMP
     *
     * @mbg.generated
     */
    public String getTmSmp() {
        return tmSmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_opr_info.TM_SMP
     *
     * @param tmSmp the value for t_sys_opr_info.TM_SMP
     *
     * @mbg.generated
     */
    public void setTmSmp(String tmSmp) {
        this.tmSmp = tmSmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_opr_info.PWD_ERR_NUM
     *
     * @return the value of t_sys_opr_info.PWD_ERR_NUM
     *
     * @mbg.generated
     */
    public String getPwdErrNum() {
        return pwdErrNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_opr_info.PWD_ERR_NUM
     *
     * @param pwdErrNum the value for t_sys_opr_info.PWD_ERR_NUM
     *
     * @mbg.generated
     */
    public void setPwdErrNum(String pwdErrNum) {
        this.pwdErrNum = pwdErrNum;
    }


    ////*******自定义开始********/

    /**
     * 角色
     */
    private Set<String> roles = new HashSet<String>(0);
    // 最后登录日期
    private String lastDt;
    // 最后登录时间
    private String lastTm;

    public String getLastDt() {
        return lastDt;
    }

    public void setLastDt(String lastDt) {
        this.lastDt = lastDt;
    }

    public String getLastTm() {
        return lastTm;
    }

    public void setLastTm(String lastTm) {
        this.lastTm = lastTm;
    }

    public Set<String> getRoles() {
        return roles;
    }

    public void setRoles(Set<String> roles) {
        this.roles = roles;
    }

    public String encodePwd(String pwd) {
        // 生成盐 随机8位
        ByteSource byteSource = new SecureRandomNumberGenerator().nextBytes(RetryLimitHashedCredentialsMatcher.SALT_SIZE);
        // 添加盐进行加密
        String newPwdCode = new Sha1Hash(pwd, byteSource.getBytes(), RetryLimitHashedCredentialsMatcher.HASH_INTERATIONS).toString();
        return byteSource.toHex() + newPwdCode;
    }

    public boolean checkPwd(String pwd) {
        // 数据库密码拆分
        String salt = loginPwd.substring(0, 16);
        String encodedPwd = loginPwd.substring(16);
        // 获取盐(密码的前16位)
        ByteSource byteSource = new SimpleByteSource(Hex.decode(salt));
        // 添加盐进行加密
        String sha1Pwd = new Sha1Hash(pwd, byteSource.getBytes(), RetryLimitHashedCredentialsMatcher.HASH_INTERATIONS).toString();
        // 进行密码匹配(前16位为盐舍去)
        return encodedPwd.equals(sha1Pwd);
    }

    //***********自定义结束****////
}
