package com.xhkj.server.energy.dao.mybatis.vo;

public class OprRolRel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_opr_rol_rel.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_opr_rol_rel.OPR_ID
     *
     * @mbg.generated
     */
    private Integer oprId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_opr_rol_rel.REL_TYPE
     *
     * @mbg.generated
     */
    private String relType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_opr_rol_rel.ROLE_ID
     *
     * @mbg.generated
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_opr_rol_rel.ID
     *
     * @return the value of t_sys_opr_rol_rel.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_opr_rol_rel.ID
     *
     * @param id the value for t_sys_opr_rol_rel.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_opr_rol_rel.OPR_ID
     *
     * @return the value of t_sys_opr_rol_rel.OPR_ID
     *
     * @mbg.generated
     */
    public Integer getOprId() {
        return oprId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_opr_rol_rel.OPR_ID
     *
     * @param oprId the value for t_sys_opr_rol_rel.OPR_ID
     *
     * @mbg.generated
     */
    public void setOprId(Integer oprId) {
        this.oprId = oprId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_opr_rol_rel.REL_TYPE
     *
     * @return the value of t_sys_opr_rol_rel.REL_TYPE
     *
     * @mbg.generated
     */
    public String getRelType() {
        return relType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_opr_rol_rel.REL_TYPE
     *
     * @param relType the value for t_sys_opr_rol_rel.REL_TYPE
     *
     * @mbg.generated
     */
    public void setRelType(String relType) {
        this.relType = relType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_opr_rol_rel.ROLE_ID
     *
     * @return the value of t_sys_opr_rol_rel.ROLE_ID
     *
     * @mbg.generated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_opr_rol_rel.ROLE_ID
     *
     * @param roleId the value for t_sys_opr_rol_rel.ROLE_ID
     *
     * @mbg.generated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }


    ////*******自定义开始********/
    //***********自定义结束****////
}
