package com.xhkj.server.energy.dao.mybatis.vo;

public class PredictData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_para.city_name
     *
     * @mbg.generated
     */
    private String cityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_para.Tw1
     *
     * @mbg.generated
     */
    private Float tw1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_para.Tpj1
     *
     * @mbg.generated
     */
    private Float tpj1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_para.N
     *
     * @mbg.generated
     */
    private Integer n;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_para.F
     *
     * @mbg.generated
     */
    private Float f;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_para.q
     *
     * @mbg.generated
     */
    private Float q;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_para.Tn
     *
     * @mbg.generated
     */
    private Float tn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_para.Q1
     *
     * @mbg.generated
     */
    private Float q1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_para.L
     *
     * @mbg.generated
     */
    private Float l;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_para.city_name
     *
     * @return the value of data_para.city_name
     *
     * @mbg.generated
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_para.city_name
     *
     * @param cityName the value for data_para.city_name
     *
     * @mbg.generated
     */
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_para.Tw1
     *
     * @return the value of data_para.Tw1
     *
     * @mbg.generated
     */
    public Float getTw1() {
        return tw1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_para.Tw1
     *
     * @param tw1 the value for data_para.Tw1
     *
     * @mbg.generated
     */
    public void setTw1(Float tw1) {
        this.tw1 = tw1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_para.Tpj1
     *
     * @return the value of data_para.Tpj1
     *
     * @mbg.generated
     */
    public Float getTpj1() {
        return tpj1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_para.Tpj1
     *
     * @param tpj1 the value for data_para.Tpj1
     *
     * @mbg.generated
     */
    public void setTpj1(Float tpj1) {
        this.tpj1 = tpj1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_para.N
     *
     * @return the value of data_para.N
     *
     * @mbg.generated
     */
    public Integer getN() {
        return n;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_para.N
     *
     * @param n the value for data_para.N
     *
     * @mbg.generated
     */
    public void setN(Integer n) {
        this.n = n;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_para.F
     *
     * @return the value of data_para.F
     *
     * @mbg.generated
     */
    public Float getF() {
        return f;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_para.F
     *
     * @param f the value for data_para.F
     *
     * @mbg.generated
     */
    public void setF(Float f) {
        this.f = f;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_para.q
     *
     * @return the value of data_para.q
     *
     * @mbg.generated
     */
    public Float getQ() {
        return q;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_para.q
     *
     * @param q the value for data_para.q
     *
     * @mbg.generated
     */
    public void setQ(Float q) {
        this.q = q;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_para.Tn
     *
     * @return the value of data_para.Tn
     *
     * @mbg.generated
     */
    public Float getTn() {
        return tn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_para.Tn
     *
     * @param tn the value for data_para.Tn
     *
     * @mbg.generated
     */
    public void setTn(Float tn) {
        this.tn = tn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_para.Q1
     *
     * @return the value of data_para.Q1
     *
     * @mbg.generated
     */
    public Float getQ1() {
        return q1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_para.Q1
     *
     * @param q1 the value for data_para.Q1
     *
     * @mbg.generated
     */
    public void setQ1(Float q1) {
        this.q1 = q1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_para.L
     *
     * @return the value of data_para.L
     *
     * @mbg.generated
     */
    public Float getL() {
        return l;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_para.L
     *
     * @param l the value for data_para.L
     *
     * @mbg.generated
     */
    public void setL(Float l) {
        this.l = l;
    }


    ////*******自定义开始********/

    @Override
    public String toString() {
        return "PredictData{" +
                "cityName='" + cityName + '\'' +
                ", tw1=" + tw1 +
                ", tpj1=" + tpj1 +
                ", n=" + n +
                ", f=" + f +
                ", q=" + q +
                ", tn=" + tn +
                ", q1=" + q1 +
                ", l=" + l +
                '}';
    }


    //***********自定义结束****////
}
