package com.xhkj.server.energy.dao.mybatis.vo;

import java.util.Date;

public class PredictHistoryData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_para_cul.OP_TIME
     *
     * @mbg.generated
     */
    private Date opTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_para_cul.k
     *
     * @mbg.generated
     */
    private Float k;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_para_cul.k1
     *
     * @mbg.generated
     */
    private Float k1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_para_cul.k2
     *
     * @mbg.generated
     */
    private Float k2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_para_cul.Q2
     *
     * @mbg.generated
     */
    private Float q2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_para_cul.Q3
     *
     * @mbg.generated
     */
    private Float q3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_para_cul.Q4
     *
     * @mbg.generated
     */
    private Float q4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_para_cul.Q5
     *
     * @mbg.generated
     */
    private Float q5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_para_cul.Q6
     *
     * @mbg.generated
     */
    private Float q6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_para_cul.Tpj2
     *
     * @mbg.generated
     */
    private Float tpj2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_para_cul.Tpj3
     *
     * @mbg.generated
     */
    private Float tpj3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_para_cul.Tpj4
     *
     * @mbg.generated
     */
    private Float tpj4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_para_cul.Tpj5
     *
     * @mbg.generated
     */
    private Float tpj5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_para_cul.OP_TIME
     *
     * @return the value of data_para_cul.OP_TIME
     *
     * @mbg.generated
     */
    public Date getOpTime() {
        return opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_para_cul.OP_TIME
     *
     * @param opTime the value for data_para_cul.OP_TIME
     *
     * @mbg.generated
     */
    public void setOpTime(Date opTime) {
        this.opTime = opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_para_cul.k
     *
     * @return the value of data_para_cul.k
     *
     * @mbg.generated
     */
    public Float getK() {
        return k;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_para_cul.k
     *
     * @param k the value for data_para_cul.k
     *
     * @mbg.generated
     */
    public void setK(Float k) {
        this.k = k;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_para_cul.k1
     *
     * @return the value of data_para_cul.k1
     *
     * @mbg.generated
     */
    public Float getK1() {
        return k1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_para_cul.k1
     *
     * @param k1 the value for data_para_cul.k1
     *
     * @mbg.generated
     */
    public void setK1(Float k1) {
        this.k1 = k1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_para_cul.k2
     *
     * @return the value of data_para_cul.k2
     *
     * @mbg.generated
     */
    public Float getK2() {
        return k2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_para_cul.k2
     *
     * @param k2 the value for data_para_cul.k2
     *
     * @mbg.generated
     */
    public void setK2(Float k2) {
        this.k2 = k2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_para_cul.Q2
     *
     * @return the value of data_para_cul.Q2
     *
     * @mbg.generated
     */
    public Float getQ2() {
        return q2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_para_cul.Q2
     *
     * @param q2 the value for data_para_cul.Q2
     *
     * @mbg.generated
     */
    public void setQ2(Float q2) {
        this.q2 = q2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_para_cul.Q3
     *
     * @return the value of data_para_cul.Q3
     *
     * @mbg.generated
     */
    public Float getQ3() {
        return q3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_para_cul.Q3
     *
     * @param q3 the value for data_para_cul.Q3
     *
     * @mbg.generated
     */
    public void setQ3(Float q3) {
        this.q3 = q3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_para_cul.Q4
     *
     * @return the value of data_para_cul.Q4
     *
     * @mbg.generated
     */
    public Float getQ4() {
        return q4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_para_cul.Q4
     *
     * @param q4 the value for data_para_cul.Q4
     *
     * @mbg.generated
     */
    public void setQ4(Float q4) {
        this.q4 = q4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_para_cul.Q5
     *
     * @return the value of data_para_cul.Q5
     *
     * @mbg.generated
     */
    public Float getQ5() {
        return q5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_para_cul.Q5
     *
     * @param q5 the value for data_para_cul.Q5
     *
     * @mbg.generated
     */
    public void setQ5(Float q5) {
        this.q5 = q5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_para_cul.Q6
     *
     * @return the value of data_para_cul.Q6
     *
     * @mbg.generated
     */
    public Float getQ6() {
        return q6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_para_cul.Q6
     *
     * @param q6 the value for data_para_cul.Q6
     *
     * @mbg.generated
     */
    public void setQ6(Float q6) {
        this.q6 = q6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_para_cul.Tpj2
     *
     * @return the value of data_para_cul.Tpj2
     *
     * @mbg.generated
     */
    public Float getTpj2() {
        return tpj2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_para_cul.Tpj2
     *
     * @param tpj2 the value for data_para_cul.Tpj2
     *
     * @mbg.generated
     */
    public void setTpj2(Float tpj2) {
        this.tpj2 = tpj2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_para_cul.Tpj3
     *
     * @return the value of data_para_cul.Tpj3
     *
     * @mbg.generated
     */
    public Float getTpj3() {
        return tpj3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_para_cul.Tpj3
     *
     * @param tpj3 the value for data_para_cul.Tpj3
     *
     * @mbg.generated
     */
    public void setTpj3(Float tpj3) {
        this.tpj3 = tpj3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_para_cul.Tpj4
     *
     * @return the value of data_para_cul.Tpj4
     *
     * @mbg.generated
     */
    public Float getTpj4() {
        return tpj4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_para_cul.Tpj4
     *
     * @param tpj4 the value for data_para_cul.Tpj4
     *
     * @mbg.generated
     */
    public void setTpj4(Float tpj4) {
        this.tpj4 = tpj4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_para_cul.Tpj5
     *
     * @return the value of data_para_cul.Tpj5
     *
     * @mbg.generated
     */
    public Float getTpj5() {
        return tpj5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_para_cul.Tpj5
     *
     * @param tpj5 the value for data_para_cul.Tpj5
     *
     * @mbg.generated
     */
    public void setTpj5(Float tpj5) {
        this.tpj5 = tpj5;
    }


    ////*******自定义开始********/

    public PredictHistoryData(Date opTime, Float k, Float k1, Float k2, Float q2, Float q3, Float q4, Float q5, Float q6, Float tpj2, Float tpj3, Float tpj4, Float tpj5) {
        this.opTime = opTime;
        this.k = k;
        this.k1 = k1;
        this.k2 = k2;
        this.q2 = q2;
        this.q3 = q3;
        this.q4 = q4;
        this.q5 = q5;
        this.q6 = q6;
        this.tpj2 = tpj2;
        this.tpj3 = tpj3;
        this.tpj4 = tpj4;
        this.tpj5 = tpj5;
    }


    //***********自定义结束****////
}
