package com.xhkj.server.energy.dao.mybatis.vo;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class PredictHistoryDataExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table data_para_cul
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table data_para_cul
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table data_para_cul
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_para_cul
     *
     * @mbg.generated
     */
    public PredictHistoryDataExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_para_cul
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_para_cul
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_para_cul
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_para_cul
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_para_cul
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_para_cul
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_para_cul
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_para_cul
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_para_cul
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_para_cul
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table data_para_cul
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andOpTimeIsNull() {
            addCriterion("OP_TIME is null");
            return (Criteria) this;
        }

        public Criteria andOpTimeIsNotNull() {
            addCriterion("OP_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andOpTimeEqualTo(Date value) {
            addCriterionForJDBCDate("OP_TIME =", value, "opTime");
            return (Criteria) this;
        }

        public Criteria andOpTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("OP_TIME <>", value, "opTime");
            return (Criteria) this;
        }

        public Criteria andOpTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("OP_TIME >", value, "opTime");
            return (Criteria) this;
        }

        public Criteria andOpTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("OP_TIME >=", value, "opTime");
            return (Criteria) this;
        }

        public Criteria andOpTimeLessThan(Date value) {
            addCriterionForJDBCDate("OP_TIME <", value, "opTime");
            return (Criteria) this;
        }

        public Criteria andOpTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("OP_TIME <=", value, "opTime");
            return (Criteria) this;
        }

        public Criteria andOpTimeIn(List<Date> values) {
            addCriterionForJDBCDate("OP_TIME in", values, "opTime");
            return (Criteria) this;
        }

        public Criteria andOpTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("OP_TIME not in", values, "opTime");
            return (Criteria) this;
        }

        public Criteria andOpTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("OP_TIME between", value1, value2, "opTime");
            return (Criteria) this;
        }

        public Criteria andOpTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("OP_TIME not between", value1, value2, "opTime");
            return (Criteria) this;
        }

        public Criteria andKIsNull() {
            addCriterion("k is null");
            return (Criteria) this;
        }

        public Criteria andKIsNotNull() {
            addCriterion("k is not null");
            return (Criteria) this;
        }

        public Criteria andKEqualTo(Float value) {
            addCriterion("k =", value, "k");
            return (Criteria) this;
        }

        public Criteria andKNotEqualTo(Float value) {
            addCriterion("k <>", value, "k");
            return (Criteria) this;
        }

        public Criteria andKGreaterThan(Float value) {
            addCriterion("k >", value, "k");
            return (Criteria) this;
        }

        public Criteria andKGreaterThanOrEqualTo(Float value) {
            addCriterion("k >=", value, "k");
            return (Criteria) this;
        }

        public Criteria andKLessThan(Float value) {
            addCriterion("k <", value, "k");
            return (Criteria) this;
        }

        public Criteria andKLessThanOrEqualTo(Float value) {
            addCriterion("k <=", value, "k");
            return (Criteria) this;
        }

        public Criteria andKIn(List<Float> values) {
            addCriterion("k in", values, "k");
            return (Criteria) this;
        }

        public Criteria andKNotIn(List<Float> values) {
            addCriterion("k not in", values, "k");
            return (Criteria) this;
        }

        public Criteria andKBetween(Float value1, Float value2) {
            addCriterion("k between", value1, value2, "k");
            return (Criteria) this;
        }

        public Criteria andKNotBetween(Float value1, Float value2) {
            addCriterion("k not between", value1, value2, "k");
            return (Criteria) this;
        }

        public Criteria andK1IsNull() {
            addCriterion("k1 is null");
            return (Criteria) this;
        }

        public Criteria andK1IsNotNull() {
            addCriterion("k1 is not null");
            return (Criteria) this;
        }

        public Criteria andK1EqualTo(Float value) {
            addCriterion("k1 =", value, "k1");
            return (Criteria) this;
        }

        public Criteria andK1NotEqualTo(Float value) {
            addCriterion("k1 <>", value, "k1");
            return (Criteria) this;
        }

        public Criteria andK1GreaterThan(Float value) {
            addCriterion("k1 >", value, "k1");
            return (Criteria) this;
        }

        public Criteria andK1GreaterThanOrEqualTo(Float value) {
            addCriterion("k1 >=", value, "k1");
            return (Criteria) this;
        }

        public Criteria andK1LessThan(Float value) {
            addCriterion("k1 <", value, "k1");
            return (Criteria) this;
        }

        public Criteria andK1LessThanOrEqualTo(Float value) {
            addCriterion("k1 <=", value, "k1");
            return (Criteria) this;
        }

        public Criteria andK1In(List<Float> values) {
            addCriterion("k1 in", values, "k1");
            return (Criteria) this;
        }

        public Criteria andK1NotIn(List<Float> values) {
            addCriterion("k1 not in", values, "k1");
            return (Criteria) this;
        }

        public Criteria andK1Between(Float value1, Float value2) {
            addCriterion("k1 between", value1, value2, "k1");
            return (Criteria) this;
        }

        public Criteria andK1NotBetween(Float value1, Float value2) {
            addCriterion("k1 not between", value1, value2, "k1");
            return (Criteria) this;
        }

        public Criteria andK2IsNull() {
            addCriterion("k2 is null");
            return (Criteria) this;
        }

        public Criteria andK2IsNotNull() {
            addCriterion("k2 is not null");
            return (Criteria) this;
        }

        public Criteria andK2EqualTo(Float value) {
            addCriterion("k2 =", value, "k2");
            return (Criteria) this;
        }

        public Criteria andK2NotEqualTo(Float value) {
            addCriterion("k2 <>", value, "k2");
            return (Criteria) this;
        }

        public Criteria andK2GreaterThan(Float value) {
            addCriterion("k2 >", value, "k2");
            return (Criteria) this;
        }

        public Criteria andK2GreaterThanOrEqualTo(Float value) {
            addCriterion("k2 >=", value, "k2");
            return (Criteria) this;
        }

        public Criteria andK2LessThan(Float value) {
            addCriterion("k2 <", value, "k2");
            return (Criteria) this;
        }

        public Criteria andK2LessThanOrEqualTo(Float value) {
            addCriterion("k2 <=", value, "k2");
            return (Criteria) this;
        }

        public Criteria andK2In(List<Float> values) {
            addCriterion("k2 in", values, "k2");
            return (Criteria) this;
        }

        public Criteria andK2NotIn(List<Float> values) {
            addCriterion("k2 not in", values, "k2");
            return (Criteria) this;
        }

        public Criteria andK2Between(Float value1, Float value2) {
            addCriterion("k2 between", value1, value2, "k2");
            return (Criteria) this;
        }

        public Criteria andK2NotBetween(Float value1, Float value2) {
            addCriterion("k2 not between", value1, value2, "k2");
            return (Criteria) this;
        }

        public Criteria andQ2IsNull() {
            addCriterion("Q2 is null");
            return (Criteria) this;
        }

        public Criteria andQ2IsNotNull() {
            addCriterion("Q2 is not null");
            return (Criteria) this;
        }

        public Criteria andQ2EqualTo(Float value) {
            addCriterion("Q2 =", value, "q2");
            return (Criteria) this;
        }

        public Criteria andQ2NotEqualTo(Float value) {
            addCriterion("Q2 <>", value, "q2");
            return (Criteria) this;
        }

        public Criteria andQ2GreaterThan(Float value) {
            addCriterion("Q2 >", value, "q2");
            return (Criteria) this;
        }

        public Criteria andQ2GreaterThanOrEqualTo(Float value) {
            addCriterion("Q2 >=", value, "q2");
            return (Criteria) this;
        }

        public Criteria andQ2LessThan(Float value) {
            addCriterion("Q2 <", value, "q2");
            return (Criteria) this;
        }

        public Criteria andQ2LessThanOrEqualTo(Float value) {
            addCriterion("Q2 <=", value, "q2");
            return (Criteria) this;
        }

        public Criteria andQ2In(List<Float> values) {
            addCriterion("Q2 in", values, "q2");
            return (Criteria) this;
        }

        public Criteria andQ2NotIn(List<Float> values) {
            addCriterion("Q2 not in", values, "q2");
            return (Criteria) this;
        }

        public Criteria andQ2Between(Float value1, Float value2) {
            addCriterion("Q2 between", value1, value2, "q2");
            return (Criteria) this;
        }

        public Criteria andQ2NotBetween(Float value1, Float value2) {
            addCriterion("Q2 not between", value1, value2, "q2");
            return (Criteria) this;
        }

        public Criteria andQ3IsNull() {
            addCriterion("Q3 is null");
            return (Criteria) this;
        }

        public Criteria andQ3IsNotNull() {
            addCriterion("Q3 is not null");
            return (Criteria) this;
        }

        public Criteria andQ3EqualTo(Float value) {
            addCriterion("Q3 =", value, "q3");
            return (Criteria) this;
        }

        public Criteria andQ3NotEqualTo(Float value) {
            addCriterion("Q3 <>", value, "q3");
            return (Criteria) this;
        }

        public Criteria andQ3GreaterThan(Float value) {
            addCriterion("Q3 >", value, "q3");
            return (Criteria) this;
        }

        public Criteria andQ3GreaterThanOrEqualTo(Float value) {
            addCriterion("Q3 >=", value, "q3");
            return (Criteria) this;
        }

        public Criteria andQ3LessThan(Float value) {
            addCriterion("Q3 <", value, "q3");
            return (Criteria) this;
        }

        public Criteria andQ3LessThanOrEqualTo(Float value) {
            addCriterion("Q3 <=", value, "q3");
            return (Criteria) this;
        }

        public Criteria andQ3In(List<Float> values) {
            addCriterion("Q3 in", values, "q3");
            return (Criteria) this;
        }

        public Criteria andQ3NotIn(List<Float> values) {
            addCriterion("Q3 not in", values, "q3");
            return (Criteria) this;
        }

        public Criteria andQ3Between(Float value1, Float value2) {
            addCriterion("Q3 between", value1, value2, "q3");
            return (Criteria) this;
        }

        public Criteria andQ3NotBetween(Float value1, Float value2) {
            addCriterion("Q3 not between", value1, value2, "q3");
            return (Criteria) this;
        }

        public Criteria andQ4IsNull() {
            addCriterion("Q4 is null");
            return (Criteria) this;
        }

        public Criteria andQ4IsNotNull() {
            addCriterion("Q4 is not null");
            return (Criteria) this;
        }

        public Criteria andQ4EqualTo(Float value) {
            addCriterion("Q4 =", value, "q4");
            return (Criteria) this;
        }

        public Criteria andQ4NotEqualTo(Float value) {
            addCriterion("Q4 <>", value, "q4");
            return (Criteria) this;
        }

        public Criteria andQ4GreaterThan(Float value) {
            addCriterion("Q4 >", value, "q4");
            return (Criteria) this;
        }

        public Criteria andQ4GreaterThanOrEqualTo(Float value) {
            addCriterion("Q4 >=", value, "q4");
            return (Criteria) this;
        }

        public Criteria andQ4LessThan(Float value) {
            addCriterion("Q4 <", value, "q4");
            return (Criteria) this;
        }

        public Criteria andQ4LessThanOrEqualTo(Float value) {
            addCriterion("Q4 <=", value, "q4");
            return (Criteria) this;
        }

        public Criteria andQ4In(List<Float> values) {
            addCriterion("Q4 in", values, "q4");
            return (Criteria) this;
        }

        public Criteria andQ4NotIn(List<Float> values) {
            addCriterion("Q4 not in", values, "q4");
            return (Criteria) this;
        }

        public Criteria andQ4Between(Float value1, Float value2) {
            addCriterion("Q4 between", value1, value2, "q4");
            return (Criteria) this;
        }

        public Criteria andQ4NotBetween(Float value1, Float value2) {
            addCriterion("Q4 not between", value1, value2, "q4");
            return (Criteria) this;
        }

        public Criteria andQ5IsNull() {
            addCriterion("Q5 is null");
            return (Criteria) this;
        }

        public Criteria andQ5IsNotNull() {
            addCriterion("Q5 is not null");
            return (Criteria) this;
        }

        public Criteria andQ5EqualTo(Float value) {
            addCriterion("Q5 =", value, "q5");
            return (Criteria) this;
        }

        public Criteria andQ5NotEqualTo(Float value) {
            addCriterion("Q5 <>", value, "q5");
            return (Criteria) this;
        }

        public Criteria andQ5GreaterThan(Float value) {
            addCriterion("Q5 >", value, "q5");
            return (Criteria) this;
        }

        public Criteria andQ5GreaterThanOrEqualTo(Float value) {
            addCriterion("Q5 >=", value, "q5");
            return (Criteria) this;
        }

        public Criteria andQ5LessThan(Float value) {
            addCriterion("Q5 <", value, "q5");
            return (Criteria) this;
        }

        public Criteria andQ5LessThanOrEqualTo(Float value) {
            addCriterion("Q5 <=", value, "q5");
            return (Criteria) this;
        }

        public Criteria andQ5In(List<Float> values) {
            addCriterion("Q5 in", values, "q5");
            return (Criteria) this;
        }

        public Criteria andQ5NotIn(List<Float> values) {
            addCriterion("Q5 not in", values, "q5");
            return (Criteria) this;
        }

        public Criteria andQ5Between(Float value1, Float value2) {
            addCriterion("Q5 between", value1, value2, "q5");
            return (Criteria) this;
        }

        public Criteria andQ5NotBetween(Float value1, Float value2) {
            addCriterion("Q5 not between", value1, value2, "q5");
            return (Criteria) this;
        }

        public Criteria andQ6IsNull() {
            addCriterion("Q6 is null");
            return (Criteria) this;
        }

        public Criteria andQ6IsNotNull() {
            addCriterion("Q6 is not null");
            return (Criteria) this;
        }

        public Criteria andQ6EqualTo(Float value) {
            addCriterion("Q6 =", value, "q6");
            return (Criteria) this;
        }

        public Criteria andQ6NotEqualTo(Float value) {
            addCriterion("Q6 <>", value, "q6");
            return (Criteria) this;
        }

        public Criteria andQ6GreaterThan(Float value) {
            addCriterion("Q6 >", value, "q6");
            return (Criteria) this;
        }

        public Criteria andQ6GreaterThanOrEqualTo(Float value) {
            addCriterion("Q6 >=", value, "q6");
            return (Criteria) this;
        }

        public Criteria andQ6LessThan(Float value) {
            addCriterion("Q6 <", value, "q6");
            return (Criteria) this;
        }

        public Criteria andQ6LessThanOrEqualTo(Float value) {
            addCriterion("Q6 <=", value, "q6");
            return (Criteria) this;
        }

        public Criteria andQ6In(List<Float> values) {
            addCriterion("Q6 in", values, "q6");
            return (Criteria) this;
        }

        public Criteria andQ6NotIn(List<Float> values) {
            addCriterion("Q6 not in", values, "q6");
            return (Criteria) this;
        }

        public Criteria andQ6Between(Float value1, Float value2) {
            addCriterion("Q6 between", value1, value2, "q6");
            return (Criteria) this;
        }

        public Criteria andQ6NotBetween(Float value1, Float value2) {
            addCriterion("Q6 not between", value1, value2, "q6");
            return (Criteria) this;
        }

        public Criteria andTpj2IsNull() {
            addCriterion("Tpj2 is null");
            return (Criteria) this;
        }

        public Criteria andTpj2IsNotNull() {
            addCriterion("Tpj2 is not null");
            return (Criteria) this;
        }

        public Criteria andTpj2EqualTo(Float value) {
            addCriterion("Tpj2 =", value, "tpj2");
            return (Criteria) this;
        }

        public Criteria andTpj2NotEqualTo(Float value) {
            addCriterion("Tpj2 <>", value, "tpj2");
            return (Criteria) this;
        }

        public Criteria andTpj2GreaterThan(Float value) {
            addCriterion("Tpj2 >", value, "tpj2");
            return (Criteria) this;
        }

        public Criteria andTpj2GreaterThanOrEqualTo(Float value) {
            addCriterion("Tpj2 >=", value, "tpj2");
            return (Criteria) this;
        }

        public Criteria andTpj2LessThan(Float value) {
            addCriterion("Tpj2 <", value, "tpj2");
            return (Criteria) this;
        }

        public Criteria andTpj2LessThanOrEqualTo(Float value) {
            addCriterion("Tpj2 <=", value, "tpj2");
            return (Criteria) this;
        }

        public Criteria andTpj2In(List<Float> values) {
            addCriterion("Tpj2 in", values, "tpj2");
            return (Criteria) this;
        }

        public Criteria andTpj2NotIn(List<Float> values) {
            addCriterion("Tpj2 not in", values, "tpj2");
            return (Criteria) this;
        }

        public Criteria andTpj2Between(Float value1, Float value2) {
            addCriterion("Tpj2 between", value1, value2, "tpj2");
            return (Criteria) this;
        }

        public Criteria andTpj2NotBetween(Float value1, Float value2) {
            addCriterion("Tpj2 not between", value1, value2, "tpj2");
            return (Criteria) this;
        }

        public Criteria andTpj3IsNull() {
            addCriterion("Tpj3 is null");
            return (Criteria) this;
        }

        public Criteria andTpj3IsNotNull() {
            addCriterion("Tpj3 is not null");
            return (Criteria) this;
        }

        public Criteria andTpj3EqualTo(Float value) {
            addCriterion("Tpj3 =", value, "tpj3");
            return (Criteria) this;
        }

        public Criteria andTpj3NotEqualTo(Float value) {
            addCriterion("Tpj3 <>", value, "tpj3");
            return (Criteria) this;
        }

        public Criteria andTpj3GreaterThan(Float value) {
            addCriterion("Tpj3 >", value, "tpj3");
            return (Criteria) this;
        }

        public Criteria andTpj3GreaterThanOrEqualTo(Float value) {
            addCriterion("Tpj3 >=", value, "tpj3");
            return (Criteria) this;
        }

        public Criteria andTpj3LessThan(Float value) {
            addCriterion("Tpj3 <", value, "tpj3");
            return (Criteria) this;
        }

        public Criteria andTpj3LessThanOrEqualTo(Float value) {
            addCriterion("Tpj3 <=", value, "tpj3");
            return (Criteria) this;
        }

        public Criteria andTpj3In(List<Float> values) {
            addCriterion("Tpj3 in", values, "tpj3");
            return (Criteria) this;
        }

        public Criteria andTpj3NotIn(List<Float> values) {
            addCriterion("Tpj3 not in", values, "tpj3");
            return (Criteria) this;
        }

        public Criteria andTpj3Between(Float value1, Float value2) {
            addCriterion("Tpj3 between", value1, value2, "tpj3");
            return (Criteria) this;
        }

        public Criteria andTpj3NotBetween(Float value1, Float value2) {
            addCriterion("Tpj3 not between", value1, value2, "tpj3");
            return (Criteria) this;
        }

        public Criteria andTpj4IsNull() {
            addCriterion("Tpj4 is null");
            return (Criteria) this;
        }

        public Criteria andTpj4IsNotNull() {
            addCriterion("Tpj4 is not null");
            return (Criteria) this;
        }

        public Criteria andTpj4EqualTo(Float value) {
            addCriterion("Tpj4 =", value, "tpj4");
            return (Criteria) this;
        }

        public Criteria andTpj4NotEqualTo(Float value) {
            addCriterion("Tpj4 <>", value, "tpj4");
            return (Criteria) this;
        }

        public Criteria andTpj4GreaterThan(Float value) {
            addCriterion("Tpj4 >", value, "tpj4");
            return (Criteria) this;
        }

        public Criteria andTpj4GreaterThanOrEqualTo(Float value) {
            addCriterion("Tpj4 >=", value, "tpj4");
            return (Criteria) this;
        }

        public Criteria andTpj4LessThan(Float value) {
            addCriterion("Tpj4 <", value, "tpj4");
            return (Criteria) this;
        }

        public Criteria andTpj4LessThanOrEqualTo(Float value) {
            addCriterion("Tpj4 <=", value, "tpj4");
            return (Criteria) this;
        }

        public Criteria andTpj4In(List<Float> values) {
            addCriterion("Tpj4 in", values, "tpj4");
            return (Criteria) this;
        }

        public Criteria andTpj4NotIn(List<Float> values) {
            addCriterion("Tpj4 not in", values, "tpj4");
            return (Criteria) this;
        }

        public Criteria andTpj4Between(Float value1, Float value2) {
            addCriterion("Tpj4 between", value1, value2, "tpj4");
            return (Criteria) this;
        }

        public Criteria andTpj4NotBetween(Float value1, Float value2) {
            addCriterion("Tpj4 not between", value1, value2, "tpj4");
            return (Criteria) this;
        }

        public Criteria andTpj5IsNull() {
            addCriterion("Tpj5 is null");
            return (Criteria) this;
        }

        public Criteria andTpj5IsNotNull() {
            addCriterion("Tpj5 is not null");
            return (Criteria) this;
        }

        public Criteria andTpj5EqualTo(Float value) {
            addCriterion("Tpj5 =", value, "tpj5");
            return (Criteria) this;
        }

        public Criteria andTpj5NotEqualTo(Float value) {
            addCriterion("Tpj5 <>", value, "tpj5");
            return (Criteria) this;
        }

        public Criteria andTpj5GreaterThan(Float value) {
            addCriterion("Tpj5 >", value, "tpj5");
            return (Criteria) this;
        }

        public Criteria andTpj5GreaterThanOrEqualTo(Float value) {
            addCriterion("Tpj5 >=", value, "tpj5");
            return (Criteria) this;
        }

        public Criteria andTpj5LessThan(Float value) {
            addCriterion("Tpj5 <", value, "tpj5");
            return (Criteria) this;
        }

        public Criteria andTpj5LessThanOrEqualTo(Float value) {
            addCriterion("Tpj5 <=", value, "tpj5");
            return (Criteria) this;
        }

        public Criteria andTpj5In(List<Float> values) {
            addCriterion("Tpj5 in", values, "tpj5");
            return (Criteria) this;
        }

        public Criteria andTpj5NotIn(List<Float> values) {
            addCriterion("Tpj5 not in", values, "tpj5");
            return (Criteria) this;
        }

        public Criteria andTpj5Between(Float value1, Float value2) {
            addCriterion("Tpj5 between", value1, value2, "tpj5");
            return (Criteria) this;
        }

        public Criteria andTpj5NotBetween(Float value1, Float value2) {
            addCriterion("Tpj5 not between", value1, value2, "tpj5");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table data_para_cul
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table data_para_cul
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }


    ////*******自定义开始********/
    //***********自定义结束****////
}
