package com.xhkj.server.energy.dao.mybatis.vo;

public class Price {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_price.COMPANY_ID
     *
     * @mbg.generated
     */
    private Integer companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_price.FT3Q_PRICE
     *
     * @mbg.generated
     */
    private Float ft3qPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_price.JQI_PRICE
     *
     * @mbg.generated
     */
    private Float jqiPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_price.QQI_PRICE
     *
     * @mbg.generated
     */
    private Float qqiPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_price.COMPANY_ID
     *
     * @return the value of data_price.COMPANY_ID
     *
     * @mbg.generated
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_price.COMPANY_ID
     *
     * @param companyId the value for data_price.COMPANY_ID
     *
     * @mbg.generated
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_price.FT3Q_PRICE
     *
     * @return the value of data_price.FT3Q_PRICE
     *
     * @mbg.generated
     */
    public Float getFt3qPrice() {
        return ft3qPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_price.FT3Q_PRICE
     *
     * @param ft3qPrice the value for data_price.FT3Q_PRICE
     *
     * @mbg.generated
     */
    public void setFt3qPrice(Float ft3qPrice) {
        this.ft3qPrice = ft3qPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_price.JQI_PRICE
     *
     * @return the value of data_price.JQI_PRICE
     *
     * @mbg.generated
     */
    public Float getJqiPrice() {
        return jqiPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_price.JQI_PRICE
     *
     * @param jqiPrice the value for data_price.JQI_PRICE
     *
     * @mbg.generated
     */
    public void setJqiPrice(Float jqiPrice) {
        this.jqiPrice = jqiPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_price.QQI_PRICE
     *
     * @return the value of data_price.QQI_PRICE
     *
     * @mbg.generated
     */
    public Float getQqiPrice() {
        return qqiPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_price.QQI_PRICE
     *
     * @param qqiPrice the value for data_price.QQI_PRICE
     *
     * @mbg.generated
     */
    public void setQqiPrice(Float qqiPrice) {
        this.qqiPrice = qqiPrice;
    }


    ////*******自定义开始********/

    @Override
    public String toString() {
        return "Price{" +
                "companyId=" + companyId +
                ", ft3qPrice=" + ft3qPrice +
                ", jqiPrice=" + jqiPrice +
                ", qqiPrice=" + qqiPrice +
                '}';
    }

    //***********自定义结束****////
}
