package com.xhkj.server.energy.dao.mybatis.vo;

import java.util.ArrayList;
import java.util.List;

public class RoleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_role
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_role
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_role
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role
     *
     * @mbg.generated
     */
    public RoleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sys_role
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRoleIdIsNull() {
            addCriterion("ROLE_ID is null");
            return (Criteria) this;
        }

        public Criteria andRoleIdIsNotNull() {
            addCriterion("ROLE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRoleIdEqualTo(Integer value) {
            addCriterion("ROLE_ID =", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdNotEqualTo(Integer value) {
            addCriterion("ROLE_ID <>", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdGreaterThan(Integer value) {
            addCriterion("ROLE_ID >", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ROLE_ID >=", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdLessThan(Integer value) {
            addCriterion("ROLE_ID <", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdLessThanOrEqualTo(Integer value) {
            addCriterion("ROLE_ID <=", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdIn(List<Integer> values) {
            addCriterion("ROLE_ID in", values, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdNotIn(List<Integer> values) {
            addCriterion("ROLE_ID not in", values, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdBetween(Integer value1, Integer value2) {
            addCriterion("ROLE_ID between", value1, value2, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ROLE_ID not between", value1, value2, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleNameIsNull() {
            addCriterion("ROLE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andRoleNameIsNotNull() {
            addCriterion("ROLE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andRoleNameEqualTo(String value) {
            addCriterion("ROLE_NAME =", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameNotEqualTo(String value) {
            addCriterion("ROLE_NAME <>", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameGreaterThan(String value) {
            addCriterion("ROLE_NAME >", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameGreaterThanOrEqualTo(String value) {
            addCriterion("ROLE_NAME >=", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameLessThan(String value) {
            addCriterion("ROLE_NAME <", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameLessThanOrEqualTo(String value) {
            addCriterion("ROLE_NAME <=", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameLike(String value) {
            addCriterion("ROLE_NAME like", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameNotLike(String value) {
            addCriterion("ROLE_NAME not like", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameIn(List<String> values) {
            addCriterion("ROLE_NAME in", values, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameNotIn(List<String> values) {
            addCriterion("ROLE_NAME not in", values, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameBetween(String value1, String value2) {
            addCriterion("ROLE_NAME between", value1, value2, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameNotBetween(String value1, String value2) {
            addCriterion("ROLE_NAME not between", value1, value2, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleTypeIsNull() {
            addCriterion("ROLE_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andRoleTypeIsNotNull() {
            addCriterion("ROLE_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andRoleTypeEqualTo(String value) {
            addCriterion("ROLE_TYPE =", value, "roleType");
            return (Criteria) this;
        }

        public Criteria andRoleTypeNotEqualTo(String value) {
            addCriterion("ROLE_TYPE <>", value, "roleType");
            return (Criteria) this;
        }

        public Criteria andRoleTypeGreaterThan(String value) {
            addCriterion("ROLE_TYPE >", value, "roleType");
            return (Criteria) this;
        }

        public Criteria andRoleTypeGreaterThanOrEqualTo(String value) {
            addCriterion("ROLE_TYPE >=", value, "roleType");
            return (Criteria) this;
        }

        public Criteria andRoleTypeLessThan(String value) {
            addCriterion("ROLE_TYPE <", value, "roleType");
            return (Criteria) this;
        }

        public Criteria andRoleTypeLessThanOrEqualTo(String value) {
            addCriterion("ROLE_TYPE <=", value, "roleType");
            return (Criteria) this;
        }

        public Criteria andRoleTypeLike(String value) {
            addCriterion("ROLE_TYPE like", value, "roleType");
            return (Criteria) this;
        }

        public Criteria andRoleTypeNotLike(String value) {
            addCriterion("ROLE_TYPE not like", value, "roleType");
            return (Criteria) this;
        }

        public Criteria andRoleTypeIn(List<String> values) {
            addCriterion("ROLE_TYPE in", values, "roleType");
            return (Criteria) this;
        }

        public Criteria andRoleTypeNotIn(List<String> values) {
            addCriterion("ROLE_TYPE not in", values, "roleType");
            return (Criteria) this;
        }

        public Criteria andRoleTypeBetween(String value1, String value2) {
            addCriterion("ROLE_TYPE between", value1, value2, "roleType");
            return (Criteria) this;
        }

        public Criteria andRoleTypeNotBetween(String value1, String value2) {
            addCriterion("ROLE_TYPE not between", value1, value2, "roleType");
            return (Criteria) this;
        }

        public Criteria andRoleStsIsNull() {
            addCriterion("ROLE_STS is null");
            return (Criteria) this;
        }

        public Criteria andRoleStsIsNotNull() {
            addCriterion("ROLE_STS is not null");
            return (Criteria) this;
        }

        public Criteria andRoleStsEqualTo(String value) {
            addCriterion("ROLE_STS =", value, "roleSts");
            return (Criteria) this;
        }

        public Criteria andRoleStsNotEqualTo(String value) {
            addCriterion("ROLE_STS <>", value, "roleSts");
            return (Criteria) this;
        }

        public Criteria andRoleStsGreaterThan(String value) {
            addCriterion("ROLE_STS >", value, "roleSts");
            return (Criteria) this;
        }

        public Criteria andRoleStsGreaterThanOrEqualTo(String value) {
            addCriterion("ROLE_STS >=", value, "roleSts");
            return (Criteria) this;
        }

        public Criteria andRoleStsLessThan(String value) {
            addCriterion("ROLE_STS <", value, "roleSts");
            return (Criteria) this;
        }

        public Criteria andRoleStsLessThanOrEqualTo(String value) {
            addCriterion("ROLE_STS <=", value, "roleSts");
            return (Criteria) this;
        }

        public Criteria andRoleStsLike(String value) {
            addCriterion("ROLE_STS like", value, "roleSts");
            return (Criteria) this;
        }

        public Criteria andRoleStsNotLike(String value) {
            addCriterion("ROLE_STS not like", value, "roleSts");
            return (Criteria) this;
        }

        public Criteria andRoleStsIn(List<String> values) {
            addCriterion("ROLE_STS in", values, "roleSts");
            return (Criteria) this;
        }

        public Criteria andRoleStsNotIn(List<String> values) {
            addCriterion("ROLE_STS not in", values, "roleSts");
            return (Criteria) this;
        }

        public Criteria andRoleStsBetween(String value1, String value2) {
            addCriterion("ROLE_STS between", value1, value2, "roleSts");
            return (Criteria) this;
        }

        public Criteria andRoleStsNotBetween(String value1, String value2) {
            addCriterion("ROLE_STS not between", value1, value2, "roleSts");
            return (Criteria) this;
        }

        public Criteria andRoleDesIsNull() {
            addCriterion("ROLE_DES is null");
            return (Criteria) this;
        }

        public Criteria andRoleDesIsNotNull() {
            addCriterion("ROLE_DES is not null");
            return (Criteria) this;
        }

        public Criteria andRoleDesEqualTo(String value) {
            addCriterion("ROLE_DES =", value, "roleDes");
            return (Criteria) this;
        }

        public Criteria andRoleDesNotEqualTo(String value) {
            addCriterion("ROLE_DES <>", value, "roleDes");
            return (Criteria) this;
        }

        public Criteria andRoleDesGreaterThan(String value) {
            addCriterion("ROLE_DES >", value, "roleDes");
            return (Criteria) this;
        }

        public Criteria andRoleDesGreaterThanOrEqualTo(String value) {
            addCriterion("ROLE_DES >=", value, "roleDes");
            return (Criteria) this;
        }

        public Criteria andRoleDesLessThan(String value) {
            addCriterion("ROLE_DES <", value, "roleDes");
            return (Criteria) this;
        }

        public Criteria andRoleDesLessThanOrEqualTo(String value) {
            addCriterion("ROLE_DES <=", value, "roleDes");
            return (Criteria) this;
        }

        public Criteria andRoleDesLike(String value) {
            addCriterion("ROLE_DES like", value, "roleDes");
            return (Criteria) this;
        }

        public Criteria andRoleDesNotLike(String value) {
            addCriterion("ROLE_DES not like", value, "roleDes");
            return (Criteria) this;
        }

        public Criteria andRoleDesIn(List<String> values) {
            addCriterion("ROLE_DES in", values, "roleDes");
            return (Criteria) this;
        }

        public Criteria andRoleDesNotIn(List<String> values) {
            addCriterion("ROLE_DES not in", values, "roleDes");
            return (Criteria) this;
        }

        public Criteria andRoleDesBetween(String value1, String value2) {
            addCriterion("ROLE_DES between", value1, value2, "roleDes");
            return (Criteria) this;
        }

        public Criteria andRoleDesNotBetween(String value1, String value2) {
            addCriterion("ROLE_DES not between", value1, value2, "roleDes");
            return (Criteria) this;
        }

        public Criteria andRmkIsNull() {
            addCriterion("RMK is null");
            return (Criteria) this;
        }

        public Criteria andRmkIsNotNull() {
            addCriterion("RMK is not null");
            return (Criteria) this;
        }

        public Criteria andRmkEqualTo(String value) {
            addCriterion("RMK =", value, "rmk");
            return (Criteria) this;
        }

        public Criteria andRmkNotEqualTo(String value) {
            addCriterion("RMK <>", value, "rmk");
            return (Criteria) this;
        }

        public Criteria andRmkGreaterThan(String value) {
            addCriterion("RMK >", value, "rmk");
            return (Criteria) this;
        }

        public Criteria andRmkGreaterThanOrEqualTo(String value) {
            addCriterion("RMK >=", value, "rmk");
            return (Criteria) this;
        }

        public Criteria andRmkLessThan(String value) {
            addCriterion("RMK <", value, "rmk");
            return (Criteria) this;
        }

        public Criteria andRmkLessThanOrEqualTo(String value) {
            addCriterion("RMK <=", value, "rmk");
            return (Criteria) this;
        }

        public Criteria andRmkLike(String value) {
            addCriterion("RMK like", value, "rmk");
            return (Criteria) this;
        }

        public Criteria andRmkNotLike(String value) {
            addCriterion("RMK not like", value, "rmk");
            return (Criteria) this;
        }

        public Criteria andRmkIn(List<String> values) {
            addCriterion("RMK in", values, "rmk");
            return (Criteria) this;
        }

        public Criteria andRmkNotIn(List<String> values) {
            addCriterion("RMK not in", values, "rmk");
            return (Criteria) this;
        }

        public Criteria andRmkBetween(String value1, String value2) {
            addCriterion("RMK between", value1, value2, "rmk");
            return (Criteria) this;
        }

        public Criteria andRmkNotBetween(String value1, String value2) {
            addCriterion("RMK not between", value1, value2, "rmk");
            return (Criteria) this;
        }

        public Criteria andCrtIdIsNull() {
            addCriterion("CRT_ID is null");
            return (Criteria) this;
        }

        public Criteria andCrtIdIsNotNull() {
            addCriterion("CRT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCrtIdEqualTo(String value) {
            addCriterion("CRT_ID =", value, "crtId");
            return (Criteria) this;
        }

        public Criteria andCrtIdNotEqualTo(String value) {
            addCriterion("CRT_ID <>", value, "crtId");
            return (Criteria) this;
        }

        public Criteria andCrtIdGreaterThan(String value) {
            addCriterion("CRT_ID >", value, "crtId");
            return (Criteria) this;
        }

        public Criteria andCrtIdGreaterThanOrEqualTo(String value) {
            addCriterion("CRT_ID >=", value, "crtId");
            return (Criteria) this;
        }

        public Criteria andCrtIdLessThan(String value) {
            addCriterion("CRT_ID <", value, "crtId");
            return (Criteria) this;
        }

        public Criteria andCrtIdLessThanOrEqualTo(String value) {
            addCriterion("CRT_ID <=", value, "crtId");
            return (Criteria) this;
        }

        public Criteria andCrtIdLike(String value) {
            addCriterion("CRT_ID like", value, "crtId");
            return (Criteria) this;
        }

        public Criteria andCrtIdNotLike(String value) {
            addCriterion("CRT_ID not like", value, "crtId");
            return (Criteria) this;
        }

        public Criteria andCrtIdIn(List<String> values) {
            addCriterion("CRT_ID in", values, "crtId");
            return (Criteria) this;
        }

        public Criteria andCrtIdNotIn(List<String> values) {
            addCriterion("CRT_ID not in", values, "crtId");
            return (Criteria) this;
        }

        public Criteria andCrtIdBetween(String value1, String value2) {
            addCriterion("CRT_ID between", value1, value2, "crtId");
            return (Criteria) this;
        }

        public Criteria andCrtIdNotBetween(String value1, String value2) {
            addCriterion("CRT_ID not between", value1, value2, "crtId");
            return (Criteria) this;
        }

        public Criteria andCrtDtIsNull() {
            addCriterion("CRT_DT is null");
            return (Criteria) this;
        }

        public Criteria andCrtDtIsNotNull() {
            addCriterion("CRT_DT is not null");
            return (Criteria) this;
        }

        public Criteria andCrtDtEqualTo(String value) {
            addCriterion("CRT_DT =", value, "crtDt");
            return (Criteria) this;
        }

        public Criteria andCrtDtNotEqualTo(String value) {
            addCriterion("CRT_DT <>", value, "crtDt");
            return (Criteria) this;
        }

        public Criteria andCrtDtGreaterThan(String value) {
            addCriterion("CRT_DT >", value, "crtDt");
            return (Criteria) this;
        }

        public Criteria andCrtDtGreaterThanOrEqualTo(String value) {
            addCriterion("CRT_DT >=", value, "crtDt");
            return (Criteria) this;
        }

        public Criteria andCrtDtLessThan(String value) {
            addCriterion("CRT_DT <", value, "crtDt");
            return (Criteria) this;
        }

        public Criteria andCrtDtLessThanOrEqualTo(String value) {
            addCriterion("CRT_DT <=", value, "crtDt");
            return (Criteria) this;
        }

        public Criteria andCrtDtLike(String value) {
            addCriterion("CRT_DT like", value, "crtDt");
            return (Criteria) this;
        }

        public Criteria andCrtDtNotLike(String value) {
            addCriterion("CRT_DT not like", value, "crtDt");
            return (Criteria) this;
        }

        public Criteria andCrtDtIn(List<String> values) {
            addCriterion("CRT_DT in", values, "crtDt");
            return (Criteria) this;
        }

        public Criteria andCrtDtNotIn(List<String> values) {
            addCriterion("CRT_DT not in", values, "crtDt");
            return (Criteria) this;
        }

        public Criteria andCrtDtBetween(String value1, String value2) {
            addCriterion("CRT_DT between", value1, value2, "crtDt");
            return (Criteria) this;
        }

        public Criteria andCrtDtNotBetween(String value1, String value2) {
            addCriterion("CRT_DT not between", value1, value2, "crtDt");
            return (Criteria) this;
        }

        public Criteria andCrtTmIsNull() {
            addCriterion("CRT_TM is null");
            return (Criteria) this;
        }

        public Criteria andCrtTmIsNotNull() {
            addCriterion("CRT_TM is not null");
            return (Criteria) this;
        }

        public Criteria andCrtTmEqualTo(String value) {
            addCriterion("CRT_TM =", value, "crtTm");
            return (Criteria) this;
        }

        public Criteria andCrtTmNotEqualTo(String value) {
            addCriterion("CRT_TM <>", value, "crtTm");
            return (Criteria) this;
        }

        public Criteria andCrtTmGreaterThan(String value) {
            addCriterion("CRT_TM >", value, "crtTm");
            return (Criteria) this;
        }

        public Criteria andCrtTmGreaterThanOrEqualTo(String value) {
            addCriterion("CRT_TM >=", value, "crtTm");
            return (Criteria) this;
        }

        public Criteria andCrtTmLessThan(String value) {
            addCriterion("CRT_TM <", value, "crtTm");
            return (Criteria) this;
        }

        public Criteria andCrtTmLessThanOrEqualTo(String value) {
            addCriterion("CRT_TM <=", value, "crtTm");
            return (Criteria) this;
        }

        public Criteria andCrtTmLike(String value) {
            addCriterion("CRT_TM like", value, "crtTm");
            return (Criteria) this;
        }

        public Criteria andCrtTmNotLike(String value) {
            addCriterion("CRT_TM not like", value, "crtTm");
            return (Criteria) this;
        }

        public Criteria andCrtTmIn(List<String> values) {
            addCriterion("CRT_TM in", values, "crtTm");
            return (Criteria) this;
        }

        public Criteria andCrtTmNotIn(List<String> values) {
            addCriterion("CRT_TM not in", values, "crtTm");
            return (Criteria) this;
        }

        public Criteria andCrtTmBetween(String value1, String value2) {
            addCriterion("CRT_TM between", value1, value2, "crtTm");
            return (Criteria) this;
        }

        public Criteria andCrtTmNotBetween(String value1, String value2) {
            addCriterion("CRT_TM not between", value1, value2, "crtTm");
            return (Criteria) this;
        }

        public Criteria andUptIdIsNull() {
            addCriterion("UPT_ID is null");
            return (Criteria) this;
        }

        public Criteria andUptIdIsNotNull() {
            addCriterion("UPT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUptIdEqualTo(String value) {
            addCriterion("UPT_ID =", value, "uptId");
            return (Criteria) this;
        }

        public Criteria andUptIdNotEqualTo(String value) {
            addCriterion("UPT_ID <>", value, "uptId");
            return (Criteria) this;
        }

        public Criteria andUptIdGreaterThan(String value) {
            addCriterion("UPT_ID >", value, "uptId");
            return (Criteria) this;
        }

        public Criteria andUptIdGreaterThanOrEqualTo(String value) {
            addCriterion("UPT_ID >=", value, "uptId");
            return (Criteria) this;
        }

        public Criteria andUptIdLessThan(String value) {
            addCriterion("UPT_ID <", value, "uptId");
            return (Criteria) this;
        }

        public Criteria andUptIdLessThanOrEqualTo(String value) {
            addCriterion("UPT_ID <=", value, "uptId");
            return (Criteria) this;
        }

        public Criteria andUptIdLike(String value) {
            addCriterion("UPT_ID like", value, "uptId");
            return (Criteria) this;
        }

        public Criteria andUptIdNotLike(String value) {
            addCriterion("UPT_ID not like", value, "uptId");
            return (Criteria) this;
        }

        public Criteria andUptIdIn(List<String> values) {
            addCriterion("UPT_ID in", values, "uptId");
            return (Criteria) this;
        }

        public Criteria andUptIdNotIn(List<String> values) {
            addCriterion("UPT_ID not in", values, "uptId");
            return (Criteria) this;
        }

        public Criteria andUptIdBetween(String value1, String value2) {
            addCriterion("UPT_ID between", value1, value2, "uptId");
            return (Criteria) this;
        }

        public Criteria andUptIdNotBetween(String value1, String value2) {
            addCriterion("UPT_ID not between", value1, value2, "uptId");
            return (Criteria) this;
        }

        public Criteria andUptDtIsNull() {
            addCriterion("UPT_DT is null");
            return (Criteria) this;
        }

        public Criteria andUptDtIsNotNull() {
            addCriterion("UPT_DT is not null");
            return (Criteria) this;
        }

        public Criteria andUptDtEqualTo(String value) {
            addCriterion("UPT_DT =", value, "uptDt");
            return (Criteria) this;
        }

        public Criteria andUptDtNotEqualTo(String value) {
            addCriterion("UPT_DT <>", value, "uptDt");
            return (Criteria) this;
        }

        public Criteria andUptDtGreaterThan(String value) {
            addCriterion("UPT_DT >", value, "uptDt");
            return (Criteria) this;
        }

        public Criteria andUptDtGreaterThanOrEqualTo(String value) {
            addCriterion("UPT_DT >=", value, "uptDt");
            return (Criteria) this;
        }

        public Criteria andUptDtLessThan(String value) {
            addCriterion("UPT_DT <", value, "uptDt");
            return (Criteria) this;
        }

        public Criteria andUptDtLessThanOrEqualTo(String value) {
            addCriterion("UPT_DT <=", value, "uptDt");
            return (Criteria) this;
        }

        public Criteria andUptDtLike(String value) {
            addCriterion("UPT_DT like", value, "uptDt");
            return (Criteria) this;
        }

        public Criteria andUptDtNotLike(String value) {
            addCriterion("UPT_DT not like", value, "uptDt");
            return (Criteria) this;
        }

        public Criteria andUptDtIn(List<String> values) {
            addCriterion("UPT_DT in", values, "uptDt");
            return (Criteria) this;
        }

        public Criteria andUptDtNotIn(List<String> values) {
            addCriterion("UPT_DT not in", values, "uptDt");
            return (Criteria) this;
        }

        public Criteria andUptDtBetween(String value1, String value2) {
            addCriterion("UPT_DT between", value1, value2, "uptDt");
            return (Criteria) this;
        }

        public Criteria andUptDtNotBetween(String value1, String value2) {
            addCriterion("UPT_DT not between", value1, value2, "uptDt");
            return (Criteria) this;
        }

        public Criteria andUptTmIsNull() {
            addCriterion("UPT_TM is null");
            return (Criteria) this;
        }

        public Criteria andUptTmIsNotNull() {
            addCriterion("UPT_TM is not null");
            return (Criteria) this;
        }

        public Criteria andUptTmEqualTo(String value) {
            addCriterion("UPT_TM =", value, "uptTm");
            return (Criteria) this;
        }

        public Criteria andUptTmNotEqualTo(String value) {
            addCriterion("UPT_TM <>", value, "uptTm");
            return (Criteria) this;
        }

        public Criteria andUptTmGreaterThan(String value) {
            addCriterion("UPT_TM >", value, "uptTm");
            return (Criteria) this;
        }

        public Criteria andUptTmGreaterThanOrEqualTo(String value) {
            addCriterion("UPT_TM >=", value, "uptTm");
            return (Criteria) this;
        }

        public Criteria andUptTmLessThan(String value) {
            addCriterion("UPT_TM <", value, "uptTm");
            return (Criteria) this;
        }

        public Criteria andUptTmLessThanOrEqualTo(String value) {
            addCriterion("UPT_TM <=", value, "uptTm");
            return (Criteria) this;
        }

        public Criteria andUptTmLike(String value) {
            addCriterion("UPT_TM like", value, "uptTm");
            return (Criteria) this;
        }

        public Criteria andUptTmNotLike(String value) {
            addCriterion("UPT_TM not like", value, "uptTm");
            return (Criteria) this;
        }

        public Criteria andUptTmIn(List<String> values) {
            addCriterion("UPT_TM in", values, "uptTm");
            return (Criteria) this;
        }

        public Criteria andUptTmNotIn(List<String> values) {
            addCriterion("UPT_TM not in", values, "uptTm");
            return (Criteria) this;
        }

        public Criteria andUptTmBetween(String value1, String value2) {
            addCriterion("UPT_TM between", value1, value2, "uptTm");
            return (Criteria) this;
        }

        public Criteria andUptTmNotBetween(String value1, String value2) {
            addCriterion("UPT_TM not between", value1, value2, "uptTm");
            return (Criteria) this;
        }

        public Criteria andTmSmpIsNull() {
            addCriterion("TM_SMP is null");
            return (Criteria) this;
        }

        public Criteria andTmSmpIsNotNull() {
            addCriterion("TM_SMP is not null");
            return (Criteria) this;
        }

        public Criteria andTmSmpEqualTo(String value) {
            addCriterion("TM_SMP =", value, "tmSmp");
            return (Criteria) this;
        }

        public Criteria andTmSmpNotEqualTo(String value) {
            addCriterion("TM_SMP <>", value, "tmSmp");
            return (Criteria) this;
        }

        public Criteria andTmSmpGreaterThan(String value) {
            addCriterion("TM_SMP >", value, "tmSmp");
            return (Criteria) this;
        }

        public Criteria andTmSmpGreaterThanOrEqualTo(String value) {
            addCriterion("TM_SMP >=", value, "tmSmp");
            return (Criteria) this;
        }

        public Criteria andTmSmpLessThan(String value) {
            addCriterion("TM_SMP <", value, "tmSmp");
            return (Criteria) this;
        }

        public Criteria andTmSmpLessThanOrEqualTo(String value) {
            addCriterion("TM_SMP <=", value, "tmSmp");
            return (Criteria) this;
        }

        public Criteria andTmSmpLike(String value) {
            addCriterion("TM_SMP like", value, "tmSmp");
            return (Criteria) this;
        }

        public Criteria andTmSmpNotLike(String value) {
            addCriterion("TM_SMP not like", value, "tmSmp");
            return (Criteria) this;
        }

        public Criteria andTmSmpIn(List<String> values) {
            addCriterion("TM_SMP in", values, "tmSmp");
            return (Criteria) this;
        }

        public Criteria andTmSmpNotIn(List<String> values) {
            addCriterion("TM_SMP not in", values, "tmSmp");
            return (Criteria) this;
        }

        public Criteria andTmSmpBetween(String value1, String value2) {
            addCriterion("TM_SMP between", value1, value2, "tmSmp");
            return (Criteria) this;
        }

        public Criteria andTmSmpNotBetween(String value1, String value2) {
            addCriterion("TM_SMP not between", value1, value2, "tmSmp");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sys_role
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sys_role
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }


    ////*******自定义开始********/
    //***********自定义结束****////
}
