package com.xhkj.server.energy.dao.mybatis.vo;

public class RoleItemRel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_role_item_rel.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_role_item_rel.ROLE_ID
     *
     * @mbg.generated
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_role_item_rel.ITEM_ID
     *
     * @mbg.generated
     */
    private Integer itemId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_role_item_rel.ID
     *
     * @return the value of t_sys_role_item_rel.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_role_item_rel.ID
     *
     * @param id the value for t_sys_role_item_rel.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_role_item_rel.ROLE_ID
     *
     * @return the value of t_sys_role_item_rel.ROLE_ID
     *
     * @mbg.generated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_role_item_rel.ROLE_ID
     *
     * @param roleId the value for t_sys_role_item_rel.ROLE_ID
     *
     * @mbg.generated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_role_item_rel.ITEM_ID
     *
     * @return the value of t_sys_role_item_rel.ITEM_ID
     *
     * @mbg.generated
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_role_item_rel.ITEM_ID
     *
     * @param itemId the value for t_sys_role_item_rel.ITEM_ID
     *
     * @mbg.generated
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }


    ////*******自定义开始********/
    //***********自定义结束****////
}
