package com.xhkj.server.energy.dao.mybatis.vo;

public class StandData extends StandDataKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_stand.STAND_NAME
     *
     * @mbg.generated
     */
    private String standName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_stand.STATION_ID
     *
     * @mbg.generated
     */
    private String stationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_stand.DESIGN_AREA
     *
     * @mbg.generated
     */
    private Integer designArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_stand.REAL_AREA
     *
     * @mbg.generated
     */
    private Integer realArea;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_stand.STAND_NAME
     *
     * @return the value of data_stand.STAND_NAME
     *
     * @mbg.generated
     */
    public String getStandName() {
        return standName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_stand.STAND_NAME
     *
     * @param standName the value for data_stand.STAND_NAME
     *
     * @mbg.generated
     */
    public void setStandName(String standName) {
        this.standName = standName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_stand.STATION_ID
     *
     * @return the value of data_stand.STATION_ID
     *
     * @mbg.generated
     */
    public String getStationId() {
        return stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_stand.STATION_ID
     *
     * @param stationId the value for data_stand.STATION_ID
     *
     * @mbg.generated
     */
    public void setStationId(String stationId) {
        this.stationId = stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_stand.DESIGN_AREA
     *
     * @return the value of data_stand.DESIGN_AREA
     *
     * @mbg.generated
     */
    public Integer getDesignArea() {
        return designArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_stand.DESIGN_AREA
     *
     * @param designArea the value for data_stand.DESIGN_AREA
     *
     * @mbg.generated
     */
    public void setDesignArea(Integer designArea) {
        this.designArea = designArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_stand.REAL_AREA
     *
     * @return the value of data_stand.REAL_AREA
     *
     * @mbg.generated
     */
    public Integer getRealArea() {
        return realArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_stand.REAL_AREA
     *
     * @param realArea the value for data_stand.REAL_AREA
     *
     * @mbg.generated
     */
    public void setRealArea(Integer realArea) {
        this.realArea = realArea;
    }


    ////*******自定义开始********/
    //***********自定义结束****////
}
