package com.xhkj.server.energy.dao.mybatis.vo;

import java.util.ArrayList;
import java.util.List;

public class StandBasicDataExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table data_stand_basic
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table data_stand_basic
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table data_stand_basic
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_stand_basic
     *
     * @mbg.generated
     */
    public StandBasicDataExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_stand_basic
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_stand_basic
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_stand_basic
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_stand_basic
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_stand_basic
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_stand_basic
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_stand_basic
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_stand_basic
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_stand_basic
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_stand_basic
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table data_stand_basic
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCompanyIdIsNull() {
            addCriterion("COMPANY_ID is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNotNull() {
            addCriterion("COMPANY_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdEqualTo(Integer value) {
            addCriterion("COMPANY_ID =", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotEqualTo(Integer value) {
            addCriterion("COMPANY_ID <>", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThan(Integer value) {
            addCriterion("COMPANY_ID >", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("COMPANY_ID >=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThan(Integer value) {
            addCriterion("COMPANY_ID <", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThanOrEqualTo(Integer value) {
            addCriterion("COMPANY_ID <=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIn(List<Integer> values) {
            addCriterion("COMPANY_ID in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotIn(List<Integer> values) {
            addCriterion("COMPANY_ID not in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdBetween(Integer value1, Integer value2) {
            addCriterion("COMPANY_ID between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotBetween(Integer value1, Integer value2) {
            addCriterion("COMPANY_ID not between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andStandIdIsNull() {
            addCriterion("STAND_ID is null");
            return (Criteria) this;
        }

        public Criteria andStandIdIsNotNull() {
            addCriterion("STAND_ID is not null");
            return (Criteria) this;
        }

        public Criteria andStandIdEqualTo(String value) {
            addCriterion("STAND_ID =", value, "standId");
            return (Criteria) this;
        }

        public Criteria andStandIdNotEqualTo(String value) {
            addCriterion("STAND_ID <>", value, "standId");
            return (Criteria) this;
        }

        public Criteria andStandIdGreaterThan(String value) {
            addCriterion("STAND_ID >", value, "standId");
            return (Criteria) this;
        }

        public Criteria andStandIdGreaterThanOrEqualTo(String value) {
            addCriterion("STAND_ID >=", value, "standId");
            return (Criteria) this;
        }

        public Criteria andStandIdLessThan(String value) {
            addCriterion("STAND_ID <", value, "standId");
            return (Criteria) this;
        }

        public Criteria andStandIdLessThanOrEqualTo(String value) {
            addCriterion("STAND_ID <=", value, "standId");
            return (Criteria) this;
        }

        public Criteria andStandIdLike(String value) {
            addCriterion("STAND_ID like", value, "standId");
            return (Criteria) this;
        }

        public Criteria andStandIdNotLike(String value) {
            addCriterion("STAND_ID not like", value, "standId");
            return (Criteria) this;
        }

        public Criteria andStandIdIn(List<String> values) {
            addCriterion("STAND_ID in", values, "standId");
            return (Criteria) this;
        }

        public Criteria andStandIdNotIn(List<String> values) {
            addCriterion("STAND_ID not in", values, "standId");
            return (Criteria) this;
        }

        public Criteria andStandIdBetween(String value1, String value2) {
            addCriterion("STAND_ID between", value1, value2, "standId");
            return (Criteria) this;
        }

        public Criteria andStandIdNotBetween(String value1, String value2) {
            addCriterion("STAND_ID not between", value1, value2, "standId");
            return (Criteria) this;
        }

        public Criteria andStandNameIsNull() {
            addCriterion("stand_name is null");
            return (Criteria) this;
        }

        public Criteria andStandNameIsNotNull() {
            addCriterion("stand_name is not null");
            return (Criteria) this;
        }

        public Criteria andStandNameEqualTo(String value) {
            addCriterion("stand_name =", value, "standName");
            return (Criteria) this;
        }

        public Criteria andStandNameNotEqualTo(String value) {
            addCriterion("stand_name <>", value, "standName");
            return (Criteria) this;
        }

        public Criteria andStandNameGreaterThan(String value) {
            addCriterion("stand_name >", value, "standName");
            return (Criteria) this;
        }

        public Criteria andStandNameGreaterThanOrEqualTo(String value) {
            addCriterion("stand_name >=", value, "standName");
            return (Criteria) this;
        }

        public Criteria andStandNameLessThan(String value) {
            addCriterion("stand_name <", value, "standName");
            return (Criteria) this;
        }

        public Criteria andStandNameLessThanOrEqualTo(String value) {
            addCriterion("stand_name <=", value, "standName");
            return (Criteria) this;
        }

        public Criteria andStandNameLike(String value) {
            addCriterion("stand_name like", value, "standName");
            return (Criteria) this;
        }

        public Criteria andStandNameNotLike(String value) {
            addCriterion("stand_name not like", value, "standName");
            return (Criteria) this;
        }

        public Criteria andStandNameIn(List<String> values) {
            addCriterion("stand_name in", values, "standName");
            return (Criteria) this;
        }

        public Criteria andStandNameNotIn(List<String> values) {
            addCriterion("stand_name not in", values, "standName");
            return (Criteria) this;
        }

        public Criteria andStandNameBetween(String value1, String value2) {
            addCriterion("stand_name between", value1, value2, "standName");
            return (Criteria) this;
        }

        public Criteria andStandNameNotBetween(String value1, String value2) {
            addCriterion("stand_name not between", value1, value2, "standName");
            return (Criteria) this;
        }

        public Criteria andStationIdIsNull() {
            addCriterion("station_id is null");
            return (Criteria) this;
        }

        public Criteria andStationIdIsNotNull() {
            addCriterion("station_id is not null");
            return (Criteria) this;
        }

        public Criteria andStationIdEqualTo(String value) {
            addCriterion("station_id =", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdNotEqualTo(String value) {
            addCriterion("station_id <>", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdGreaterThan(String value) {
            addCriterion("station_id >", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdGreaterThanOrEqualTo(String value) {
            addCriterion("station_id >=", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdLessThan(String value) {
            addCriterion("station_id <", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdLessThanOrEqualTo(String value) {
            addCriterion("station_id <=", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdLike(String value) {
            addCriterion("station_id like", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdNotLike(String value) {
            addCriterion("station_id not like", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdIn(List<String> values) {
            addCriterion("station_id in", values, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdNotIn(List<String> values) {
            addCriterion("station_id not in", values, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdBetween(String value1, String value2) {
            addCriterion("station_id between", value1, value2, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdNotBetween(String value1, String value2) {
            addCriterion("station_id not between", value1, value2, "stationId");
            return (Criteria) this;
        }

        public Criteria andTotalAreaIsNull() {
            addCriterion("total_area is null");
            return (Criteria) this;
        }

        public Criteria andTotalAreaIsNotNull() {
            addCriterion("total_area is not null");
            return (Criteria) this;
        }

        public Criteria andTotalAreaEqualTo(Float value) {
            addCriterion("total_area =", value, "totalArea");
            return (Criteria) this;
        }

        public Criteria andTotalAreaNotEqualTo(Float value) {
            addCriterion("total_area <>", value, "totalArea");
            return (Criteria) this;
        }

        public Criteria andTotalAreaGreaterThan(Float value) {
            addCriterion("total_area >", value, "totalArea");
            return (Criteria) this;
        }

        public Criteria andTotalAreaGreaterThanOrEqualTo(Float value) {
            addCriterion("total_area >=", value, "totalArea");
            return (Criteria) this;
        }

        public Criteria andTotalAreaLessThan(Float value) {
            addCriterion("total_area <", value, "totalArea");
            return (Criteria) this;
        }

        public Criteria andTotalAreaLessThanOrEqualTo(Float value) {
            addCriterion("total_area <=", value, "totalArea");
            return (Criteria) this;
        }

        public Criteria andTotalAreaIn(List<Float> values) {
            addCriterion("total_area in", values, "totalArea");
            return (Criteria) this;
        }

        public Criteria andTotalAreaNotIn(List<Float> values) {
            addCriterion("total_area not in", values, "totalArea");
            return (Criteria) this;
        }

        public Criteria andTotalAreaBetween(Float value1, Float value2) {
            addCriterion("total_area between", value1, value2, "totalArea");
            return (Criteria) this;
        }

        public Criteria andTotalAreaNotBetween(Float value1, Float value2) {
            addCriterion("total_area not between", value1, value2, "totalArea");
            return (Criteria) this;
        }

        public Criteria andStandFhIsNull() {
            addCriterion("stand_fh is null");
            return (Criteria) this;
        }

        public Criteria andStandFhIsNotNull() {
            addCriterion("stand_fh is not null");
            return (Criteria) this;
        }

        public Criteria andStandFhEqualTo(String value) {
            addCriterion("stand_fh =", value, "standFh");
            return (Criteria) this;
        }

        public Criteria andStandFhNotEqualTo(String value) {
            addCriterion("stand_fh <>", value, "standFh");
            return (Criteria) this;
        }

        public Criteria andStandFhGreaterThan(String value) {
            addCriterion("stand_fh >", value, "standFh");
            return (Criteria) this;
        }

        public Criteria andStandFhGreaterThanOrEqualTo(String value) {
            addCriterion("stand_fh >=", value, "standFh");
            return (Criteria) this;
        }

        public Criteria andStandFhLessThan(String value) {
            addCriterion("stand_fh <", value, "standFh");
            return (Criteria) this;
        }

        public Criteria andStandFhLessThanOrEqualTo(String value) {
            addCriterion("stand_fh <=", value, "standFh");
            return (Criteria) this;
        }

        public Criteria andStandFhLike(String value) {
            addCriterion("stand_fh like", value, "standFh");
            return (Criteria) this;
        }

        public Criteria andStandFhNotLike(String value) {
            addCriterion("stand_fh not like", value, "standFh");
            return (Criteria) this;
        }

        public Criteria andStandFhIn(List<String> values) {
            addCriterion("stand_fh in", values, "standFh");
            return (Criteria) this;
        }

        public Criteria andStandFhNotIn(List<String> values) {
            addCriterion("stand_fh not in", values, "standFh");
            return (Criteria) this;
        }

        public Criteria andStandFhBetween(String value1, String value2) {
            addCriterion("stand_fh between", value1, value2, "standFh");
            return (Criteria) this;
        }

        public Criteria andStandFhNotBetween(String value1, String value2) {
            addCriterion("stand_fh not between", value1, value2, "standFh");
            return (Criteria) this;
        }

        public Criteria andStandAreaIsNull() {
            addCriterion("stand_area is null");
            return (Criteria) this;
        }

        public Criteria andStandAreaIsNotNull() {
            addCriterion("stand_area is not null");
            return (Criteria) this;
        }

        public Criteria andStandAreaEqualTo(String value) {
            addCriterion("stand_area =", value, "standArea");
            return (Criteria) this;
        }

        public Criteria andStandAreaNotEqualTo(String value) {
            addCriterion("stand_area <>", value, "standArea");
            return (Criteria) this;
        }

        public Criteria andStandAreaGreaterThan(String value) {
            addCriterion("stand_area >", value, "standArea");
            return (Criteria) this;
        }

        public Criteria andStandAreaGreaterThanOrEqualTo(String value) {
            addCriterion("stand_area >=", value, "standArea");
            return (Criteria) this;
        }

        public Criteria andStandAreaLessThan(String value) {
            addCriterion("stand_area <", value, "standArea");
            return (Criteria) this;
        }

        public Criteria andStandAreaLessThanOrEqualTo(String value) {
            addCriterion("stand_area <=", value, "standArea");
            return (Criteria) this;
        }

        public Criteria andStandAreaLike(String value) {
            addCriterion("stand_area like", value, "standArea");
            return (Criteria) this;
        }

        public Criteria andStandAreaNotLike(String value) {
            addCriterion("stand_area not like", value, "standArea");
            return (Criteria) this;
        }

        public Criteria andStandAreaIn(List<String> values) {
            addCriterion("stand_area in", values, "standArea");
            return (Criteria) this;
        }

        public Criteria andStandAreaNotIn(List<String> values) {
            addCriterion("stand_area not in", values, "standArea");
            return (Criteria) this;
        }

        public Criteria andStandAreaBetween(String value1, String value2) {
            addCriterion("stand_area between", value1, value2, "standArea");
            return (Criteria) this;
        }

        public Criteria andStandAreaNotBetween(String value1, String value2) {
            addCriterion("stand_area not between", value1, value2, "standArea");
            return (Criteria) this;
        }

        public Criteria andStandBfNumIsNull() {
            addCriterion("stand_bf_num is null");
            return (Criteria) this;
        }

        public Criteria andStandBfNumIsNotNull() {
            addCriterion("stand_bf_num is not null");
            return (Criteria) this;
        }

        public Criteria andStandBfNumEqualTo(String value) {
            addCriterion("stand_bf_num =", value, "standBfNum");
            return (Criteria) this;
        }

        public Criteria andStandBfNumNotEqualTo(String value) {
            addCriterion("stand_bf_num <>", value, "standBfNum");
            return (Criteria) this;
        }

        public Criteria andStandBfNumGreaterThan(String value) {
            addCriterion("stand_bf_num >", value, "standBfNum");
            return (Criteria) this;
        }

        public Criteria andStandBfNumGreaterThanOrEqualTo(String value) {
            addCriterion("stand_bf_num >=", value, "standBfNum");
            return (Criteria) this;
        }

        public Criteria andStandBfNumLessThan(String value) {
            addCriterion("stand_bf_num <", value, "standBfNum");
            return (Criteria) this;
        }

        public Criteria andStandBfNumLessThanOrEqualTo(String value) {
            addCriterion("stand_bf_num <=", value, "standBfNum");
            return (Criteria) this;
        }

        public Criteria andStandBfNumLike(String value) {
            addCriterion("stand_bf_num like", value, "standBfNum");
            return (Criteria) this;
        }

        public Criteria andStandBfNumNotLike(String value) {
            addCriterion("stand_bf_num not like", value, "standBfNum");
            return (Criteria) this;
        }

        public Criteria andStandBfNumIn(List<String> values) {
            addCriterion("stand_bf_num in", values, "standBfNum");
            return (Criteria) this;
        }

        public Criteria andStandBfNumNotIn(List<String> values) {
            addCriterion("stand_bf_num not in", values, "standBfNum");
            return (Criteria) this;
        }

        public Criteria andStandBfNumBetween(String value1, String value2) {
            addCriterion("stand_bf_num between", value1, value2, "standBfNum");
            return (Criteria) this;
        }

        public Criteria andStandBfNumNotBetween(String value1, String value2) {
            addCriterion("stand_bf_num not between", value1, value2, "standBfNum");
            return (Criteria) this;
        }

        public Criteria andXhbLlIsNull() {
            addCriterion("xhb_ll is null");
            return (Criteria) this;
        }

        public Criteria andXhbLlIsNotNull() {
            addCriterion("xhb_ll is not null");
            return (Criteria) this;
        }

        public Criteria andXhbLlEqualTo(String value) {
            addCriterion("xhb_ll =", value, "xhbLl");
            return (Criteria) this;
        }

        public Criteria andXhbLlNotEqualTo(String value) {
            addCriterion("xhb_ll <>", value, "xhbLl");
            return (Criteria) this;
        }

        public Criteria andXhbLlGreaterThan(String value) {
            addCriterion("xhb_ll >", value, "xhbLl");
            return (Criteria) this;
        }

        public Criteria andXhbLlGreaterThanOrEqualTo(String value) {
            addCriterion("xhb_ll >=", value, "xhbLl");
            return (Criteria) this;
        }

        public Criteria andXhbLlLessThan(String value) {
            addCriterion("xhb_ll <", value, "xhbLl");
            return (Criteria) this;
        }

        public Criteria andXhbLlLessThanOrEqualTo(String value) {
            addCriterion("xhb_ll <=", value, "xhbLl");
            return (Criteria) this;
        }

        public Criteria andXhbLlLike(String value) {
            addCriterion("xhb_ll like", value, "xhbLl");
            return (Criteria) this;
        }

        public Criteria andXhbLlNotLike(String value) {
            addCriterion("xhb_ll not like", value, "xhbLl");
            return (Criteria) this;
        }

        public Criteria andXhbLlIn(List<String> values) {
            addCriterion("xhb_ll in", values, "xhbLl");
            return (Criteria) this;
        }

        public Criteria andXhbLlNotIn(List<String> values) {
            addCriterion("xhb_ll not in", values, "xhbLl");
            return (Criteria) this;
        }

        public Criteria andXhbLlBetween(String value1, String value2) {
            addCriterion("xhb_ll between", value1, value2, "xhbLl");
            return (Criteria) this;
        }

        public Criteria andXhbLlNotBetween(String value1, String value2) {
            addCriterion("xhb_ll not between", value1, value2, "xhbLl");
            return (Criteria) this;
        }

        public Criteria andXhbYcIsNull() {
            addCriterion("xhb_yc is null");
            return (Criteria) this;
        }

        public Criteria andXhbYcIsNotNull() {
            addCriterion("xhb_yc is not null");
            return (Criteria) this;
        }

        public Criteria andXhbYcEqualTo(String value) {
            addCriterion("xhb_yc =", value, "xhbYc");
            return (Criteria) this;
        }

        public Criteria andXhbYcNotEqualTo(String value) {
            addCriterion("xhb_yc <>", value, "xhbYc");
            return (Criteria) this;
        }

        public Criteria andXhbYcGreaterThan(String value) {
            addCriterion("xhb_yc >", value, "xhbYc");
            return (Criteria) this;
        }

        public Criteria andXhbYcGreaterThanOrEqualTo(String value) {
            addCriterion("xhb_yc >=", value, "xhbYc");
            return (Criteria) this;
        }

        public Criteria andXhbYcLessThan(String value) {
            addCriterion("xhb_yc <", value, "xhbYc");
            return (Criteria) this;
        }

        public Criteria andXhbYcLessThanOrEqualTo(String value) {
            addCriterion("xhb_yc <=", value, "xhbYc");
            return (Criteria) this;
        }

        public Criteria andXhbYcLike(String value) {
            addCriterion("xhb_yc like", value, "xhbYc");
            return (Criteria) this;
        }

        public Criteria andXhbYcNotLike(String value) {
            addCriterion("xhb_yc not like", value, "xhbYc");
            return (Criteria) this;
        }

        public Criteria andXhbYcIn(List<String> values) {
            addCriterion("xhb_yc in", values, "xhbYc");
            return (Criteria) this;
        }

        public Criteria andXhbYcNotIn(List<String> values) {
            addCriterion("xhb_yc not in", values, "xhbYc");
            return (Criteria) this;
        }

        public Criteria andXhbYcBetween(String value1, String value2) {
            addCriterion("xhb_yc between", value1, value2, "xhbYc");
            return (Criteria) this;
        }

        public Criteria andXhbYcNotBetween(String value1, String value2) {
            addCriterion("xhb_yc not between", value1, value2, "xhbYc");
            return (Criteria) this;
        }

        public Criteria andXhbGlIsNull() {
            addCriterion("xhb_gl is null");
            return (Criteria) this;
        }

        public Criteria andXhbGlIsNotNull() {
            addCriterion("xhb_gl is not null");
            return (Criteria) this;
        }

        public Criteria andXhbGlEqualTo(String value) {
            addCriterion("xhb_gl =", value, "xhbGl");
            return (Criteria) this;
        }

        public Criteria andXhbGlNotEqualTo(String value) {
            addCriterion("xhb_gl <>", value, "xhbGl");
            return (Criteria) this;
        }

        public Criteria andXhbGlGreaterThan(String value) {
            addCriterion("xhb_gl >", value, "xhbGl");
            return (Criteria) this;
        }

        public Criteria andXhbGlGreaterThanOrEqualTo(String value) {
            addCriterion("xhb_gl >=", value, "xhbGl");
            return (Criteria) this;
        }

        public Criteria andXhbGlLessThan(String value) {
            addCriterion("xhb_gl <", value, "xhbGl");
            return (Criteria) this;
        }

        public Criteria andXhbGlLessThanOrEqualTo(String value) {
            addCriterion("xhb_gl <=", value, "xhbGl");
            return (Criteria) this;
        }

        public Criteria andXhbGlLike(String value) {
            addCriterion("xhb_gl like", value, "xhbGl");
            return (Criteria) this;
        }

        public Criteria andXhbGlNotLike(String value) {
            addCriterion("xhb_gl not like", value, "xhbGl");
            return (Criteria) this;
        }

        public Criteria andXhbGlIn(List<String> values) {
            addCriterion("xhb_gl in", values, "xhbGl");
            return (Criteria) this;
        }

        public Criteria andXhbGlNotIn(List<String> values) {
            addCriterion("xhb_gl not in", values, "xhbGl");
            return (Criteria) this;
        }

        public Criteria andXhbGlBetween(String value1, String value2) {
            addCriterion("xhb_gl between", value1, value2, "xhbGl");
            return (Criteria) this;
        }

        public Criteria andXhbGlNotBetween(String value1, String value2) {
            addCriterion("xhb_gl not between", value1, value2, "xhbGl");
            return (Criteria) this;
        }

        public Criteria andXhbNumIsNull() {
            addCriterion("xhb_num is null");
            return (Criteria) this;
        }

        public Criteria andXhbNumIsNotNull() {
            addCriterion("xhb_num is not null");
            return (Criteria) this;
        }

        public Criteria andXhbNumEqualTo(String value) {
            addCriterion("xhb_num =", value, "xhbNum");
            return (Criteria) this;
        }

        public Criteria andXhbNumNotEqualTo(String value) {
            addCriterion("xhb_num <>", value, "xhbNum");
            return (Criteria) this;
        }

        public Criteria andXhbNumGreaterThan(String value) {
            addCriterion("xhb_num >", value, "xhbNum");
            return (Criteria) this;
        }

        public Criteria andXhbNumGreaterThanOrEqualTo(String value) {
            addCriterion("xhb_num >=", value, "xhbNum");
            return (Criteria) this;
        }

        public Criteria andXhbNumLessThan(String value) {
            addCriterion("xhb_num <", value, "xhbNum");
            return (Criteria) this;
        }

        public Criteria andXhbNumLessThanOrEqualTo(String value) {
            addCriterion("xhb_num <=", value, "xhbNum");
            return (Criteria) this;
        }

        public Criteria andXhbNumLike(String value) {
            addCriterion("xhb_num like", value, "xhbNum");
            return (Criteria) this;
        }

        public Criteria andXhbNumNotLike(String value) {
            addCriterion("xhb_num not like", value, "xhbNum");
            return (Criteria) this;
        }

        public Criteria andXhbNumIn(List<String> values) {
            addCriterion("xhb_num in", values, "xhbNum");
            return (Criteria) this;
        }

        public Criteria andXhbNumNotIn(List<String> values) {
            addCriterion("xhb_num not in", values, "xhbNum");
            return (Criteria) this;
        }

        public Criteria andXhbNumBetween(String value1, String value2) {
            addCriterion("xhb_num between", value1, value2, "xhbNum");
            return (Criteria) this;
        }

        public Criteria andXhbNumNotBetween(String value1, String value2) {
            addCriterion("xhb_num not between", value1, value2, "xhbNum");
            return (Criteria) this;
        }

        public Criteria andBsbLlIsNull() {
            addCriterion("bsb_ll is null");
            return (Criteria) this;
        }

        public Criteria andBsbLlIsNotNull() {
            addCriterion("bsb_ll is not null");
            return (Criteria) this;
        }

        public Criteria andBsbLlEqualTo(String value) {
            addCriterion("bsb_ll =", value, "bsbLl");
            return (Criteria) this;
        }

        public Criteria andBsbLlNotEqualTo(String value) {
            addCriterion("bsb_ll <>", value, "bsbLl");
            return (Criteria) this;
        }

        public Criteria andBsbLlGreaterThan(String value) {
            addCriterion("bsb_ll >", value, "bsbLl");
            return (Criteria) this;
        }

        public Criteria andBsbLlGreaterThanOrEqualTo(String value) {
            addCriterion("bsb_ll >=", value, "bsbLl");
            return (Criteria) this;
        }

        public Criteria andBsbLlLessThan(String value) {
            addCriterion("bsb_ll <", value, "bsbLl");
            return (Criteria) this;
        }

        public Criteria andBsbLlLessThanOrEqualTo(String value) {
            addCriterion("bsb_ll <=", value, "bsbLl");
            return (Criteria) this;
        }

        public Criteria andBsbLlLike(String value) {
            addCriterion("bsb_ll like", value, "bsbLl");
            return (Criteria) this;
        }

        public Criteria andBsbLlNotLike(String value) {
            addCriterion("bsb_ll not like", value, "bsbLl");
            return (Criteria) this;
        }

        public Criteria andBsbLlIn(List<String> values) {
            addCriterion("bsb_ll in", values, "bsbLl");
            return (Criteria) this;
        }

        public Criteria andBsbLlNotIn(List<String> values) {
            addCriterion("bsb_ll not in", values, "bsbLl");
            return (Criteria) this;
        }

        public Criteria andBsbLlBetween(String value1, String value2) {
            addCriterion("bsb_ll between", value1, value2, "bsbLl");
            return (Criteria) this;
        }

        public Criteria andBsbLlNotBetween(String value1, String value2) {
            addCriterion("bsb_ll not between", value1, value2, "bsbLl");
            return (Criteria) this;
        }

        public Criteria andBsbYcIsNull() {
            addCriterion("bsb_yc is null");
            return (Criteria) this;
        }

        public Criteria andBsbYcIsNotNull() {
            addCriterion("bsb_yc is not null");
            return (Criteria) this;
        }

        public Criteria andBsbYcEqualTo(String value) {
            addCriterion("bsb_yc =", value, "bsbYc");
            return (Criteria) this;
        }

        public Criteria andBsbYcNotEqualTo(String value) {
            addCriterion("bsb_yc <>", value, "bsbYc");
            return (Criteria) this;
        }

        public Criteria andBsbYcGreaterThan(String value) {
            addCriterion("bsb_yc >", value, "bsbYc");
            return (Criteria) this;
        }

        public Criteria andBsbYcGreaterThanOrEqualTo(String value) {
            addCriterion("bsb_yc >=", value, "bsbYc");
            return (Criteria) this;
        }

        public Criteria andBsbYcLessThan(String value) {
            addCriterion("bsb_yc <", value, "bsbYc");
            return (Criteria) this;
        }

        public Criteria andBsbYcLessThanOrEqualTo(String value) {
            addCriterion("bsb_yc <=", value, "bsbYc");
            return (Criteria) this;
        }

        public Criteria andBsbYcLike(String value) {
            addCriterion("bsb_yc like", value, "bsbYc");
            return (Criteria) this;
        }

        public Criteria andBsbYcNotLike(String value) {
            addCriterion("bsb_yc not like", value, "bsbYc");
            return (Criteria) this;
        }

        public Criteria andBsbYcIn(List<String> values) {
            addCriterion("bsb_yc in", values, "bsbYc");
            return (Criteria) this;
        }

        public Criteria andBsbYcNotIn(List<String> values) {
            addCriterion("bsb_yc not in", values, "bsbYc");
            return (Criteria) this;
        }

        public Criteria andBsbYcBetween(String value1, String value2) {
            addCriterion("bsb_yc between", value1, value2, "bsbYc");
            return (Criteria) this;
        }

        public Criteria andBsbYcNotBetween(String value1, String value2) {
            addCriterion("bsb_yc not between", value1, value2, "bsbYc");
            return (Criteria) this;
        }

        public Criteria andBsbGlIsNull() {
            addCriterion("bsb_gl is null");
            return (Criteria) this;
        }

        public Criteria andBsbGlIsNotNull() {
            addCriterion("bsb_gl is not null");
            return (Criteria) this;
        }

        public Criteria andBsbGlEqualTo(String value) {
            addCriterion("bsb_gl =", value, "bsbGl");
            return (Criteria) this;
        }

        public Criteria andBsbGlNotEqualTo(String value) {
            addCriterion("bsb_gl <>", value, "bsbGl");
            return (Criteria) this;
        }

        public Criteria andBsbGlGreaterThan(String value) {
            addCriterion("bsb_gl >", value, "bsbGl");
            return (Criteria) this;
        }

        public Criteria andBsbGlGreaterThanOrEqualTo(String value) {
            addCriterion("bsb_gl >=", value, "bsbGl");
            return (Criteria) this;
        }

        public Criteria andBsbGlLessThan(String value) {
            addCriterion("bsb_gl <", value, "bsbGl");
            return (Criteria) this;
        }

        public Criteria andBsbGlLessThanOrEqualTo(String value) {
            addCriterion("bsb_gl <=", value, "bsbGl");
            return (Criteria) this;
        }

        public Criteria andBsbGlLike(String value) {
            addCriterion("bsb_gl like", value, "bsbGl");
            return (Criteria) this;
        }

        public Criteria andBsbGlNotLike(String value) {
            addCriterion("bsb_gl not like", value, "bsbGl");
            return (Criteria) this;
        }

        public Criteria andBsbGlIn(List<String> values) {
            addCriterion("bsb_gl in", values, "bsbGl");
            return (Criteria) this;
        }

        public Criteria andBsbGlNotIn(List<String> values) {
            addCriterion("bsb_gl not in", values, "bsbGl");
            return (Criteria) this;
        }

        public Criteria andBsbGlBetween(String value1, String value2) {
            addCriterion("bsb_gl between", value1, value2, "bsbGl");
            return (Criteria) this;
        }

        public Criteria andBsbGlNotBetween(String value1, String value2) {
            addCriterion("bsb_gl not between", value1, value2, "bsbGl");
            return (Criteria) this;
        }

        public Criteria andBsbNumIsNull() {
            addCriterion("bsb_num is null");
            return (Criteria) this;
        }

        public Criteria andBsbNumIsNotNull() {
            addCriterion("bsb_num is not null");
            return (Criteria) this;
        }

        public Criteria andBsbNumEqualTo(String value) {
            addCriterion("bsb_num =", value, "bsbNum");
            return (Criteria) this;
        }

        public Criteria andBsbNumNotEqualTo(String value) {
            addCriterion("bsb_num <>", value, "bsbNum");
            return (Criteria) this;
        }

        public Criteria andBsbNumGreaterThan(String value) {
            addCriterion("bsb_num >", value, "bsbNum");
            return (Criteria) this;
        }

        public Criteria andBsbNumGreaterThanOrEqualTo(String value) {
            addCriterion("bsb_num >=", value, "bsbNum");
            return (Criteria) this;
        }

        public Criteria andBsbNumLessThan(String value) {
            addCriterion("bsb_num <", value, "bsbNum");
            return (Criteria) this;
        }

        public Criteria andBsbNumLessThanOrEqualTo(String value) {
            addCriterion("bsb_num <=", value, "bsbNum");
            return (Criteria) this;
        }

        public Criteria andBsbNumLike(String value) {
            addCriterion("bsb_num like", value, "bsbNum");
            return (Criteria) this;
        }

        public Criteria andBsbNumNotLike(String value) {
            addCriterion("bsb_num not like", value, "bsbNum");
            return (Criteria) this;
        }

        public Criteria andBsbNumIn(List<String> values) {
            addCriterion("bsb_num in", values, "bsbNum");
            return (Criteria) this;
        }

        public Criteria andBsbNumNotIn(List<String> values) {
            addCriterion("bsb_num not in", values, "bsbNum");
            return (Criteria) this;
        }

        public Criteria andBsbNumBetween(String value1, String value2) {
            addCriterion("bsb_num between", value1, value2, "bsbNum");
            return (Criteria) this;
        }

        public Criteria andBsbNumNotBetween(String value1, String value2) {
            addCriterion("bsb_num not between", value1, value2, "bsbNum");
            return (Criteria) this;
        }

        public Criteria andHsjybLlIsNull() {
            addCriterion("hsjyb_ll is null");
            return (Criteria) this;
        }

        public Criteria andHsjybLlIsNotNull() {
            addCriterion("hsjyb_ll is not null");
            return (Criteria) this;
        }

        public Criteria andHsjybLlEqualTo(String value) {
            addCriterion("hsjyb_ll =", value, "hsjybLl");
            return (Criteria) this;
        }

        public Criteria andHsjybLlNotEqualTo(String value) {
            addCriterion("hsjyb_ll <>", value, "hsjybLl");
            return (Criteria) this;
        }

        public Criteria andHsjybLlGreaterThan(String value) {
            addCriterion("hsjyb_ll >", value, "hsjybLl");
            return (Criteria) this;
        }

        public Criteria andHsjybLlGreaterThanOrEqualTo(String value) {
            addCriterion("hsjyb_ll >=", value, "hsjybLl");
            return (Criteria) this;
        }

        public Criteria andHsjybLlLessThan(String value) {
            addCriterion("hsjyb_ll <", value, "hsjybLl");
            return (Criteria) this;
        }

        public Criteria andHsjybLlLessThanOrEqualTo(String value) {
            addCriterion("hsjyb_ll <=", value, "hsjybLl");
            return (Criteria) this;
        }

        public Criteria andHsjybLlLike(String value) {
            addCriterion("hsjyb_ll like", value, "hsjybLl");
            return (Criteria) this;
        }

        public Criteria andHsjybLlNotLike(String value) {
            addCriterion("hsjyb_ll not like", value, "hsjybLl");
            return (Criteria) this;
        }

        public Criteria andHsjybLlIn(List<String> values) {
            addCriterion("hsjyb_ll in", values, "hsjybLl");
            return (Criteria) this;
        }

        public Criteria andHsjybLlNotIn(List<String> values) {
            addCriterion("hsjyb_ll not in", values, "hsjybLl");
            return (Criteria) this;
        }

        public Criteria andHsjybLlBetween(String value1, String value2) {
            addCriterion("hsjyb_ll between", value1, value2, "hsjybLl");
            return (Criteria) this;
        }

        public Criteria andHsjybLlNotBetween(String value1, String value2) {
            addCriterion("hsjyb_ll not between", value1, value2, "hsjybLl");
            return (Criteria) this;
        }

        public Criteria andHsjybYcIsNull() {
            addCriterion("hsjyb_yc is null");
            return (Criteria) this;
        }

        public Criteria andHsjybYcIsNotNull() {
            addCriterion("hsjyb_yc is not null");
            return (Criteria) this;
        }

        public Criteria andHsjybYcEqualTo(String value) {
            addCriterion("hsjyb_yc =", value, "hsjybYc");
            return (Criteria) this;
        }

        public Criteria andHsjybYcNotEqualTo(String value) {
            addCriterion("hsjyb_yc <>", value, "hsjybYc");
            return (Criteria) this;
        }

        public Criteria andHsjybYcGreaterThan(String value) {
            addCriterion("hsjyb_yc >", value, "hsjybYc");
            return (Criteria) this;
        }

        public Criteria andHsjybYcGreaterThanOrEqualTo(String value) {
            addCriterion("hsjyb_yc >=", value, "hsjybYc");
            return (Criteria) this;
        }

        public Criteria andHsjybYcLessThan(String value) {
            addCriterion("hsjyb_yc <", value, "hsjybYc");
            return (Criteria) this;
        }

        public Criteria andHsjybYcLessThanOrEqualTo(String value) {
            addCriterion("hsjyb_yc <=", value, "hsjybYc");
            return (Criteria) this;
        }

        public Criteria andHsjybYcLike(String value) {
            addCriterion("hsjyb_yc like", value, "hsjybYc");
            return (Criteria) this;
        }

        public Criteria andHsjybYcNotLike(String value) {
            addCriterion("hsjyb_yc not like", value, "hsjybYc");
            return (Criteria) this;
        }

        public Criteria andHsjybYcIn(List<String> values) {
            addCriterion("hsjyb_yc in", values, "hsjybYc");
            return (Criteria) this;
        }

        public Criteria andHsjybYcNotIn(List<String> values) {
            addCriterion("hsjyb_yc not in", values, "hsjybYc");
            return (Criteria) this;
        }

        public Criteria andHsjybYcBetween(String value1, String value2) {
            addCriterion("hsjyb_yc between", value1, value2, "hsjybYc");
            return (Criteria) this;
        }

        public Criteria andHsjybYcNotBetween(String value1, String value2) {
            addCriterion("hsjyb_yc not between", value1, value2, "hsjybYc");
            return (Criteria) this;
        }

        public Criteria andHsjybGlIsNull() {
            addCriterion("hsjyb_gl is null");
            return (Criteria) this;
        }

        public Criteria andHsjybGlIsNotNull() {
            addCriterion("hsjyb_gl is not null");
            return (Criteria) this;
        }

        public Criteria andHsjybGlEqualTo(String value) {
            addCriterion("hsjyb_gl =", value, "hsjybGl");
            return (Criteria) this;
        }

        public Criteria andHsjybGlNotEqualTo(String value) {
            addCriterion("hsjyb_gl <>", value, "hsjybGl");
            return (Criteria) this;
        }

        public Criteria andHsjybGlGreaterThan(String value) {
            addCriterion("hsjyb_gl >", value, "hsjybGl");
            return (Criteria) this;
        }

        public Criteria andHsjybGlGreaterThanOrEqualTo(String value) {
            addCriterion("hsjyb_gl >=", value, "hsjybGl");
            return (Criteria) this;
        }

        public Criteria andHsjybGlLessThan(String value) {
            addCriterion("hsjyb_gl <", value, "hsjybGl");
            return (Criteria) this;
        }

        public Criteria andHsjybGlLessThanOrEqualTo(String value) {
            addCriterion("hsjyb_gl <=", value, "hsjybGl");
            return (Criteria) this;
        }

        public Criteria andHsjybGlLike(String value) {
            addCriterion("hsjyb_gl like", value, "hsjybGl");
            return (Criteria) this;
        }

        public Criteria andHsjybGlNotLike(String value) {
            addCriterion("hsjyb_gl not like", value, "hsjybGl");
            return (Criteria) this;
        }

        public Criteria andHsjybGlIn(List<String> values) {
            addCriterion("hsjyb_gl in", values, "hsjybGl");
            return (Criteria) this;
        }

        public Criteria andHsjybGlNotIn(List<String> values) {
            addCriterion("hsjyb_gl not in", values, "hsjybGl");
            return (Criteria) this;
        }

        public Criteria andHsjybGlBetween(String value1, String value2) {
            addCriterion("hsjyb_gl between", value1, value2, "hsjybGl");
            return (Criteria) this;
        }

        public Criteria andHsjybGlNotBetween(String value1, String value2) {
            addCriterion("hsjyb_gl not between", value1, value2, "hsjybGl");
            return (Criteria) this;
        }

        public Criteria andHsjybNumIsNull() {
            addCriterion("hsjyb_num is null");
            return (Criteria) this;
        }

        public Criteria andHsjybNumIsNotNull() {
            addCriterion("hsjyb_num is not null");
            return (Criteria) this;
        }

        public Criteria andHsjybNumEqualTo(String value) {
            addCriterion("hsjyb_num =", value, "hsjybNum");
            return (Criteria) this;
        }

        public Criteria andHsjybNumNotEqualTo(String value) {
            addCriterion("hsjyb_num <>", value, "hsjybNum");
            return (Criteria) this;
        }

        public Criteria andHsjybNumGreaterThan(String value) {
            addCriterion("hsjyb_num >", value, "hsjybNum");
            return (Criteria) this;
        }

        public Criteria andHsjybNumGreaterThanOrEqualTo(String value) {
            addCriterion("hsjyb_num >=", value, "hsjybNum");
            return (Criteria) this;
        }

        public Criteria andHsjybNumLessThan(String value) {
            addCriterion("hsjyb_num <", value, "hsjybNum");
            return (Criteria) this;
        }

        public Criteria andHsjybNumLessThanOrEqualTo(String value) {
            addCriterion("hsjyb_num <=", value, "hsjybNum");
            return (Criteria) this;
        }

        public Criteria andHsjybNumLike(String value) {
            addCriterion("hsjyb_num like", value, "hsjybNum");
            return (Criteria) this;
        }

        public Criteria andHsjybNumNotLike(String value) {
            addCriterion("hsjyb_num not like", value, "hsjybNum");
            return (Criteria) this;
        }

        public Criteria andHsjybNumIn(List<String> values) {
            addCriterion("hsjyb_num in", values, "hsjybNum");
            return (Criteria) this;
        }

        public Criteria andHsjybNumNotIn(List<String> values) {
            addCriterion("hsjyb_num not in", values, "hsjybNum");
            return (Criteria) this;
        }

        public Criteria andHsjybNumBetween(String value1, String value2) {
            addCriterion("hsjyb_num between", value1, value2, "hsjybNum");
            return (Criteria) this;
        }

        public Criteria andHsjybNumNotBetween(String value1, String value2) {
            addCriterion("hsjyb_num not between", value1, value2, "hsjybNum");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table data_stand_basic
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table data_stand_basic
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }


    ////*******自定义开始********/
    //***********自定义结束****////
}
