package com.xhkj.server.energy.dao.mybatis.vo;

public class StandBasicDataKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_stand_basic.COMPANY_ID
     *
     * @mbg.generated
     */
    private Integer companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_stand_basic.STAND_ID
     *
     * @mbg.generated
     */
    private String standId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_stand_basic.COMPANY_ID
     *
     * @return the value of data_stand_basic.COMPANY_ID
     *
     * @mbg.generated
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_stand_basic.COMPANY_ID
     *
     * @param companyId the value for data_stand_basic.COMPANY_ID
     *
     * @mbg.generated
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_stand_basic.STAND_ID
     *
     * @return the value of data_stand_basic.STAND_ID
     *
     * @mbg.generated
     */
    public String getStandId() {
        return standId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_stand_basic.STAND_ID
     *
     * @param standId the value for data_stand_basic.STAND_ID
     *
     * @mbg.generated
     */
    public void setStandId(String standId) {
        this.standId = standId;
    }


    ////*******自定义开始********/
    //***********自定义结束****////
}
