package com.xhkj.server.energy.dao.mybatis.vo;

public class StandBasicData extends StandBasicDataKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_stand_basic.stand_name
     *
     * @mbg.generated
     */
    private String standName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_stand_basic.station_id
     *
     * @mbg.generated
     */
    private String stationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_stand_basic.total_area
     *
     * @mbg.generated
     */
    private Float totalArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_stand_basic.stand_fh
     *
     * @mbg.generated
     */
    private String standFh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_stand_basic.stand_area
     *
     * @mbg.generated
     */
    private String standArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_stand_basic.stand_bf_num
     *
     * @mbg.generated
     */
    private String standBfNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_stand_basic.xhb_ll
     *
     * @mbg.generated
     */
    private String xhbLl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_stand_basic.xhb_yc
     *
     * @mbg.generated
     */
    private String xhbYc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_stand_basic.xhb_gl
     *
     * @mbg.generated
     */
    private String xhbGl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_stand_basic.xhb_num
     *
     * @mbg.generated
     */
    private String xhbNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_stand_basic.bsb_ll
     *
     * @mbg.generated
     */
    private String bsbLl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_stand_basic.bsb_yc
     *
     * @mbg.generated
     */
    private String bsbYc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_stand_basic.bsb_gl
     *
     * @mbg.generated
     */
    private String bsbGl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_stand_basic.bsb_num
     *
     * @mbg.generated
     */
    private String bsbNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_stand_basic.hsjyb_ll
     *
     * @mbg.generated
     */
    private String hsjybLl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_stand_basic.hsjyb_yc
     *
     * @mbg.generated
     */
    private String hsjybYc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_stand_basic.hsjyb_gl
     *
     * @mbg.generated
     */
    private String hsjybGl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_stand_basic.hsjyb_num
     *
     * @mbg.generated
     */
    private String hsjybNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_stand_basic.stand_name
     *
     * @return the value of data_stand_basic.stand_name
     *
     * @mbg.generated
     */
    public String getStandName() {
        return standName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_stand_basic.stand_name
     *
     * @param standName the value for data_stand_basic.stand_name
     *
     * @mbg.generated
     */
    public void setStandName(String standName) {
        this.standName = standName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_stand_basic.station_id
     *
     * @return the value of data_stand_basic.station_id
     *
     * @mbg.generated
     */
    public String getStationId() {
        return stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_stand_basic.station_id
     *
     * @param stationId the value for data_stand_basic.station_id
     *
     * @mbg.generated
     */
    public void setStationId(String stationId) {
        this.stationId = stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_stand_basic.total_area
     *
     * @return the value of data_stand_basic.total_area
     *
     * @mbg.generated
     */
    public Float getTotalArea() {
        return totalArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_stand_basic.total_area
     *
     * @param totalArea the value for data_stand_basic.total_area
     *
     * @mbg.generated
     */
    public void setTotalArea(Float totalArea) {
        this.totalArea = totalArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_stand_basic.stand_fh
     *
     * @return the value of data_stand_basic.stand_fh
     *
     * @mbg.generated
     */
    public String getStandFh() {
        return standFh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_stand_basic.stand_fh
     *
     * @param standFh the value for data_stand_basic.stand_fh
     *
     * @mbg.generated
     */
    public void setStandFh(String standFh) {
        this.standFh = standFh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_stand_basic.stand_area
     *
     * @return the value of data_stand_basic.stand_area
     *
     * @mbg.generated
     */
    public String getStandArea() {
        return standArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_stand_basic.stand_area
     *
     * @param standArea the value for data_stand_basic.stand_area
     *
     * @mbg.generated
     */
    public void setStandArea(String standArea) {
        this.standArea = standArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_stand_basic.stand_bf_num
     *
     * @return the value of data_stand_basic.stand_bf_num
     *
     * @mbg.generated
     */
    public String getStandBfNum() {
        return standBfNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_stand_basic.stand_bf_num
     *
     * @param standBfNum the value for data_stand_basic.stand_bf_num
     *
     * @mbg.generated
     */
    public void setStandBfNum(String standBfNum) {
        this.standBfNum = standBfNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_stand_basic.xhb_ll
     *
     * @return the value of data_stand_basic.xhb_ll
     *
     * @mbg.generated
     */
    public String getXhbLl() {
        return xhbLl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_stand_basic.xhb_ll
     *
     * @param xhbLl the value for data_stand_basic.xhb_ll
     *
     * @mbg.generated
     */
    public void setXhbLl(String xhbLl) {
        this.xhbLl = xhbLl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_stand_basic.xhb_yc
     *
     * @return the value of data_stand_basic.xhb_yc
     *
     * @mbg.generated
     */
    public String getXhbYc() {
        return xhbYc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_stand_basic.xhb_yc
     *
     * @param xhbYc the value for data_stand_basic.xhb_yc
     *
     * @mbg.generated
     */
    public void setXhbYc(String xhbYc) {
        this.xhbYc = xhbYc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_stand_basic.xhb_gl
     *
     * @return the value of data_stand_basic.xhb_gl
     *
     * @mbg.generated
     */
    public String getXhbGl() {
        return xhbGl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_stand_basic.xhb_gl
     *
     * @param xhbGl the value for data_stand_basic.xhb_gl
     *
     * @mbg.generated
     */
    public void setXhbGl(String xhbGl) {
        this.xhbGl = xhbGl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_stand_basic.xhb_num
     *
     * @return the value of data_stand_basic.xhb_num
     *
     * @mbg.generated
     */
    public String getXhbNum() {
        return xhbNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_stand_basic.xhb_num
     *
     * @param xhbNum the value for data_stand_basic.xhb_num
     *
     * @mbg.generated
     */
    public void setXhbNum(String xhbNum) {
        this.xhbNum = xhbNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_stand_basic.bsb_ll
     *
     * @return the value of data_stand_basic.bsb_ll
     *
     * @mbg.generated
     */
    public String getBsbLl() {
        return bsbLl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_stand_basic.bsb_ll
     *
     * @param bsbLl the value for data_stand_basic.bsb_ll
     *
     * @mbg.generated
     */
    public void setBsbLl(String bsbLl) {
        this.bsbLl = bsbLl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_stand_basic.bsb_yc
     *
     * @return the value of data_stand_basic.bsb_yc
     *
     * @mbg.generated
     */
    public String getBsbYc() {
        return bsbYc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_stand_basic.bsb_yc
     *
     * @param bsbYc the value for data_stand_basic.bsb_yc
     *
     * @mbg.generated
     */
    public void setBsbYc(String bsbYc) {
        this.bsbYc = bsbYc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_stand_basic.bsb_gl
     *
     * @return the value of data_stand_basic.bsb_gl
     *
     * @mbg.generated
     */
    public String getBsbGl() {
        return bsbGl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_stand_basic.bsb_gl
     *
     * @param bsbGl the value for data_stand_basic.bsb_gl
     *
     * @mbg.generated
     */
    public void setBsbGl(String bsbGl) {
        this.bsbGl = bsbGl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_stand_basic.bsb_num
     *
     * @return the value of data_stand_basic.bsb_num
     *
     * @mbg.generated
     */
    public String getBsbNum() {
        return bsbNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_stand_basic.bsb_num
     *
     * @param bsbNum the value for data_stand_basic.bsb_num
     *
     * @mbg.generated
     */
    public void setBsbNum(String bsbNum) {
        this.bsbNum = bsbNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_stand_basic.hsjyb_ll
     *
     * @return the value of data_stand_basic.hsjyb_ll
     *
     * @mbg.generated
     */
    public String getHsjybLl() {
        return hsjybLl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_stand_basic.hsjyb_ll
     *
     * @param hsjybLl the value for data_stand_basic.hsjyb_ll
     *
     * @mbg.generated
     */
    public void setHsjybLl(String hsjybLl) {
        this.hsjybLl = hsjybLl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_stand_basic.hsjyb_yc
     *
     * @return the value of data_stand_basic.hsjyb_yc
     *
     * @mbg.generated
     */
    public String getHsjybYc() {
        return hsjybYc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_stand_basic.hsjyb_yc
     *
     * @param hsjybYc the value for data_stand_basic.hsjyb_yc
     *
     * @mbg.generated
     */
    public void setHsjybYc(String hsjybYc) {
        this.hsjybYc = hsjybYc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_stand_basic.hsjyb_gl
     *
     * @return the value of data_stand_basic.hsjyb_gl
     *
     * @mbg.generated
     */
    public String getHsjybGl() {
        return hsjybGl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_stand_basic.hsjyb_gl
     *
     * @param hsjybGl the value for data_stand_basic.hsjyb_gl
     *
     * @mbg.generated
     */
    public void setHsjybGl(String hsjybGl) {
        this.hsjybGl = hsjybGl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_stand_basic.hsjyb_num
     *
     * @return the value of data_stand_basic.hsjyb_num
     *
     * @mbg.generated
     */
    public String getHsjybNum() {
        return hsjybNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_stand_basic.hsjyb_num
     *
     * @param hsjybNum the value for data_stand_basic.hsjyb_num
     *
     * @mbg.generated
     */
    public void setHsjybNum(String hsjybNum) {
        this.hsjybNum = hsjybNum;
    }


    ////*******自定义开始********/
    //***********自定义结束****////
}
