package com.xhkj.server.energy.dao.mybatis.vo;

public class TecolCurveCulData extends TecolCurveCulDataKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_tecol_curve_cul.STAND_NAME
     *
     * @mbg.generated
     */
    private String standName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_tecol_curve_cul.TE1_cul
     *
     * @mbg.generated
     */
    private Float te1Cul;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_tecol_curve_cul.TE2_cul
     *
     * @mbg.generated
     */
    private Float te2Cul;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_tecol_curve_cul.TE3_cul
     *
     * @mbg.generated
     */
    private Float te3Cul;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_tecol_curve_cul.TE4_cul
     *
     * @mbg.generated
     */
    private Float te4Cul;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_tecol_curve_cul.STAND_NAME
     *
     * @return the value of data_tecol_curve_cul.STAND_NAME
     *
     * @mbg.generated
     */
    public String getStandName() {
        return standName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_tecol_curve_cul.STAND_NAME
     *
     * @param standName the value for data_tecol_curve_cul.STAND_NAME
     *
     * @mbg.generated
     */
    public void setStandName(String standName) {
        this.standName = standName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_tecol_curve_cul.TE1_cul
     *
     * @return the value of data_tecol_curve_cul.TE1_cul
     *
     * @mbg.generated
     */
    public Float getTe1Cul() {
        return te1Cul;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_tecol_curve_cul.TE1_cul
     *
     * @param te1Cul the value for data_tecol_curve_cul.TE1_cul
     *
     * @mbg.generated
     */
    public void setTe1Cul(Float te1Cul) {
        this.te1Cul = te1Cul;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_tecol_curve_cul.TE2_cul
     *
     * @return the value of data_tecol_curve_cul.TE2_cul
     *
     * @mbg.generated
     */
    public Float getTe2Cul() {
        return te2Cul;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_tecol_curve_cul.TE2_cul
     *
     * @param te2Cul the value for data_tecol_curve_cul.TE2_cul
     *
     * @mbg.generated
     */
    public void setTe2Cul(Float te2Cul) {
        this.te2Cul = te2Cul;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_tecol_curve_cul.TE3_cul
     *
     * @return the value of data_tecol_curve_cul.TE3_cul
     *
     * @mbg.generated
     */
    public Float getTe3Cul() {
        return te3Cul;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_tecol_curve_cul.TE3_cul
     *
     * @param te3Cul the value for data_tecol_curve_cul.TE3_cul
     *
     * @mbg.generated
     */
    public void setTe3Cul(Float te3Cul) {
        this.te3Cul = te3Cul;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_tecol_curve_cul.TE4_cul
     *
     * @return the value of data_tecol_curve_cul.TE4_cul
     *
     * @mbg.generated
     */
    public Float getTe4Cul() {
        return te4Cul;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_tecol_curve_cul.TE4_cul
     *
     * @param te4Cul the value for data_tecol_curve_cul.TE4_cul
     *
     * @mbg.generated
     */
    public void setTe4Cul(Float te4Cul) {
        this.te4Cul = te4Cul;
    }


    ////*******自定义开始********/
    //***********自定义结束****////
}
