package com.xhkj.server.energy.dao.mybatis.vo;

import com.xhkj.server.energy.entity.BaseEntity;

public class Valve extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_valve.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_valve.batch_number
     *
     * @mbg.generated
     */
    private Integer batchNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_valve.project_id
     *
     * @mbg.generated
     */
    private String projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_valve.append
     *
     * @mbg.generated
     */
    private String append;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_valve.online
     *
     * @mbg.generated
     */
    private Boolean online;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_valve.open_ctl
     *
     * @mbg.generated
     */
    private Integer openCtl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_valve.open
     *
     * @mbg.generated
     */
    private Integer open;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_valve.temp_back
     *
     * @mbg.generated
     */
    private Integer tempBack;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_valve.temp_home
     *
     * @mbg.generated
     */
    private Integer tempHome;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_valve.dtuId
     *
     * @mbg.generated
     */
    private String dtuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_valve.dn
     *
     * @mbg.generated
     */
    private String dn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_valve.id
     *
     * @return the value of data_valve.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_valve.id
     *
     * @param id the value for data_valve.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_valve.batch_number
     *
     * @return the value of data_valve.batch_number
     *
     * @mbg.generated
     */
    public Integer getBatchNumber() {
        return batchNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_valve.batch_number
     *
     * @param batchNumber the value for data_valve.batch_number
     *
     * @mbg.generated
     */
    public void setBatchNumber(Integer batchNumber) {
        this.batchNumber = batchNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_valve.project_id
     *
     * @return the value of data_valve.project_id
     *
     * @mbg.generated
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_valve.project_id
     *
     * @param projectId the value for data_valve.project_id
     *
     * @mbg.generated
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_valve.append
     *
     * @return the value of data_valve.append
     *
     * @mbg.generated
     */
    public String getAppend() {
        return append;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_valve.append
     *
     * @param append the value for data_valve.append
     *
     * @mbg.generated
     */
    public void setAppend(String append) {
        this.append = append;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_valve.online
     *
     * @return the value of data_valve.online
     *
     * @mbg.generated
     */
    public Boolean getOnline() {
        return online;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_valve.online
     *
     * @param online the value for data_valve.online
     *
     * @mbg.generated
     */
    public void setOnline(Boolean online) {
        this.online = online;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_valve.open_ctl
     *
     * @return the value of data_valve.open_ctl
     *
     * @mbg.generated
     */
    public Integer getOpenCtl() {
        return openCtl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_valve.open_ctl
     *
     * @param openCtl the value for data_valve.open_ctl
     *
     * @mbg.generated
     */
    public void setOpenCtl(Integer openCtl) {
        this.openCtl = openCtl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_valve.open
     *
     * @return the value of data_valve.open
     *
     * @mbg.generated
     */
    public Integer getOpen() {
        return open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_valve.open
     *
     * @param open the value for data_valve.open
     *
     * @mbg.generated
     */
    public void setOpen(Integer open) {
        this.open = open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_valve.temp_back
     *
     * @return the value of data_valve.temp_back
     *
     * @mbg.generated
     */
    public Integer getTempBack() {
        return tempBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_valve.temp_back
     *
     * @param tempBack the value for data_valve.temp_back
     *
     * @mbg.generated
     */
    public void setTempBack(Integer tempBack) {
        this.tempBack = tempBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_valve.temp_home
     *
     * @return the value of data_valve.temp_home
     *
     * @mbg.generated
     */
    public Integer getTempHome() {
        return tempHome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_valve.temp_home
     *
     * @param tempHome the value for data_valve.temp_home
     *
     * @mbg.generated
     */
    public void setTempHome(Integer tempHome) {
        this.tempHome = tempHome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_valve.dtuId
     *
     * @return the value of data_valve.dtuId
     *
     * @mbg.generated
     */
    public String getDtuid() {
        return dtuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_valve.dtuId
     *
     * @param dtuid the value for data_valve.dtuId
     *
     * @mbg.generated
     */
    public void setDtuid(String dtuid) {
        this.dtuid = dtuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_valve.dn
     *
     * @return the value of data_valve.dn
     *
     * @mbg.generated
     */
    public String getDn() {
        return dn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_valve.dn
     *
     * @param dn the value for data_valve.dn
     *
     * @mbg.generated
     */
    public void setDn(String dn) {
        this.dn = dn;
    }


    ////*******自定义开始********/
    //***********自定义结束****////
}
