package com.xhkj.server.energy.dao.mybatis.vo;

public class ValveCompany {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_valve_company.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_valve_company.company_id
     *
     * @mbg.generated
     */
    private Integer companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_valve_company.project_id
     *
     * @mbg.generated
     */
    private String projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_valve_company.project_name
     *
     * @mbg.generated
     */
    private String projectName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_valve_company.id
     *
     * @return the value of data_valve_company.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_valve_company.id
     *
     * @param id the value for data_valve_company.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_valve_company.company_id
     *
     * @return the value of data_valve_company.company_id
     *
     * @mbg.generated
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_valve_company.company_id
     *
     * @param companyId the value for data_valve_company.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_valve_company.project_id
     *
     * @return the value of data_valve_company.project_id
     *
     * @mbg.generated
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_valve_company.project_id
     *
     * @param projectId the value for data_valve_company.project_id
     *
     * @mbg.generated
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_valve_company.project_name
     *
     * @return the value of data_valve_company.project_name
     *
     * @mbg.generated
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_valve_company.project_name
     *
     * @param projectName the value for data_valve_company.project_name
     *
     * @mbg.generated
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }


    ////*******自定义开始********/
    //***********自定义结束****////
}
