package com.xhkj.server.energy.dao.mybatis.vo;

public class WaterTemperatureData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_water_temperature.temperature
     *
     * @mbg.generated
     */
    private Short temperature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_water_temperature.TE1
     *
     * @mbg.generated
     */
    private Float te1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_water_temperature.TE2
     *
     * @mbg.generated
     */
    private Float te2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_water_temperature.TE3
     *
     * @mbg.generated
     */
    private Float te3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_water_temperature.TE4
     *
     * @mbg.generated
     */
    private Float te4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_water_temperature.TAG
     *
     * @mbg.generated
     */
    private Boolean tag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_water_temperature.temperature
     *
     * @return the value of data_water_temperature.temperature
     *
     * @mbg.generated
     */
    public Short getTemperature() {
        return temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_water_temperature.temperature
     *
     * @param temperature the value for data_water_temperature.temperature
     *
     * @mbg.generated
     */
    public void setTemperature(Short temperature) {
        this.temperature = temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_water_temperature.TE1
     *
     * @return the value of data_water_temperature.TE1
     *
     * @mbg.generated
     */
    public Float getTe1() {
        return te1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_water_temperature.TE1
     *
     * @param te1 the value for data_water_temperature.TE1
     *
     * @mbg.generated
     */
    public void setTe1(Float te1) {
        this.te1 = te1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_water_temperature.TE2
     *
     * @return the value of data_water_temperature.TE2
     *
     * @mbg.generated
     */
    public Float getTe2() {
        return te2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_water_temperature.TE2
     *
     * @param te2 the value for data_water_temperature.TE2
     *
     * @mbg.generated
     */
    public void setTe2(Float te2) {
        this.te2 = te2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_water_temperature.TE3
     *
     * @return the value of data_water_temperature.TE3
     *
     * @mbg.generated
     */
    public Float getTe3() {
        return te3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_water_temperature.TE3
     *
     * @param te3 the value for data_water_temperature.TE3
     *
     * @mbg.generated
     */
    public void setTe3(Float te3) {
        this.te3 = te3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_water_temperature.TE4
     *
     * @return the value of data_water_temperature.TE4
     *
     * @mbg.generated
     */
    public Float getTe4() {
        return te4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_water_temperature.TE4
     *
     * @param te4 the value for data_water_temperature.TE4
     *
     * @mbg.generated
     */
    public void setTe4(Float te4) {
        this.te4 = te4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_water_temperature.TAG
     *
     * @return the value of data_water_temperature.TAG
     *
     * @mbg.generated
     */
    public Boolean getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_water_temperature.TAG
     *
     * @param tag the value for data_water_temperature.TAG
     *
     * @mbg.generated
     */
    public void setTag(Boolean tag) {
        this.tag = tag;
    }


    ////*******自定义开始********/
    //***********自定义结束****////
}
