package com.xhkj.server.energy.dao.mybatis.vo;

import java.math.BigDecimal;

public class WeatherDataStal {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_weather_stal.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_weather_stal.STA_ID
     *
     * @mbg.generated
     */
    private String staId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_weather_stal.DAY
     *
     * @mbg.generated
     */
    private String day;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_weather_stal.Hour
     *
     * @mbg.generated
     */
    private Integer hour;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_weather_stal.PRS
     *
     * @mbg.generated
     */
    private BigDecimal prs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_weather_stal.PRS_Sea
     *
     * @mbg.generated
     */
    private BigDecimal prsSea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_weather_stal.PRS_Max
     *
     * @mbg.generated
     */
    private BigDecimal prsMax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_weather_stal.PRS_Min
     *
     * @mbg.generated
     */
    private BigDecimal prsMin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_weather_stal.TEM
     *
     * @mbg.generated
     */
    private BigDecimal tem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_weather_stal.TEM_Max
     *
     * @mbg.generated
     */
    private BigDecimal temMax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_weather_stal.TEM_Min
     *
     * @mbg.generated
     */
    private BigDecimal temMin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_weather_stal.RHU
     *
     * @mbg.generated
     */
    private BigDecimal rhu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_weather_stal.RHU_Min
     *
     * @mbg.generated
     */
    private BigDecimal rhuMin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_weather_stal.VAP
     *
     * @mbg.generated
     */
    private BigDecimal vap;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_weather_stal.PRE_1h
     *
     * @mbg.generated
     */
    private BigDecimal pre1h;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_weather_stal.WIN_D_INST_Max
     *
     * @mbg.generated
     */
    private BigDecimal winDInstMax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_weather_stal.WIN_S_Max
     *
     * @mbg.generated
     */
    private BigDecimal winSMax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_weather_stal.WIN_D_S_Max
     *
     * @mbg.generated
     */
    private BigDecimal winDSMax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_weather_stal.WIN_S_Inst_Max
     *
     * @mbg.generated
     */
    private BigDecimal winSInstMax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_weather_stal.WIN_S_Avg_10mi
     *
     * @mbg.generated
     */
    private BigDecimal winSAvg10mi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_weather_stal.WIN_D_Avg_10mi
     *
     * @mbg.generated
     */
    private BigDecimal winDAvg10mi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_weather_stal.CRT_DT
     *
     * @mbg.generated
     */
    private String crtDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_weather_stal.CRT_TM
     *
     * @mbg.generated
     */
    private String crtTm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_weather_stal.ID
     *
     * @return the value of data_weather_stal.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_weather_stal.ID
     *
     * @param id the value for data_weather_stal.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_weather_stal.STA_ID
     *
     * @return the value of data_weather_stal.STA_ID
     *
     * @mbg.generated
     */
    public String getStaId() {
        return staId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_weather_stal.STA_ID
     *
     * @param staId the value for data_weather_stal.STA_ID
     *
     * @mbg.generated
     */
    public void setStaId(String staId) {
        this.staId = staId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_weather_stal.DAY
     *
     * @return the value of data_weather_stal.DAY
     *
     * @mbg.generated
     */
    public String getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_weather_stal.DAY
     *
     * @param day the value for data_weather_stal.DAY
     *
     * @mbg.generated
     */
    public void setDay(String day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_weather_stal.Hour
     *
     * @return the value of data_weather_stal.Hour
     *
     * @mbg.generated
     */
    public Integer getHour() {
        return hour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_weather_stal.Hour
     *
     * @param hour the value for data_weather_stal.Hour
     *
     * @mbg.generated
     */
    public void setHour(Integer hour) {
        this.hour = hour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_weather_stal.PRS
     *
     * @return the value of data_weather_stal.PRS
     *
     * @mbg.generated
     */
    public BigDecimal getPrs() {
        return prs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_weather_stal.PRS
     *
     * @param prs the value for data_weather_stal.PRS
     *
     * @mbg.generated
     */
    public void setPrs(BigDecimal prs) {
        this.prs = prs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_weather_stal.PRS_Sea
     *
     * @return the value of data_weather_stal.PRS_Sea
     *
     * @mbg.generated
     */
    public BigDecimal getPrsSea() {
        return prsSea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_weather_stal.PRS_Sea
     *
     * @param prsSea the value for data_weather_stal.PRS_Sea
     *
     * @mbg.generated
     */
    public void setPrsSea(BigDecimal prsSea) {
        this.prsSea = prsSea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_weather_stal.PRS_Max
     *
     * @return the value of data_weather_stal.PRS_Max
     *
     * @mbg.generated
     */
    public BigDecimal getPrsMax() {
        return prsMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_weather_stal.PRS_Max
     *
     * @param prsMax the value for data_weather_stal.PRS_Max
     *
     * @mbg.generated
     */
    public void setPrsMax(BigDecimal prsMax) {
        this.prsMax = prsMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_weather_stal.PRS_Min
     *
     * @return the value of data_weather_stal.PRS_Min
     *
     * @mbg.generated
     */
    public BigDecimal getPrsMin() {
        return prsMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_weather_stal.PRS_Min
     *
     * @param prsMin the value for data_weather_stal.PRS_Min
     *
     * @mbg.generated
     */
    public void setPrsMin(BigDecimal prsMin) {
        this.prsMin = prsMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_weather_stal.TEM
     *
     * @return the value of data_weather_stal.TEM
     *
     * @mbg.generated
     */
    public BigDecimal getTem() {
        return tem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_weather_stal.TEM
     *
     * @param tem the value for data_weather_stal.TEM
     *
     * @mbg.generated
     */
    public void setTem(BigDecimal tem) {
        this.tem = tem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_weather_stal.TEM_Max
     *
     * @return the value of data_weather_stal.TEM_Max
     *
     * @mbg.generated
     */
    public BigDecimal getTemMax() {
        return temMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_weather_stal.TEM_Max
     *
     * @param temMax the value for data_weather_stal.TEM_Max
     *
     * @mbg.generated
     */
    public void setTemMax(BigDecimal temMax) {
        this.temMax = temMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_weather_stal.TEM_Min
     *
     * @return the value of data_weather_stal.TEM_Min
     *
     * @mbg.generated
     */
    public BigDecimal getTemMin() {
        return temMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_weather_stal.TEM_Min
     *
     * @param temMin the value for data_weather_stal.TEM_Min
     *
     * @mbg.generated
     */
    public void setTemMin(BigDecimal temMin) {
        this.temMin = temMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_weather_stal.RHU
     *
     * @return the value of data_weather_stal.RHU
     *
     * @mbg.generated
     */
    public BigDecimal getRhu() {
        return rhu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_weather_stal.RHU
     *
     * @param rhu the value for data_weather_stal.RHU
     *
     * @mbg.generated
     */
    public void setRhu(BigDecimal rhu) {
        this.rhu = rhu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_weather_stal.RHU_Min
     *
     * @return the value of data_weather_stal.RHU_Min
     *
     * @mbg.generated
     */
    public BigDecimal getRhuMin() {
        return rhuMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_weather_stal.RHU_Min
     *
     * @param rhuMin the value for data_weather_stal.RHU_Min
     *
     * @mbg.generated
     */
    public void setRhuMin(BigDecimal rhuMin) {
        this.rhuMin = rhuMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_weather_stal.VAP
     *
     * @return the value of data_weather_stal.VAP
     *
     * @mbg.generated
     */
    public BigDecimal getVap() {
        return vap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_weather_stal.VAP
     *
     * @param vap the value for data_weather_stal.VAP
     *
     * @mbg.generated
     */
    public void setVap(BigDecimal vap) {
        this.vap = vap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_weather_stal.PRE_1h
     *
     * @return the value of data_weather_stal.PRE_1h
     *
     * @mbg.generated
     */
    public BigDecimal getPre1h() {
        return pre1h;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_weather_stal.PRE_1h
     *
     * @param pre1h the value for data_weather_stal.PRE_1h
     *
     * @mbg.generated
     */
    public void setPre1h(BigDecimal pre1h) {
        this.pre1h = pre1h;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_weather_stal.WIN_D_INST_Max
     *
     * @return the value of data_weather_stal.WIN_D_INST_Max
     *
     * @mbg.generated
     */
    public BigDecimal getWinDInstMax() {
        return winDInstMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_weather_stal.WIN_D_INST_Max
     *
     * @param winDInstMax the value for data_weather_stal.WIN_D_INST_Max
     *
     * @mbg.generated
     */
    public void setWinDInstMax(BigDecimal winDInstMax) {
        this.winDInstMax = winDInstMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_weather_stal.WIN_S_Max
     *
     * @return the value of data_weather_stal.WIN_S_Max
     *
     * @mbg.generated
     */
    public BigDecimal getWinSMax() {
        return winSMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_weather_stal.WIN_S_Max
     *
     * @param winSMax the value for data_weather_stal.WIN_S_Max
     *
     * @mbg.generated
     */
    public void setWinSMax(BigDecimal winSMax) {
        this.winSMax = winSMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_weather_stal.WIN_D_S_Max
     *
     * @return the value of data_weather_stal.WIN_D_S_Max
     *
     * @mbg.generated
     */
    public BigDecimal getWinDSMax() {
        return winDSMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_weather_stal.WIN_D_S_Max
     *
     * @param winDSMax the value for data_weather_stal.WIN_D_S_Max
     *
     * @mbg.generated
     */
    public void setWinDSMax(BigDecimal winDSMax) {
        this.winDSMax = winDSMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_weather_stal.WIN_S_Inst_Max
     *
     * @return the value of data_weather_stal.WIN_S_Inst_Max
     *
     * @mbg.generated
     */
    public BigDecimal getWinSInstMax() {
        return winSInstMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_weather_stal.WIN_S_Inst_Max
     *
     * @param winSInstMax the value for data_weather_stal.WIN_S_Inst_Max
     *
     * @mbg.generated
     */
    public void setWinSInstMax(BigDecimal winSInstMax) {
        this.winSInstMax = winSInstMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_weather_stal.WIN_S_Avg_10mi
     *
     * @return the value of data_weather_stal.WIN_S_Avg_10mi
     *
     * @mbg.generated
     */
    public BigDecimal getWinSAvg10mi() {
        return winSAvg10mi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_weather_stal.WIN_S_Avg_10mi
     *
     * @param winSAvg10mi the value for data_weather_stal.WIN_S_Avg_10mi
     *
     * @mbg.generated
     */
    public void setWinSAvg10mi(BigDecimal winSAvg10mi) {
        this.winSAvg10mi = winSAvg10mi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_weather_stal.WIN_D_Avg_10mi
     *
     * @return the value of data_weather_stal.WIN_D_Avg_10mi
     *
     * @mbg.generated
     */
    public BigDecimal getWinDAvg10mi() {
        return winDAvg10mi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_weather_stal.WIN_D_Avg_10mi
     *
     * @param winDAvg10mi the value for data_weather_stal.WIN_D_Avg_10mi
     *
     * @mbg.generated
     */
    public void setWinDAvg10mi(BigDecimal winDAvg10mi) {
        this.winDAvg10mi = winDAvg10mi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_weather_stal.CRT_DT
     *
     * @return the value of data_weather_stal.CRT_DT
     *
     * @mbg.generated
     */
    public String getCrtDt() {
        return crtDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_weather_stal.CRT_DT
     *
     * @param crtDt the value for data_weather_stal.CRT_DT
     *
     * @mbg.generated
     */
    public void setCrtDt(String crtDt) {
        this.crtDt = crtDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_weather_stal.CRT_TM
     *
     * @return the value of data_weather_stal.CRT_TM
     *
     * @mbg.generated
     */
    public String getCrtTm() {
        return crtTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_weather_stal.CRT_TM
     *
     * @param crtTm the value for data_weather_stal.CRT_TM
     *
     * @mbg.generated
     */
    public void setCrtTm(String crtTm) {
        this.crtTm = crtTm;
    }


    ////*******自定义开始********/
    //***********自定义结束****////
}
